{
   "assignee" : null,
   "assignees" : [],
   "author_association" : "CONTRIBUTOR",
   "body" : "#12101 adds 2 edge cases to wallet_encryption.py, but those cases always fail with my mac. \r\n\r\n[wallet_encryption.log](https://github.com/bitcoin/bitcoin/files/1702765/wallet_encryption.log)\r\n[debug.log](https://github.com/bitcoin/bitcoin/files/1702772/debug.log)\r\n\r\nin the debug.log:\r\n```\r\n2018-02-07 10:31:10.016784 Received a POST request for / from 127.0.0.1:53758\r\n2018-02-07 10:31:10.016861 ThreadRPCServer method=walletpassphrase\r\n2018-02-07 10:31:10.120324 queue run of timer lockwallet(wallet.dat) in 1073741224 seconds (using HTTP)\r\n2018-02-07 10:31:10.121092 Received a POST request for / from 127.0.0.1:53758\r\n2018-02-07 10:31:10.121184 libevent: kevent: Invalid argument\r\n2018-02-07 10:31:10.121196 ThreadRPCServer method=getwalletinfo\r\n2018-02-07 10:31:10.121208 Exited http event loop\r\n```\r\nIt seems 1073741224 == (1 << 30) - 600 is accepted by libevent.event_add(),  but fails libevent.event_base_dispatch() via kevent() and stop http thread loop, therefore following RPC(getwalletinfo) is timed out.\r\n\r\n[enviroment]\r\nMacBook Pro (macOS 10.13.3/i7 2.2GHz/mem 16GB/SSD)\r\nBitcoin Core version v0.16.99.0-1462bde76 (release build)\r\n\r\n[how to reproduce the issue]\r\nwallet_encryption.py \r\nor\r\nbitcoin-cli walletpassphrase \"yourpassphrase\" 100000002\r\n",
   "closed_at" : null,
   "closed_by" : null,
   "comments" : 0,
   "comments_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/12375/comments",
   "created_at" : "2018-02-07T11:13:50Z",
   "events_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/12375/events",
   "html_url" : "https://github.com/bitcoin/bitcoin/issues/12375",
   "id" : 295098431,
   "labels" : [],
   "labels_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/12375/labels{/name}",
   "locked" : false,
   "milestone" : null,
   "number" : 12375,
   "repository_url" : "https://api.github.com/repos/bitcoin/bitcoin",
   "state" : "open",
   "title" : "wallet_encryption.py fails on macos",
   "updated_at" : "2018-02-07T11:13:50Z",
   "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/12375",
   "user" : {
      "avatar_url" : "https://avatars0.githubusercontent.com/u/24285095?v=4",
      "events_url" : "https://api.github.com/users/AkioNak/events{/privacy}",
      "followers_url" : "https://api.github.com/users/AkioNak/followers",
      "following_url" : "https://api.github.com/users/AkioNak/following{/other_user}",
      "gists_url" : "https://api.github.com/users/AkioNak/gists{/gist_id}",
      "gravatar_id" : "",
      "html_url" : "https://github.com/AkioNak",
      "id" : 24285095,
      "login" : "AkioNak",
      "organizations_url" : "https://api.github.com/users/AkioNak/orgs",
      "received_events_url" : "https://api.github.com/users/AkioNak/received_events",
      "repos_url" : "https://api.github.com/users/AkioNak/repos",
      "site_admin" : false,
      "starred_url" : "https://api.github.com/users/AkioNak/starred{/owner}{/repo}",
      "subscriptions_url" : "https://api.github.com/users/AkioNak/subscriptions",
      "type" : "User",
      "url" : "https://api.github.com/users/AkioNak"
   }
}
