[
   {
      "author_association" : "NONE",
      "body" : "Note: I tried to locate the message \"ignoring getheaders from peer=0 because node is in initial block download\" emitted in [net_processing.cpp:3223] [ProcessMessage], but this is not what we have in the sources here. I see this message only in very old versions of Bitcoin sources.\r\n\r\nSo Bitcoin v23 was compiled from some sources that were out of sync (probably on another test branch, not meant to be part of the release).\r\n\r\nIt seems also that the test for seeing if some lock must be released is inverted (so this can explain the 100% CPU use seen on one CPU core by a thread runing the tight loop almost forever, of waiting for some exception or event which will come only when we shut down)",
      "created_at" : "2022-08-07T13:56:17Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/25800#issuecomment-1207414185",
      "id" : 1207414185,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/25800",
      "node_id" : "IC_kwDOABII585H962p",
      "performed_via_github_app" : null,
      "reactions" : {
         "+1" : 0,
         "-1" : 0,
         "confused" : 0,
         "eyes" : 0,
         "heart" : 0,
         "hooray" : 0,
         "laugh" : 0,
         "rocket" : 0,
         "total_count" : 0,
         "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1207414185/reactions"
      },
      "updated_at" : "2022-08-07T14:00:22Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1207414185",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/1387035?v=4",
         "events_url" : "https://api.github.com/users/verdy-p/events{/privacy}",
         "followers_url" : "https://api.github.com/users/verdy-p/followers",
         "following_url" : "https://api.github.com/users/verdy-p/following{/other_user}",
         "gists_url" : "https://api.github.com/users/verdy-p/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/verdy-p",
         "id" : 1387035,
         "login" : "verdy-p",
         "node_id" : "MDQ6VXNlcjEzODcwMzU=",
         "organizations_url" : "https://api.github.com/users/verdy-p/orgs",
         "received_events_url" : "https://api.github.com/users/verdy-p/received_events",
         "repos_url" : "https://api.github.com/users/verdy-p/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/verdy-p/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/verdy-p/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/verdy-p"
      }
   },
   {
      "author_association" : "MEMBER",
      "body" : "https://github.com/bitcoin/bitcoin/blob/v23.0/src/net_processing.cpp#L3223",
      "created_at" : "2022-08-07T13:59:52Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/25800#issuecomment-1207414742",
      "id" : 1207414742,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/25800",
      "node_id" : "IC_kwDOABII585H96_W",
      "performed_via_github_app" : null,
      "reactions" : {
         "+1" : 0,
         "-1" : 0,
         "confused" : 0,
         "eyes" : 0,
         "heart" : 0,
         "hooray" : 0,
         "laugh" : 0,
         "rocket" : 0,
         "total_count" : 0,
         "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1207414742/reactions"
      },
      "updated_at" : "2022-08-07T13:59:52Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1207414742",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/548488?v=4",
         "events_url" : "https://api.github.com/users/sipa/events{/privacy}",
         "followers_url" : "https://api.github.com/users/sipa/followers",
         "following_url" : "https://api.github.com/users/sipa/following{/other_user}",
         "gists_url" : "https://api.github.com/users/sipa/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/sipa",
         "id" : 548488,
         "login" : "sipa",
         "node_id" : "MDQ6VXNlcjU0ODQ4OA==",
         "organizations_url" : "https://api.github.com/users/sipa/orgs",
         "received_events_url" : "https://api.github.com/users/sipa/received_events",
         "repos_url" : "https://api.github.com/users/sipa/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/sipa/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/sipa/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/sipa"
      }
   },
   {
      "author_association" : "NONE",
      "body" : "It seems that the way that ```LOCK(cs_main)``` are called is faulty, this is a real mess in a giant function containing many successive but exclusive if() that should be a switch to smaller functions. How are locks released when you return early without processing a message?",
      "created_at" : "2022-08-07T14:13:51Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/25800#issuecomment-1207417692",
      "id" : 1207417692,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/25800",
      "node_id" : "IC_kwDOABII585H97tc",
      "performed_via_github_app" : null,
      "reactions" : {
         "+1" : 0,
         "-1" : 0,
         "confused" : 0,
         "eyes" : 0,
         "heart" : 0,
         "hooray" : 0,
         "laugh" : 0,
         "rocket" : 0,
         "total_count" : 0,
         "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1207417692/reactions"
      },
      "updated_at" : "2022-08-07T14:13:51Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1207417692",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/1387035?v=4",
         "events_url" : "https://api.github.com/users/verdy-p/events{/privacy}",
         "followers_url" : "https://api.github.com/users/verdy-p/followers",
         "following_url" : "https://api.github.com/users/verdy-p/following{/other_user}",
         "gists_url" : "https://api.github.com/users/verdy-p/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/verdy-p",
         "id" : 1387035,
         "login" : "verdy-p",
         "node_id" : "MDQ6VXNlcjEzODcwMzU=",
         "organizations_url" : "https://api.github.com/users/verdy-p/orgs",
         "received_events_url" : "https://api.github.com/users/verdy-p/received_events",
         "repos_url" : "https://api.github.com/users/verdy-p/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/verdy-p/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/verdy-p/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/verdy-p"
      }
   },
   {
      "author_association" : "NONE",
      "body" : "Anyway I do not understand why a node A in IBD (having for example here 300K blocks synchronized) that is connecting to a full node B (which is fully in sync with 760K blocks for now) and requests it a set of headers, gets these headers, but then node B needs to request headers to node A: how can a full node in sync request any headers (in the 760K blocks) to a node in IBD which does not have them, when node B ***knows*** that node A was just syncing (in the 300K blocks, several years behind)?\r\n\r\nNote that my node and the remote node were both using the v23 version of Bitcoin core... v23 seems to work OK only for a node that is already in sync (or not too far behind, so that a single headers request at most would allow them to know they are in sync). I've also seen in Bitcoin.io that v23 nodes seem now to be frequently stalling near the best tip. They apparently need to be regularly shut down and restarted to resync them.\r\n\r\nIn other words the logic for sync'ing nodes (even those that are not in IBD) is broken now in v23.",
      "created_at" : "2022-08-07T15:40:18Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/25800#issuecomment-1207433696",
      "id" : 1207433696,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/25800",
      "node_id" : "IC_kwDOABII585H9_ng",
      "performed_via_github_app" : null,
      "reactions" : {
         "+1" : 0,
         "-1" : 0,
         "confused" : 0,
         "eyes" : 0,
         "heart" : 0,
         "hooray" : 0,
         "laugh" : 0,
         "rocket" : 0,
         "total_count" : 0,
         "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1207433696/reactions"
      },
      "updated_at" : "2022-08-07T15:44:57Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1207433696",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/1387035?v=4",
         "events_url" : "https://api.github.com/users/verdy-p/events{/privacy}",
         "followers_url" : "https://api.github.com/users/verdy-p/followers",
         "following_url" : "https://api.github.com/users/verdy-p/following{/other_user}",
         "gists_url" : "https://api.github.com/users/verdy-p/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/verdy-p",
         "id" : 1387035,
         "login" : "verdy-p",
         "node_id" : "MDQ6VXNlcjEzODcwMzU=",
         "organizations_url" : "https://api.github.com/users/verdy-p/orgs",
         "received_events_url" : "https://api.github.com/users/verdy-p/received_events",
         "repos_url" : "https://api.github.com/users/verdy-p/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/verdy-p/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/verdy-p/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/verdy-p"
      }
   },
   {
      "author_association" : "NONE",
      "body" : "Note also that even if downloading headers stalls (only advanced by about 1000 blocks at each run), the number of fully downloaded blocks NEVER progresses; all the available ones are already indexed, have their \"rev*dat\" file ready, the transaction indexi and coinbase indexes seem to progress (but only according to logs: in fact, some of them are merged to regenerate a new top index while the previous top index is deleted; there remains only indexes for the very old blocks); but according to statistics we are froen always to the same full block.\r\n\r\nI've enabled all documented \"check*\" options and validations, no probelm or corruption is ever detected.\r\nHave you tried to resync any FRESH full node recently (with no other data)?\r\nIs it likelty that some parts of full data for some blocks are ONLY available via Tor and not from any other node in the P2P network (via IPv4, IPVv6, or I2P), and not available even in so called \"full nodes\"? Or that I'm stuck in a dead branch of the network each time I try (note that my node is reachable via both IPv4 and IPv6, it uses UPnP for NAT over IPv4, but IPv6 is direct), and that my IPs are not reachable from some parts of the Internet, so that I need to use proxies?\r\n",
      "created_at" : "2022-08-07T17:12:33Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/25800#issuecomment-1207448708",
      "id" : 1207448708,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/25800",
      "node_id" : "IC_kwDOABII585H-DSE",
      "performed_via_github_app" : null,
      "reactions" : {
         "+1" : 0,
         "-1" : 0,
         "confused" : 0,
         "eyes" : 0,
         "heart" : 0,
         "hooray" : 0,
         "laugh" : 0,
         "rocket" : 0,
         "total_count" : 0,
         "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1207448708/reactions"
      },
      "updated_at" : "2022-08-07T17:12:33Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1207448708",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/1387035?v=4",
         "events_url" : "https://api.github.com/users/verdy-p/events{/privacy}",
         "followers_url" : "https://api.github.com/users/verdy-p/followers",
         "following_url" : "https://api.github.com/users/verdy-p/following{/other_user}",
         "gists_url" : "https://api.github.com/users/verdy-p/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/verdy-p",
         "id" : 1387035,
         "login" : "verdy-p",
         "node_id" : "MDQ6VXNlcjEzODcwMzU=",
         "organizations_url" : "https://api.github.com/users/verdy-p/orgs",
         "received_events_url" : "https://api.github.com/users/verdy-p/received_events",
         "repos_url" : "https://api.github.com/users/verdy-p/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/verdy-p/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/verdy-p/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/verdy-p"
      }
   },
   {
      "author_association" : "NONE",
      "body" : "After (too many) tests, I just figured out what to do: STOPPING using the QT UI for the IBD.\r\n\r\nYou may use te QT Interface just to start and try the configuration, but for the IBD it is unreliable.\r\n\r\nThis bug seems to be caused by Qt's own internal threads for its UI, adding it own unsynchronized locks or managing other condurrent threads used by Bitcoin incorrectly, or it could be a bug in the Qt integration inside the BitCoin Core UI.\r\n\r\nAlso I note that bitcointd is much faster than bitcoin-qt to progress in the IBD phase.\r\n\r\nOnce the IBD phase is complete. you can interrupt bitcoind (CTRL+C is safe, and it terminates much faster), if you want to continue with the QT UI (which will not consume a lot of CPU/disk/net resources). However I've noted frequently that the QT version can corrupt some indexes. The Qt integrationis not completely thread safe and has race isues.\r\n\r\nIMHO, the QT version should run the daemon only in a separate process (which could be registered in Windows as a standard \"service\", without any attached console), and control it with its RPC/IPC interface. Stopping the QT interface should not stop the daemon, unless we click a button to stop the daemon by its RPC/IPC interface (or via Windows services API).\r\n\r\nAs well there should be an option to send logs not in a flat file, but to Windows Events, where they could be compressed and managed automatically with a circular buffer (internally Windows Events will be packed in *.evtx or *.etl files and have a type handler managing common strings and formaters): this also saves a lot of I/O; Windows provides tools to dump these events into a flat file if needed, and to also filter them by sources, event type IDs, or sort them in different order. This would be mostly useful for log events generated by the daemon (debug logs for the QT interface can remain in flat files, or could be sent to a different source category in Windows Events).\r\n\r\n----\r\n\r\nNote also that I use a dedicated storage partition only for the /Bitcoin data files and NOT the main system partition.\r\n\r\nI have also formatted it not with the default cluster sizes (4KB) but increased it to clusters of 256KB (because most files are very large): this significantly improves the I/O, reduces the filesystem overhead in terms of I/O and memory for the filesystem structures (allocation bitmaps are smaller and modified much less often, because database files, undo files, index files, redo-logs, and debug log files are all allocated incrementally and in parallel), it improves the filesystem cache, reduces the fragmentation a lot (when the store is on harddisks, even on a fast array), so we also get reduced latency.\r\n\r\nThis also greatly facilitates maintenance.",
      "created_at" : "2022-08-07T20:08:17Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/25800#issuecomment-1207476578",
      "id" : 1207476578,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/25800",
      "node_id" : "IC_kwDOABII585H-KFi",
      "performed_via_github_app" : null,
      "reactions" : {
         "+1" : 0,
         "-1" : 0,
         "confused" : 0,
         "eyes" : 0,
         "heart" : 0,
         "hooray" : 0,
         "laugh" : 0,
         "rocket" : 0,
         "total_count" : 0,
         "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1207476578/reactions"
      },
      "updated_at" : "2022-08-07T20:25:16Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1207476578",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/1387035?v=4",
         "events_url" : "https://api.github.com/users/verdy-p/events{/privacy}",
         "followers_url" : "https://api.github.com/users/verdy-p/followers",
         "following_url" : "https://api.github.com/users/verdy-p/following{/other_user}",
         "gists_url" : "https://api.github.com/users/verdy-p/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/verdy-p",
         "id" : 1387035,
         "login" : "verdy-p",
         "node_id" : "MDQ6VXNlcjEzODcwMzU=",
         "organizations_url" : "https://api.github.com/users/verdy-p/orgs",
         "received_events_url" : "https://api.github.com/users/verdy-p/received_events",
         "repos_url" : "https://api.github.com/users/verdy-p/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/verdy-p/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/verdy-p/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/verdy-p"
      }
   },
   {
      "author_association" : "NONE",
      "body" : "Permanent solution is to downgrade to 22.0",
      "created_at" : "2022-08-07T21:09:01Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/25800#issuecomment-1207485817",
      "id" : 1207485817,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/25800",
      "node_id" : "IC_kwDOABII585H-MV5",
      "performed_via_github_app" : null,
      "reactions" : {
         "+1" : 0,
         "-1" : 0,
         "confused" : 0,
         "eyes" : 0,
         "heart" : 0,
         "hooray" : 0,
         "laugh" : 0,
         "rocket" : 0,
         "total_count" : 0,
         "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1207485817/reactions"
      },
      "updated_at" : "2022-08-07T21:12:10Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1207485817",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/98498676?v=4",
         "events_url" : "https://api.github.com/users/memz13155n/events{/privacy}",
         "followers_url" : "https://api.github.com/users/memz13155n/followers",
         "following_url" : "https://api.github.com/users/memz13155n/following{/other_user}",
         "gists_url" : "https://api.github.com/users/memz13155n/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/memz13155n",
         "id" : 98498676,
         "login" : "memz13155n",
         "node_id" : "U_kgDOBd74dA",
         "organizations_url" : "https://api.github.com/users/memz13155n/orgs",
         "received_events_url" : "https://api.github.com/users/memz13155n/received_events",
         "repos_url" : "https://api.github.com/users/memz13155n/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/memz13155n/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/memz13155n/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/memz13155n"
      }
   },
   {
      "author_association" : "NONE",
      "body" : "No, version 22.0 has the same issue (though it does not have the bug present in the EXE installer for Windows caused by ASLR, due to a bug in MAKENSIS which creates an invalid EXE by when it appends the \"pcode\" compiled from the nsis.ini script, and then appends the compressed files, because it does not correctly manages the relations that are placed after them, but forgets to update the PE EXE header to the new placement of the relocation section in the EXE file)\r\n\r\nv22 tools has the same issue with the IBD which stalls as well if you use the QT interface (in addition, the bitcoin-qt.exe also corrupts the indexes; Qt is unsafe as it silently changes some global settings in the C runtime environment, and the LevelDB is also affected; it seems that Qt temporarily changes the current working directory, and files accessed by LeevlDB do not seem to specify the absolute path, so there are race conditions where some Qt threads may affect concurrent LevelDB threads.\r\n\r\nIF you use only the CLI daemon (v22 or v23), there's no such conflict and race conditions; it is faster in both cases than their QT version; but the v23 includes many fixes (multiple ones being critical) still not present in the v22 binaries (and not backported in the v22 sources).\r\n\r\nI just hope that a new v23 will be recreated soon (and there are other bugs pending to be solved, already present in the sources, but not in the precompiled binaries).\r\n\r\nIn my opinon the QT version of the daemon has not been seriously tested. And trying to link the daemon with the QT interface is an error; the QT interface should spawn or control the regular CLI daemon",
      "created_at" : "2022-08-07T23:58:35Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/25800#issuecomment-1207512664",
      "id" : 1207512664,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/25800",
      "node_id" : "IC_kwDOABII585H-S5Y",
      "performed_via_github_app" : null,
      "reactions" : {
         "+1" : 0,
         "-1" : 0,
         "confused" : 0,
         "eyes" : 0,
         "heart" : 0,
         "hooray" : 0,
         "laugh" : 0,
         "rocket" : 0,
         "total_count" : 0,
         "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1207512664/reactions"
      },
      "updated_at" : "2022-08-07T23:58:35Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1207512664",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/1387035?v=4",
         "events_url" : "https://api.github.com/users/verdy-p/events{/privacy}",
         "followers_url" : "https://api.github.com/users/verdy-p/followers",
         "following_url" : "https://api.github.com/users/verdy-p/following{/other_user}",
         "gists_url" : "https://api.github.com/users/verdy-p/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/verdy-p",
         "id" : 1387035,
         "login" : "verdy-p",
         "node_id" : "MDQ6VXNlcjEzODcwMzU=",
         "organizations_url" : "https://api.github.com/users/verdy-p/orgs",
         "received_events_url" : "https://api.github.com/users/verdy-p/received_events",
         "repos_url" : "https://api.github.com/users/verdy-p/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/verdy-p/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/verdy-p/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/verdy-p"
      }
   },
   {
      "author_association" : "NONE",
      "body" : "Learning from this, just use the CLI version of bitcoin core by running bitcoind.exe on cmd and have another cmd session to interface with the wallet using another executable (I think it is bitcoin-cli.exe)",
      "created_at" : "2022-08-08T18:15:50Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/25800#issuecomment-1208452260",
      "id" : 1208452260,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/25800",
      "node_id" : "IC_kwDOABII585IB4Sk",
      "performed_via_github_app" : null,
      "reactions" : {
         "+1" : 0,
         "-1" : 0,
         "confused" : 0,
         "eyes" : 0,
         "heart" : 0,
         "hooray" : 0,
         "laugh" : 0,
         "rocket" : 0,
         "total_count" : 0,
         "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1208452260/reactions"
      },
      "updated_at" : "2022-08-08T18:16:15Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1208452260",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/98498676?v=4",
         "events_url" : "https://api.github.com/users/memz13155n/events{/privacy}",
         "followers_url" : "https://api.github.com/users/memz13155n/followers",
         "following_url" : "https://api.github.com/users/memz13155n/following{/other_user}",
         "gists_url" : "https://api.github.com/users/memz13155n/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/memz13155n",
         "id" : 98498676,
         "login" : "memz13155n",
         "node_id" : "U_kgDOBd74dA",
         "organizations_url" : "https://api.github.com/users/memz13155n/orgs",
         "received_events_url" : "https://api.github.com/users/memz13155n/received_events",
         "repos_url" : "https://api.github.com/users/memz13155n/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/memz13155n/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/memz13155n/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/memz13155n"
      }
   },
   {
      "author_association" : "NONE",
      "body" : "Also I've discovered that in some cases, during the IBD phase, if we have too many open connections with other peers, we exhaust the maximum number of allowed open files in the whole process.\r\nAs a result we get a status saying \"Error: Error reading from database, shutting down.\"\r\n\r\nBut what is worse is that during that shutdown, Bitcoind or Bitcoin-qt is unable to save its current indexing: it should first close all peer connections, make sure that they don't have threads open in existing LevelDB files or on block files, BEFORE finally saving the indexing state. This occurs much more often with the QT version probably beaue Qt itself uses many additional file handles.\r\n\r\nSo Bitcoin core is not properly handling cases where it cannot open files. If this occurs, an exception handler should first seek to terminate connections to peers with lower priority (notably incoming peers before outgoing peers).\r\n\r\nAs well there are visibly leaks of open file handles if we leave Bitcoin Core open for a long time, especially during the IBD phase. The work around for that is to run the IBD phase for a limited time (e.g. stop after half an hour). Bitcoin core should in fact make such cleanup, possibly closing all connections to peers regularly, flushing its indexing state.\r\n\r\nAs well it should NOT cleanup all files in the chainstate immediately, but should preserve at least the previous valid manifest and its attached lbd files. If ever there's been a corruption because it could not save the last chainstate, at least it has a way to restart from the previous manifest, and may be me more conservative by limiting the number of peers with which it interacts (for now there's no limit at all, and during the IBD, remote peers can request any data from anywhere, in any order, and this locks too many files, more that what is allowed in the configuration.\r\n\r\nBy default it accepts up to 125 peers, and about 2000 open files, but during the IBD and if you have multiple indexes in construction, that limit is easily exhausted (notably when you run it over a Gigabit  Internet connection): you cannot safely run the IBD phase and at the same time allow the construction of several additional indexes in parallel (e.g. with blockfilterindex=1, coinstatsindex=1, peerblockfilters=1, peerbloomfilters=1: you can only enable them one by one, after you'ev succesfully finished the IBD and each of the following phases for other indexes).\r\n\r\nSuch forced shutdown (which incorrectly states that the \"blocks are corrupted\", when in fact it could not even open them because of internal resource limits) leaving the chainstate after the shutdown in an inconsistant state (I've checked the blocks they were perfectly correct, it's just that Bitcoin Core could not open them!) and it is very harmful (because we've lost the chainstate which becomes unrecoverable and has to be reindexed once again from the begining) and as opposed to what is said, this has nothing to do with a hardware problem on the sorage or with the memory: it is architectural in the app, which does not use safe management of its own resources usage, even if the host can perfectly support more! The so called \"corruption\" is generated by Bitcoin Core itself by not properly tracking its own internal errors for its own resource usages, whose given diagnostics are wrong about their effective cause).\r\n\r\nAlso I wonder why, with the option \"reindex-chainstate\", Bitcoin core will not just run without accepting ANY incoming connections; it may just open 1 outgoing connection to a full peer, and it should be sufficient for the time needed to recover the chainstate to the last block.",
      "created_at" : "2022-08-11T07:38:08Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/25800#issuecomment-1211647918",
      "id" : 1211647918,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/25800",
      "node_id" : "IC_kwDOABII585IOEeu",
      "performed_via_github_app" : null,
      "reactions" : {
         "+1" : 0,
         "-1" : 0,
         "confused" : 0,
         "eyes" : 0,
         "heart" : 0,
         "hooray" : 0,
         "laugh" : 0,
         "rocket" : 0,
         "total_count" : 0,
         "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1211647918/reactions"
      },
      "updated_at" : "2022-08-11T07:42:42Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1211647918",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/1387035?v=4",
         "events_url" : "https://api.github.com/users/verdy-p/events{/privacy}",
         "followers_url" : "https://api.github.com/users/verdy-p/followers",
         "following_url" : "https://api.github.com/users/verdy-p/following{/other_user}",
         "gists_url" : "https://api.github.com/users/verdy-p/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/verdy-p",
         "id" : 1387035,
         "login" : "verdy-p",
         "node_id" : "MDQ6VXNlcjEzODcwMzU=",
         "organizations_url" : "https://api.github.com/users/verdy-p/orgs",
         "received_events_url" : "https://api.github.com/users/verdy-p/received_events",
         "repos_url" : "https://api.github.com/users/verdy-p/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/verdy-p/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/verdy-p/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/verdy-p"
      }
   },
   {
      "author_association" : "NONE",
      "body" : "another proof that the logic for IBD is wrong and stalls after one of many retries without any success:\r\n\r\n```\r\n2022-08-11T12:10:31Z init message: Loading block indexâ¦\r\n2022-08-11T12:10:31Z Switching active chainstate to Chainstate [ibd] @ height -1 (null)\r\n2022-08-11T12:10:31Z Opening LevelDB in G:\\Bitcoin\\blocks\\index\r\n2022-08-11T12:10:31Z Opened LevelDB successfully\r\n2022-08-11T12:10:31Z Using obfuscation key for G:\\Bitcoin\\blocks\\index: 0000000000000000\r\n2022-08-11T12:10:35Z LoadBlockIndexDB: last block file = 2611\r\n2022-08-11T12:10:35Z LoadBlockIndexDB: last block file info: CBlockFileInfo(blocks=12, size=15108850, heights=686224...686609, time=2021-06-04...2021-06-07)\r\n2022-08-11T12:10:35Z Checking all blk files are present...\r\n2022-08-11T12:10:36Z Opening LevelDB in G:\\Bitcoin\\chainstate\r\n2022-08-11T12:10:36Z Opened LevelDB successfully\r\n2022-08-11T12:10:36Z Using obfuscation key for G:\\Bitcoin\\chainstate: ea53eab331512c62\r\n2022-08-11T12:10:36Z Loaded best chain: hashBestChain=00000000000000003a8d7be745e0515c78b51014311f20235327855bdd1e87e4 height=277116 date=2013-12-26T21:18:12Z progress=0.039674\r\n2022-08-11T12:10:36Z init message: Verifying blocksâ¦\r\n2022-08-11T12:10:36Z Verifying last 6 blocks at level 3\r\n2022-08-11T12:10:36Z [0%]...[16%]...[33%]...[50%]...[66%]...[83%]...[99%]...[DONE].\r\n2022-08-11T12:10:36Z No coin database inconsistencies in last 6 blocks (2745 transactions)\r\n2022-08-11T12:10:36Z  block index            5193ms\r\n2022-08-11T12:10:36Z block tree size = 748958\r\n2022-08-11T12:10:36Z nBestHeight = 277116\r\n2022-08-11T12:10:36Z loadblk thread start\r\n2022-08-11T12:10:36Z Imported mempool transactions from disk: 0 succeeded, 0 failed, 0 expired, 0 already there, 0 waiting for initial broadcast\r\n2022-08-11T12:10:36Z loadblk thread exit\r\n2022-08-11T12:10:36Z torcontrol thread start\r\n2022-08-11T12:10:36Z AddLocal([2a01:e0a:30:2b70::4925:5939]:8333,1)\r\n2022-08-11T12:10:36Z Discover: JUPITER - 2a01:e0a:30:2b70::4925:5939\r\n2022-08-11T12:10:36Z Bound to 127.0.0.1:8334\r\n2022-08-11T12:10:36Z Bound to [::]:8333\r\n2022-08-11T12:10:36Z Bound to 0.0.0.0:8333\r\n2022-08-11T12:10:36Z Loaded 2 addresses from \"anchors.dat\"\r\n2022-08-11T12:10:36Z 2 block-relay-only anchors will be tried for connections.\r\n2022-08-11T12:10:36Z init message: Starting network threadsâ¦\r\n2022-08-11T12:10:36Z net thread start\r\n2022-08-11T12:10:36Z dnsseed thread start\r\n2022-08-11T12:10:36Z Waiting 300 seconds before querying DNS seeds.\r\n2022-08-11T12:10:36Z addcon thread start\r\n2022-08-11T12:10:36Z opencon thread start\r\n2022-08-11T12:10:36Z init message: Done loading\r\n2022-08-11T12:10:36Z msghand thread start\r\n2022-08-11T12:10:37Z New outbound peer connected: version: 70016, blocks=748973, peer=0 (block-relay-only)\r\n2022-08-11T12:10:37Z New outbound peer connected: version: 70016, blocks=748973, peer=1 (block-relay-only)\r\n2022-08-11T12:10:49Z New outbound peer connected: version: 70016, blocks=748973, peer=2 (outbound-full-relay)\r\n2022-08-11T12:10:55Z New outbound peer connected: version: 70016, blocks=748973, peer=3 (outbound-full-relay)\r\n2022-08-11T12:10:56Z New outbound peer connected: version: 70016, blocks=748973, peer=4 (outbound-full-relay)\r\n2022-08-11T12:10:56Z New outbound peer connected: version: 70016, blocks=748973, peer=5 (outbound-full-relay)\r\n2022-08-11T12:11:04Z New outbound peer connected: version: 70016, blocks=748973, peer=6 (outbound-full-relay)\r\n2022-08-11T12:11:10Z New outbound peer connected: version: 70016, blocks=748973, peer=7 (outbound-full-relay)\r\n2022-08-11T12:11:11Z New outbound peer connected: version: 70015, blocks=748973, peer=8 (outbound-full-relay)\r\n2022-08-11T12:11:11Z New outbound peer connected: version: 70015, blocks=748973, peer=9 (outbound-full-relay)\r\n2022-08-11T12:11:17Z New outbound peer connected: version: 70016, blocks=748973, peer=10 (outbound-full-relay)\r\n2022-08-11T12:11:29Z New outbound peer connected: version: 70015, blocks=748972, peer=13 (outbound-full-relay)\r\n```\r\n\r\nAnd here it stalls at nBestHeight = 277116 (still in Chainstate [ibd] @ height -1 (null)), even though it knows at startup that block tree size = 748958, and then makes outgoing connection to peers all having blocks=748973, without asking anything else to them (those peers disconnect, and the local node just continues to make outbound connections). The local node already has all blocks up to height=748958, but stops going further and noes not index them. What is it waiting for?\r\n\r\nHow many times I've tried to relaunch the daemon with -reindex-chainstate? The chainstate management is definitely broken with bad assumptions, also causing frequent crashes when it does not just stall!",
      "created_at" : "2022-08-11T12:19:02Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/25800#issuecomment-1211913053",
      "id" : 1211913053,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/25800",
      "node_id" : "IC_kwDOABII585IPFNd",
      "performed_via_github_app" : null,
      "reactions" : {
         "+1" : 0,
         "-1" : 0,
         "confused" : 0,
         "eyes" : 0,
         "heart" : 0,
         "hooray" : 0,
         "laugh" : 0,
         "rocket" : 0,
         "total_count" : 0,
         "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1211913053/reactions"
      },
      "updated_at" : "2022-08-11T12:22:58Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1211913053",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/1387035?v=4",
         "events_url" : "https://api.github.com/users/verdy-p/events{/privacy}",
         "followers_url" : "https://api.github.com/users/verdy-p/followers",
         "following_url" : "https://api.github.com/users/verdy-p/following{/other_user}",
         "gists_url" : "https://api.github.com/users/verdy-p/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/verdy-p",
         "id" : 1387035,
         "login" : "verdy-p",
         "node_id" : "MDQ6VXNlcjEzODcwMzU=",
         "organizations_url" : "https://api.github.com/users/verdy-p/orgs",
         "received_events_url" : "https://api.github.com/users/verdy-p/received_events",
         "repos_url" : "https://api.github.com/users/verdy-p/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/verdy-p/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/verdy-p/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/verdy-p"
      }
   },
   {
      "author_association" : "MEMBER",
      "body" : "What does the `getchaintips` RPC output?",
      "created_at" : "2022-08-11T12:22:02Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/25800#issuecomment-1211916045",
      "id" : 1211916045,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/25800",
      "node_id" : "IC_kwDOABII585IPF8N",
      "performed_via_github_app" : null,
      "reactions" : {
         "+1" : 0,
         "-1" : 0,
         "confused" : 0,
         "eyes" : 0,
         "heart" : 0,
         "hooray" : 0,
         "laugh" : 0,
         "rocket" : 0,
         "total_count" : 0,
         "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1211916045/reactions"
      },
      "updated_at" : "2022-08-11T12:22:02Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1211916045",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/548488?v=4",
         "events_url" : "https://api.github.com/users/sipa/events{/privacy}",
         "followers_url" : "https://api.github.com/users/sipa/followers",
         "following_url" : "https://api.github.com/users/sipa/following{/other_user}",
         "gists_url" : "https://api.github.com/users/sipa/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/sipa",
         "id" : 548488,
         "login" : "sipa",
         "node_id" : "MDQ6VXNlcjU0ODQ4OA==",
         "organizations_url" : "https://api.github.com/users/sipa/orgs",
         "received_events_url" : "https://api.github.com/users/sipa/received_events",
         "repos_url" : "https://api.github.com/users/sipa/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/sipa/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/sipa/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/sipa"
      }
   },
   {
      "author_association" : "NONE",
      "body" : "Bitcoin> bitcoin-cli.exe -getinfo\r\nChain: main\r\nBlocks: 277116\r\nHeaders: 277116\r\nVerification progress: âââââââââââââââââââââ 3.9674%\r\nDifficulty: 1180923195.258026\r\n\r\nNetwork: in 0, out 0, total 0\r\nVersion: 230000\r\nTime offset (s): 0\r\nProxies: n/a\r\nMin tx relay fee rate (BTC/kvB): 0.00001000\r\n\r\n(this is when it stalls, only the \"Network: in 0, out 0, total 0\" line changes with the number of peers connected and disconnecting continuously)\r\n\r\nI can press CTRL+C, the daamon will exit normally without error, and I can relauch it, nothing changes. the chaintips never changes, and it is never updated even when I activate the option \"-debug=all\" to get more logs.\r\n\r\nI can use v22 or v23 (only from the published releases, I did not compile them) I get the same.\r\n\r\nMore details with \"debug=all\":\r\n\r\n```\r\n2022-08-11T12:35:30Z received: getheaders (1029 bytes) peer=45\r\n2022-08-11T12:35:30Z Ignoring getheaders from peer=45 because node is in initial block download\r\n2022-08-11T12:35:31Z received: pong (8 bytes) peer=45\r\n2022-08-11T12:35:32Z socket closed for peer=31\r\n2022-08-11T12:35:32Z disconnecting peer=31\r\n2022-08-11T12:35:32Z Cleared nodestate for peer=31\r\n2022-08-11T12:35:32Z initial getheaders (277115) to peer=41 (startheight:748977)\r\n2022-08-11T12:35:32Z sending getheaders (997 bytes) peer=41\r\n2022-08-11T12:35:32Z Selected 2.61.65.59:8333 from new\r\n2022-08-11T12:35:32Z trying connection 2.61.65.59:8333 lastseen=49.3hrs\r\n2022-08-11T12:35:32Z sending addr (31 bytes) peer=38\r\n2022-08-11T12:35:32Z received: headers (162003 bytes) peer=41\r\n2022-08-11T12:35:32Z AcceptBlockHeader: block 0000000000000002cdf7bce4c09c0849f789a9508d812d3ca430429f6213688b is marked invalid\r\n2022-08-11T12:35:32Z Misbehaving: peer=41 (0 -> 100) DISCOURAGE THRESHOLD EXCEEDED: invalid header received\r\n2022-08-11T12:35:32Z Disconnecting and discouraging peer 41!\r\n2022-08-11T12:35:32Z disconnect by subnet matched peer=41; disconnecting\r\n2022-08-11T12:35:32Z disconnecting peer=41\r\n2022-08-11T12:35:32Z Cleared nodestate for peer=41\r\n2022-08-11T12:35:32Z initial getheaders (277115) to peer=36 (startheight:748977)\r\n2022-08-11T12:35:32Z sending getheaders (997 bytes) peer=36\r\n2022-08-11T12:35:33Z received: headers (162003 bytes) peer=36\r\n2022-08-11T12:35:33Z AcceptBlockHeader: block 0000000000000002cdf7bce4c09c0849f789a9508d812d3ca430429f6213688b is marked invalid\r\n2022-08-11T12:35:33Z Misbehaving: peer=36 (0 -> 100) DISCOURAGE THRESHOLD EXCEEDED: invalid header received\r\n2022-08-11T12:35:33Z Disconnecting and discouraging peer 36!\r\n2022-08-11T12:35:33Z disconnect by subnet matched peer=36; disconnecting\r\n2022-08-11T12:35:33Z disconnecting peer=36\r\n2022-08-11T12:35:33Z Cleared nodestate for peer=36\r\n2022-08-11T12:35:33Z initial getheaders (277115) to peer=34 (startheight:748977)\r\n2022-08-11T12:35:33Z sending getheaders (997 bytes) peer=34\r\n2022-08-11T12:35:33Z received: headers (162003 bytes) peer=34\r\n2022-08-11T12:35:33Z AcceptBlockHeader: block 0000000000000002cdf7bce4c09c0849f789a9508d812d3ca430429f6213688b is marked invalid\r\n2022-08-11T12:35:33Z Misbehaving: peer=34 (0 -> 100) DISCOURAGE THRESHOLD EXCEEDED: invalid header received\r\n2022-08-11T12:35:33Z Disconnecting and discouraging peer 34!\r\n2022-08-11T12:35:33Z disconnect by subnet matched peer=34; disconnecting\r\n2022-08-11T12:35:33Z disconnecting peer=34\r\n2022-08-11T12:35:33Z Cleared nodestate for peer=34\r\n2022-08-11T12:35:33Z initial getheaders (277115) to peer=33 (startheight:748977)\r\n2022-08-11T12:35:33Z sending getheaders (997 bytes) peer=33\r\n2022-08-11T12:35:33Z received: headers (162003 bytes) peer=33\r\n2022-08-11T12:35:33Z AcceptBlockHeader: block 0000000000000002cdf7bce4c09c0849f789a9508d812d3ca430429f6213688b is marked invalid\r\n2022-08-11T12:35:33Z Misbehaving: peer=33 (0 -> 100) DISCOURAGE THRESHOLD EXCEEDED: invalid header received\r\n2022-08-11T12:35:33Z Disconnecting and discouraging peer 33!\r\n2022-08-11T12:35:33Z disconnect by subnet matched peer=33; disconnecting\r\n2022-08-11T12:35:33Z disconnecting peer=33\r\n2022-08-11T12:35:33Z Cleared nodestate for peer=33\r\n2022-08-11T12:35:33Z initial getheaders (277115) to peer=38 (startheight:748971)\r\n2022-08-11T12:35:33Z sending getheaders (997 bytes) peer=38\r\n2022-08-11T12:35:34Z received: inv (397 bytes) peer=35\r\n2022-08-11T12:35:34Z got inv: wtx 44fd2ca0a4e5554690cd35871cf9da6a122c247b070504525351582fa1c7de37  new peer=35\r\n2022-08-11T12:35:34Z got inv: wtx 29d1039191288ff05646be90af2236f7e3161365dc5857980f3a8189c9c5754a  new peer=35\r\n2022-08-11T12:35:34Z got inv: wtx 254600576b8891f6389bae1151ef3b72ee8c8d1a2f633165a069705e60ccc694  new peer=35\r\n2022-08-11T12:35:34Z got inv: wtx 19c968d92c93c5a9f6c25220762f9d41c4b6dec83ab70b724668c3a6536c0773  new peer=35\r\n2022-08-11T12:35:34Z got inv: wtx 3f9fe1d48bac7d20fc33e688f18667473b959739716c436b0f5479ee7bf7a346  new peer=35\r\n2022-08-11T12:35:34Z got inv: wtx 288ff0886891bae9fa1471db7c7a909f3b3ec015e3ca0f407b32889eb44ea259  new peer=35\r\n2022-08-11T12:35:34Z got inv: wtx 3aba4502674f4c46de3b2916647793f081aebc31b134d700d4ab8d798d2b1b6d  new peer=35\r\n2022-08-11T12:35:34Z got inv: wtx 1239b7f6ff54ab12c7b1d5730d7a2ea4a827e559d3e8461ccee06ab58ac7e470  new peer=35\r\n2022-08-11T12:35:34Z got inv: wtx 2b13fe8c8e41401a5c17b6d241cde283cee18b974ed7379dfa3b46f1e435979b  new peer=35\r\n2022-08-11T12:35:34Z got inv: wtx 16bfe62a3e9d8fd2c8f8e93086e73218a4de9a38eb77c4893e66b9ef5ea4c106  new peer=35\r\n2022-08-11T12:35:34Z got inv: wtx abc6b8fd20904a859715114cda786af8ce6f58ab1286f9be14eb457ba38b8558  new peer=35\r\n2022-08-11T12:35:37Z connection attempt to 2.61.65.59:8333 timed out\r\n```\r\n\r\nDo I always find only \"misbehaving\" nodes? Or isn't Bitcoin Core v22+ itself misbehaving?\r\n\r\nNote that I have stopped since long trying to use the QT version (which bugs too much often). I just use the command line daemon (bitcoind) and the command line CLI query client (bitcoin-cli). In all cases these stalls or crashes are inside the management of the chainstate (there's no corruption at all in the downloaded blocks) occuring at random position (with the same valid blocks downloaded I can restart \"reindex-chainstate\", it always fails.\r\n\r\nIf I restart with \"reindex\" it forces downloading again the whole blocks, but when performing binary compares with a backup of blocks from previous runs, they are strictly identical (except \"block00000.dat\" which is special and contains the current root of the tree, updated at each run).\r\n\r\nI thought my PC was too fast, and my Gigabit figer internet too fast. I tried running the daemon in a Linux VM, by restricting its amount of memory and network bandwidth allocated in the hypervisor. Still I get the same results: It's never possible to terminate the IBD, I always get crashes by corruptions in the chainstate (some *.ldb files were deleted too early after a merge, even though they were still needed for other upper *.ldb files files; or I got the chainstate stalled as well in the IBD, and no corruption detected by the daemon).\r\n\r\nI don't know what kind of machine or specific configuration can really make Bitcoin Core working and succeed in their IBD phase.\r\n\r\nOr the Bitcoin chain already and really contains invalid blocks (that were rejected much longer after they were first accepted), that can't be eliminated and no progress is possible (in that case it is the whole shared Bitcoin chain which is damaged since long, or Bitcoin Core has forgotten to implement a rule to perform a safe cleanup of rejected blocks).\r\n\r\nAre there reliable Bitnode softwares **other than Bitnode Core v22+** that can be used today to run a full node with the current state of the chain?",
      "created_at" : "2022-08-11T12:23:55Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/25800#issuecomment-1211918071",
      "id" : 1211918071,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/25800",
      "node_id" : "IC_kwDOABII585IPGb3",
      "performed_via_github_app" : null,
      "reactions" : {
         "+1" : 0,
         "-1" : 0,
         "confused" : 0,
         "eyes" : 0,
         "heart" : 0,
         "hooray" : 0,
         "laugh" : 0,
         "rocket" : 0,
         "total_count" : 0,
         "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1211918071/reactions"
      },
      "updated_at" : "2022-08-11T13:06:08Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1211918071",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/1387035?v=4",
         "events_url" : "https://api.github.com/users/verdy-p/events{/privacy}",
         "followers_url" : "https://api.github.com/users/verdy-p/followers",
         "following_url" : "https://api.github.com/users/verdy-p/following{/other_user}",
         "gists_url" : "https://api.github.com/users/verdy-p/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/verdy-p",
         "id" : 1387035,
         "login" : "verdy-p",
         "node_id" : "MDQ6VXNlcjEzODcwMzU=",
         "organizations_url" : "https://api.github.com/users/verdy-p/orgs",
         "received_events_url" : "https://api.github.com/users/verdy-p/received_events",
         "repos_url" : "https://api.github.com/users/verdy-p/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/verdy-p/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/verdy-p/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/verdy-p"
      }
   },
   {
      "author_association" : "NONE",
      "body" : "And if you still think that my machine has a hardware problem, I've also tried on different PCs, and with a Linux VM hosted in Azure and Amazon. They are also failing to sync the IBD with the same symptoms in the \"chainstate\" (corruption of the chain with index *.lbd files deleted too soon, and missing, or stalling at unpredictable height).\r\n\r\nI think that those that have Bitcoin Core working on their machine had to compile it themselves. But they DO NOT use your signed binary releases (which aer most prbably not compiled correctly in a safe environment; I know you use a new build chain in \"GUIX\", but it is then not working at all: do you really test the generated binaries, which seem to be broken locally in GUIX by some unknown and unsafe/untested local customizations and patches, or running on a broken/damaged Linux installation?).\r\n\r\nMy opinion is that it is not my machines that are borken, but your \"GUIX\" environment used to produce the signed binaries. And unfortunately you've not opensourced that environment; may be you should retry by using an hypervisor like Proxmox and building a \"template\" for a safe Linux image, a safe installtion of GCC and related tools; that tempalte would then be easy to replicate when you want to make all your tests before actual releases. The sources of Bitcoin Core alone is definitely not sufficient without a safe build chain we can replicate easily. Apparently you are only testing Bitcoin core with binaries you compile on your local machines without using \"GUIX\", you never use or test the **released** signed binaries published on your official website!",
      "created_at" : "2022-08-11T13:12:02Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/25800#issuecomment-1211970713",
      "id" : 1211970713,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/25800",
      "node_id" : "IC_kwDOABII585IPTSZ",
      "performed_via_github_app" : null,
      "reactions" : {
         "+1" : 0,
         "-1" : 0,
         "confused" : 0,
         "eyes" : 0,
         "heart" : 0,
         "hooray" : 0,
         "laugh" : 0,
         "rocket" : 0,
         "total_count" : 0,
         "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1211970713/reactions"
      },
      "updated_at" : "2022-08-11T13:25:35Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1211970713",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/1387035?v=4",
         "events_url" : "https://api.github.com/users/verdy-p/events{/privacy}",
         "followers_url" : "https://api.github.com/users/verdy-p/followers",
         "following_url" : "https://api.github.com/users/verdy-p/following{/other_user}",
         "gists_url" : "https://api.github.com/users/verdy-p/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/verdy-p",
         "id" : 1387035,
         "login" : "verdy-p",
         "node_id" : "MDQ6VXNlcjEzODcwMzU=",
         "organizations_url" : "https://api.github.com/users/verdy-p/orgs",
         "received_events_url" : "https://api.github.com/users/verdy-p/received_events",
         "repos_url" : "https://api.github.com/users/verdy-p/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/verdy-p/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/verdy-p/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/verdy-p"
      }
   },
   {
      "author_association" : "MEMBER",
      "body" : "Can you report the output of `getchaintips`?",
      "created_at" : "2022-08-11T13:13:38Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/25800#issuecomment-1211972752",
      "id" : 1211972752,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/25800",
      "node_id" : "IC_kwDOABII585IPTyQ",
      "performed_via_github_app" : null,
      "reactions" : {
         "+1" : 0,
         "-1" : 0,
         "confused" : 0,
         "eyes" : 0,
         "heart" : 0,
         "hooray" : 0,
         "laugh" : 0,
         "rocket" : 0,
         "total_count" : 0,
         "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1211972752/reactions"
      },
      "updated_at" : "2022-08-11T13:13:38Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1211972752",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/548488?v=4",
         "events_url" : "https://api.github.com/users/sipa/events{/privacy}",
         "followers_url" : "https://api.github.com/users/sipa/followers",
         "following_url" : "https://api.github.com/users/sipa/following{/other_user}",
         "gists_url" : "https://api.github.com/users/sipa/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/sipa",
         "id" : 548488,
         "login" : "sipa",
         "node_id" : "MDQ6VXNlcjU0ODQ4OA==",
         "organizations_url" : "https://api.github.com/users/sipa/orgs",
         "received_events_url" : "https://api.github.com/users/sipa/received_events",
         "repos_url" : "https://api.github.com/users/sipa/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/sipa/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/sipa/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/sipa"
      }
   },
   {
      "author_association" : "NONE",
      "body" : "```\r\nbitcoin> bitcoin-cli getchaintips\r\n[\r\n  {\r\n    \"height\": 748957,\r\n    \"hash\": \"00000000000000000002997b7cf13fed750e2183d7693a24785c9f594389ee88\",\r\n    \"branchlen\": 471841,\r\n    \"status\": \"invalid\"\r\n  },\r\n  {\r\n    \"height\": 277116,\r\n    \"hash\": \"00000000000000003a8d7be745e0515c78b51014311f20235327855bdd1e87e4\",\r\n    \"branchlen\": 0,\r\n    \"status\": \"active\"\r\n  }\r\n]\r\n```\r\n\r\nDo I need to manually delete some recent blk0*.dat and rev0*.dat and restart indexing again and again? Are they caused by misbehaving nodes (or malwares) in the P2P network distributing wrong blocks and causing normal nodes in IBD to fail or stall? Is it the signal of an DoS attack again the Bitcoin chain in order to take control of it by \"ejecting\" regular nodes with such bad blocks? In that case, they are succesful in their attacks since many months! I've never been able to compleet the IBD from any machine when using Bitcoin Core. May be this is the sign that Bitcoin Core does not fully apply the \"consensus\" rules for validating new blocks, and that it accepts them too early, and is unable to rollback safely when they are detected as \"disapproved\" too much longer later. And above some limits (a big number of bad block in the chain to revert to replace one that came much earlier in the chain), it seems to crash and corrupt the \"chainstate\" index files itself.\r\n\r\nBut may be there are other competing softwares that could work such as https://www.bitcoinabc.org/ (if they've detected such attack and are able to isolate and fix it)?\r\n",
      "created_at" : "2022-08-11T13:56:44Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/25800#issuecomment-1212025604",
      "id" : 1212025604,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/25800",
      "node_id" : "IC_kwDOABII585IPgsE",
      "performed_via_github_app" : null,
      "reactions" : {
         "+1" : 0,
         "-1" : 0,
         "confused" : 0,
         "eyes" : 0,
         "heart" : 0,
         "hooray" : 0,
         "laugh" : 0,
         "rocket" : 0,
         "total_count" : 0,
         "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1212025604/reactions"
      },
      "updated_at" : "2022-08-11T14:12:59Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1212025604",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/1387035?v=4",
         "events_url" : "https://api.github.com/users/verdy-p/events{/privacy}",
         "followers_url" : "https://api.github.com/users/verdy-p/followers",
         "following_url" : "https://api.github.com/users/verdy-p/following{/other_user}",
         "gists_url" : "https://api.github.com/users/verdy-p/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/verdy-p",
         "id" : 1387035,
         "login" : "verdy-p",
         "node_id" : "MDQ6VXNlcjEzODcwMzU=",
         "organizations_url" : "https://api.github.com/users/verdy-p/orgs",
         "received_events_url" : "https://api.github.com/users/verdy-p/received_events",
         "repos_url" : "https://api.github.com/users/verdy-p/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/verdy-p/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/verdy-p/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/verdy-p"
      }
   },
   {
      "author_association" : "MEMBER",
      "body" : "So, for whatever reason, your node has marked block 277117 (0000000000000002cdf7bce4c09c0849f789a9508d812d3ca430429f6213688b) incorrectly as invalid. It's not synchronizing further, because it is treating every peer that hands it block 277177 as malicious. We'll need to figure out why that is happening. Your comment above about running out of file descriptors seems like a useful lead.\r\n\r\nFirst, we need to know if it is the block on disk itself that is corrupted, or the validation database. It's likely the latter, but to find out, run `reconsiderblock 0000000000000002cdf7bce4c09c0849f789a9508d812d3ca430429f6213688b`, and report what you see in debug.log at that time.\r\n\r\n> Do I need to manually delete some recent blk0*.dat and rev0*.dat and restart indexing again and again?\r\n\r\nIf the blocks themselves are corrupted, you'll need to use `-reindex`. If it's just the database that is corrupted, `-reindex-chainstate` should suffice. Given that it sounds like you've tried the latter several times and that doesn't help, it's either a problem with the blocks themselves, or somehow your Bitcoin Core instance is corrupting itself time after time. Looking at the `reconsiderblock` output will help figure this out.\r\n\r\n> Are they caused by misbehaving nodes (or malwares) in the P2P network distributing wrong blocks and causing normal nodes in IBD to fail or stall?\r\n\r\nMisbehaving nodes should never be able to cause Bitcoin Core to incorrectly mark a block as invalid, so no.\r\n\r\n> May be this is the sign that Bitcoin Core does not fully apply the \"consensus\" rules for validating new blocks, and that it accepts them too early\r\n\r\nNo.\r\n\r\n> But may be there are other competing softwares that could work such as https://www.bitcoinabc.org/ (if they've detected such attack and are able to isolate and fix it)?\r\n\r\nThat software is for a different currency, with different consensus rules. It will not synchronize with the Bitcoin network/chain/currency.",
      "created_at" : "2022-08-11T14:12:00Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/25800#issuecomment-1212044042",
      "id" : 1212044042,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/25800",
      "node_id" : "IC_kwDOABII585IPlMK",
      "performed_via_github_app" : null,
      "reactions" : {
         "+1" : 1,
         "-1" : 0,
         "confused" : 0,
         "eyes" : 0,
         "heart" : 0,
         "hooray" : 0,
         "laugh" : 0,
         "rocket" : 0,
         "total_count" : 1,
         "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1212044042/reactions"
      },
      "updated_at" : "2022-08-11T14:13:27Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1212044042",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/548488?v=4",
         "events_url" : "https://api.github.com/users/sipa/events{/privacy}",
         "followers_url" : "https://api.github.com/users/sipa/followers",
         "following_url" : "https://api.github.com/users/sipa/following{/other_user}",
         "gists_url" : "https://api.github.com/users/sipa/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/sipa",
         "id" : 548488,
         "login" : "sipa",
         "node_id" : "MDQ6VXNlcjU0ODQ4OA==",
         "organizations_url" : "https://api.github.com/users/sipa/orgs",
         "received_events_url" : "https://api.github.com/users/sipa/received_events",
         "repos_url" : "https://api.github.com/users/sipa/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/sipa/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/sipa/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/sipa"
      }
   },
   {
      "author_association" : "NONE",
      "body" : "I jsut ran \"bitcoin-cli reconsiderblock 0000000000000002cdf7bce4c09c0849f789a9508d812d3ca430429f6213688b\".\r\n\r\nAnd instantly the daemon restarts the IBD synchronization.\r\n\r\nI see many \"UpdateTip: new best=*\" logged.\r\n\r\nI did not have to use \"-reindex\" or \"-reindex-chainstate\".",
      "created_at" : "2022-08-11T14:15:20Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/25800#issuecomment-1212048271",
      "id" : 1212048271,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/25800",
      "node_id" : "IC_kwDOABII585IPmOP",
      "performed_via_github_app" : null,
      "reactions" : {
         "+1" : 0,
         "-1" : 0,
         "confused" : 0,
         "eyes" : 0,
         "heart" : 0,
         "hooray" : 0,
         "laugh" : 0,
         "rocket" : 0,
         "total_count" : 0,
         "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1212048271/reactions"
      },
      "updated_at" : "2022-08-11T14:16:57Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1212048271",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/1387035?v=4",
         "events_url" : "https://api.github.com/users/verdy-p/events{/privacy}",
         "followers_url" : "https://api.github.com/users/verdy-p/followers",
         "following_url" : "https://api.github.com/users/verdy-p/following{/other_user}",
         "gists_url" : "https://api.github.com/users/verdy-p/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/verdy-p",
         "id" : 1387035,
         "login" : "verdy-p",
         "node_id" : "MDQ6VXNlcjEzODcwMzU=",
         "organizations_url" : "https://api.github.com/users/verdy-p/orgs",
         "received_events_url" : "https://api.github.com/users/verdy-p/received_events",
         "repos_url" : "https://api.github.com/users/verdy-p/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/verdy-p/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/verdy-p/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/verdy-p"
      }
   },
   {
      "author_association" : "MEMBER",
      "body" : "> I see many \"UpdateTip: new best=*\" logged.\r\n\r\nYou'll need to provide the exact debug log at the exact location when the RPC `reconsiderblock` was called",
      "created_at" : "2022-08-11T14:18:05Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/25800#issuecomment-1212051539",
      "id" : 1212051539,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/25800",
      "node_id" : "IC_kwDOABII585IPnBT",
      "performed_via_github_app" : null,
      "reactions" : {
         "+1" : 0,
         "-1" : 0,
         "confused" : 0,
         "eyes" : 0,
         "heart" : 0,
         "hooray" : 0,
         "laugh" : 0,
         "rocket" : 0,
         "total_count" : 0,
         "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1212051539/reactions"
      },
      "updated_at" : "2022-08-11T14:18:05Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1212051539",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/6399679?v=4",
         "events_url" : "https://api.github.com/users/MarcoFalke/events{/privacy}",
         "followers_url" : "https://api.github.com/users/MarcoFalke/followers",
         "following_url" : "https://api.github.com/users/MarcoFalke/following{/other_user}",
         "gists_url" : "https://api.github.com/users/MarcoFalke/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/MarcoFalke",
         "id" : 6399679,
         "login" : "MarcoFalke",
         "node_id" : "MDQ6VXNlcjYzOTk2Nzk=",
         "organizations_url" : "https://api.github.com/users/MarcoFalke/orgs",
         "received_events_url" : "https://api.github.com/users/MarcoFalke/received_events",
         "repos_url" : "https://api.github.com/users/MarcoFalke/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/MarcoFalke/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/MarcoFalke/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/MarcoFalke"
      }
   },
   {
      "author_association" : "MEMBER",
      "body" : "@verdy-p Do the heights keep going up, past 277117? If so, it sounds like there may not actually have been any corruption at all, but just a one-off validation issue.\r\n",
      "created_at" : "2022-08-11T14:19:36Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/25800#issuecomment-1212053658",
      "id" : 1212053658,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/25800",
      "node_id" : "IC_kwDOABII585IPnia",
      "performed_via_github_app" : null,
      "reactions" : {
         "+1" : 0,
         "-1" : 0,
         "confused" : 0,
         "eyes" : 0,
         "heart" : 0,
         "hooray" : 0,
         "laugh" : 0,
         "rocket" : 0,
         "total_count" : 0,
         "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1212053658/reactions"
      },
      "updated_at" : "2022-08-11T14:19:36Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1212053658",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/548488?v=4",
         "events_url" : "https://api.github.com/users/sipa/events{/privacy}",
         "followers_url" : "https://api.github.com/users/sipa/followers",
         "following_url" : "https://api.github.com/users/sipa/following{/other_user}",
         "gists_url" : "https://api.github.com/users/sipa/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/sipa",
         "id" : 548488,
         "login" : "sipa",
         "node_id" : "MDQ6VXNlcjU0ODQ4OA==",
         "organizations_url" : "https://api.github.com/users/sipa/orgs",
         "received_events_url" : "https://api.github.com/users/sipa/received_events",
         "repos_url" : "https://api.github.com/users/sipa/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/sipa/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/sipa/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/sipa"
      }
   },
   {
      "author_association" : "NONE",
      "body" : "Too late... that log has been \"autocleared\" with the huge amiunt of \"UpdateTip: new best=*\" that instantly started (and I cannot recover it as well fro mthe console which has flushed it as well from its memory.\r\n\r\nYes \"bitcoin-cli getinfo\" shows that it is progressing again, as well as \"bitcoin-cli getchaintips\".\r\n\r\nNote that in the separate console where I ran \"bitcoin-cli reconsiderblock 0000000000000002cdf7bce4c09c0849f789a9508d812d3ca430429f6213688b\", the command never exited; I had to press CTRL+C to terminate the RPC session. But this does not affect the daemon which continues at fast speed.\r\n\r\nFor example I get now:\r\n````\r\nbitcoin> bitcoin-cli getchaintips\r\n[\r\n  {\r\n    \"height\": 748989,\r\n    \"hash\": \"000000000000000000081ba73135ef39612f940bc77e76240e52ef83b5f0b1e9\",\r\n    \"branchlen\": 443985,\r\n    \"status\": \"headers-only\"\r\n  },\r\n  {\r\n    \"height\": 305004,\r\n    \"hash\": \"0000000000000000162865e084d637f7e7fbd3580a2dae91abe6d47fa4ef8abe\",\r\n    \"branchlen\": 0,\r\n    \"status\": \"active\"\r\n  }\r\n]\r\n```\r\n",
      "created_at" : "2022-08-11T14:19:48Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/25800#issuecomment-1212053928",
      "id" : 1212053928,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/25800",
      "node_id" : "IC_kwDOABII585IPnmo",
      "performed_via_github_app" : null,
      "reactions" : {
         "+1" : 0,
         "-1" : 0,
         "confused" : 0,
         "eyes" : 0,
         "heart" : 0,
         "hooray" : 0,
         "laugh" : 0,
         "rocket" : 0,
         "total_count" : 0,
         "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1212053928/reactions"
      },
      "updated_at" : "2022-08-11T14:24:34Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1212053928",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/1387035?v=4",
         "events_url" : "https://api.github.com/users/verdy-p/events{/privacy}",
         "followers_url" : "https://api.github.com/users/verdy-p/followers",
         "following_url" : "https://api.github.com/users/verdy-p/following{/other_user}",
         "gists_url" : "https://api.github.com/users/verdy-p/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/verdy-p",
         "id" : 1387035,
         "login" : "verdy-p",
         "node_id" : "MDQ6VXNlcjEzODcwMzU=",
         "organizations_url" : "https://api.github.com/users/verdy-p/orgs",
         "received_events_url" : "https://api.github.com/users/verdy-p/received_events",
         "repos_url" : "https://api.github.com/users/verdy-p/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/verdy-p/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/verdy-p/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/verdy-p"
      }
   },
   {
      "author_association" : "MEMBER",
      "body" : "@verdy-p Yeah, it's expected that it doesn't exit; it'll exit whenever it is done reconsidering that block, and all other blocks whose validation is triggered by it. If all goes well, that won't be until it reaches the tip of the downloaded blocks you had before (height 748957) - or until somehow another incorrect validation error occurs.",
      "created_at" : "2022-08-11T14:24:50Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/25800#issuecomment-1212060311",
      "id" : 1212060311,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/25800",
      "node_id" : "IC_kwDOABII585IPpKX",
      "performed_via_github_app" : null,
      "reactions" : {
         "+1" : 0,
         "-1" : 0,
         "confused" : 0,
         "eyes" : 0,
         "heart" : 0,
         "hooray" : 0,
         "laugh" : 0,
         "rocket" : 0,
         "total_count" : 0,
         "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1212060311/reactions"
      },
      "updated_at" : "2022-08-11T14:24:50Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1212060311",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/548488?v=4",
         "events_url" : "https://api.github.com/users/sipa/events{/privacy}",
         "followers_url" : "https://api.github.com/users/sipa/followers",
         "following_url" : "https://api.github.com/users/sipa/following{/other_user}",
         "gists_url" : "https://api.github.com/users/sipa/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/sipa",
         "id" : 548488,
         "login" : "sipa",
         "node_id" : "MDQ6VXNlcjU0ODQ4OA==",
         "organizations_url" : "https://api.github.com/users/sipa/orgs",
         "received_events_url" : "https://api.github.com/users/sipa/received_events",
         "repos_url" : "https://api.github.com/users/sipa/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/sipa/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/sipa/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/sipa"
      }
   },
   {
      "author_association" : "NONE",
      "body" : "Could it be caused by some OS limitation (temporarily disabling write accesses for some critical operations, and sending a \"busy\" status error that Bitcoin Core does not corerctly interpret, and cannot recover just by a retry after some reasonnable delay; e.g. it could be generated by security tools, instructing a running app to \"pause\" temporarily and not allowing for example to create or delete new files in the directory containing files of the chainstate, which changes really too fast with thousands files added/deleted each minute)? It may be caused by the fact that even if we close a file handle, the OS may still maintain it internally for its own operations, and cannot allocate new file handles for some time, until the OS performs some background cleanup in the background with the filesystem.\r\n\r\nSo the issue would be that Bitcoin core fails while trying to open a new file: the OS does not accept immediately to give it a new file handle, and the error returned may indicate that the application needs to wait a bit before retrying.",
      "created_at" : "2022-08-11T14:31:26Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/25800#issuecomment-1212070234",
      "id" : 1212070234,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/25800",
      "node_id" : "IC_kwDOABII585IPrla",
      "performed_via_github_app" : null,
      "reactions" : {
         "+1" : 0,
         "-1" : 0,
         "confused" : 0,
         "eyes" : 0,
         "heart" : 0,
         "hooray" : 0,
         "laugh" : 0,
         "rocket" : 0,
         "total_count" : 0,
         "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1212070234/reactions"
      },
      "updated_at" : "2022-08-11T14:36:59Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1212070234",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/1387035?v=4",
         "events_url" : "https://api.github.com/users/verdy-p/events{/privacy}",
         "followers_url" : "https://api.github.com/users/verdy-p/followers",
         "following_url" : "https://api.github.com/users/verdy-p/following{/other_user}",
         "gists_url" : "https://api.github.com/users/verdy-p/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/verdy-p",
         "id" : 1387035,
         "login" : "verdy-p",
         "node_id" : "MDQ6VXNlcjEzODcwMzU=",
         "organizations_url" : "https://api.github.com/users/verdy-p/orgs",
         "received_events_url" : "https://api.github.com/users/verdy-p/received_events",
         "repos_url" : "https://api.github.com/users/verdy-p/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/verdy-p/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/verdy-p/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/verdy-p"
      }
   },
   {
      "author_association" : "MEMBER",
      "body" : "@verdy-p That sounds like a possibility.\r\n\r\nIf so, I would guess that whatever is going on is likely happening when Bitcoin Core is flushing the chainstate database to disk. You can trigger such a flush manually by calling `gettxoutsetinfo`, if you'd like.",
      "created_at" : "2022-08-11T14:33:38Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/25800#issuecomment-1212073126",
      "id" : 1212073126,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/25800",
      "node_id" : "IC_kwDOABII585IPsSm",
      "performed_via_github_app" : null,
      "reactions" : {
         "+1" : 0,
         "-1" : 0,
         "confused" : 0,
         "eyes" : 0,
         "heart" : 0,
         "hooray" : 0,
         "laugh" : 0,
         "rocket" : 0,
         "total_count" : 0,
         "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1212073126/reactions"
      },
      "updated_at" : "2022-08-11T14:33:38Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1212073126",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/548488?v=4",
         "events_url" : "https://api.github.com/users/sipa/events{/privacy}",
         "followers_url" : "https://api.github.com/users/sipa/followers",
         "following_url" : "https://api.github.com/users/sipa/following{/other_user}",
         "gists_url" : "https://api.github.com/users/sipa/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/sipa",
         "id" : 548488,
         "login" : "sipa",
         "node_id" : "MDQ6VXNlcjU0ODQ4OA==",
         "organizations_url" : "https://api.github.com/users/sipa/orgs",
         "received_events_url" : "https://api.github.com/users/sipa/received_events",
         "repos_url" : "https://api.github.com/users/sipa/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/sipa/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/sipa/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/sipa"
      }
   },
   {
      "author_association" : "NONE",
      "body" : "Thanks for the tip about \"bitcoin-cli gettxoutsetinfo\". It takes some minutes to complete until it returns:\r\n```\r\n{\r\n  \"height\": 347551,\r\n  \"bestblock\": \"000000000000000014f5db2548b27a532ba2d81e22ada3800e787383496da281\",\r\n  \"txouts\": 17634623,\r\n  \"bogosize\": 1340919614,\r\n  \"hash_serialized_2\": \"7a9209a30d15eade5e74248095962d82d67c1b060e91f9eb7127eac805aafbb0\",\r\n  \"total_amount\": 13938639.77152479,\r\n  \"transactions\": 4995854,\r\n  \"disk_size\": 950709316\r\n}\r\n```\r\nBut this does not seem to stop the daemon which continues adding new tips at increadible rate (I just see instantly the truncation of some \"level-0\" table for less than one second, then it continues indexing at fast rate. I get the reply from \"gettxoutsetinfo\" only a few minutes later (probably the RPC service thread has low priority to reply, most of the CPU threads are for the indexing).",
      "created_at" : "2022-08-11T14:41:14Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/25800#issuecomment-1212082213",
      "id" : 1212082213,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/25800",
      "node_id" : "IC_kwDOABII585IPugl",
      "performed_via_github_app" : null,
      "reactions" : {
         "+1" : 0,
         "-1" : 0,
         "confused" : 0,
         "eyes" : 0,
         "heart" : 0,
         "hooray" : 0,
         "laugh" : 0,
         "rocket" : 0,
         "total_count" : 0,
         "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1212082213/reactions"
      },
      "updated_at" : "2022-08-11T14:41:14Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1212082213",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/1387035?v=4",
         "events_url" : "https://api.github.com/users/verdy-p/events{/privacy}",
         "followers_url" : "https://api.github.com/users/verdy-p/followers",
         "following_url" : "https://api.github.com/users/verdy-p/following{/other_user}",
         "gists_url" : "https://api.github.com/users/verdy-p/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/verdy-p",
         "id" : 1387035,
         "login" : "verdy-p",
         "node_id" : "MDQ6VXNlcjEzODcwMzU=",
         "organizations_url" : "https://api.github.com/users/verdy-p/orgs",
         "received_events_url" : "https://api.github.com/users/verdy-p/received_events",
         "repos_url" : "https://api.github.com/users/verdy-p/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/verdy-p/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/verdy-p/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/verdy-p"
      }
   },
   {
      "author_association" : "NONE",
      "body" : "So for some reasons if the OS returns some error when opening a file, the log should detail that error (with the exact error number: it is very likely non-fatal, we should just retry after waiting a couple of seconds: there does not seem to exist any exception handler to handle this case), instead of just saying that it can't open a file and give a false guess about a corruption and exiting abruptly (and at that time, trying to flush the state of the chain before exising will also faile for the same reason, as it will need to open many files for that: at that time this crashes, and we are unable to recover with missing files).",
      "created_at" : "2022-08-11T14:46:07Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/25800#issuecomment-1212088139",
      "id" : 1212088139,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/25800",
      "node_id" : "IC_kwDOABII585IPv9L",
      "performed_via_github_app" : null,
      "reactions" : {
         "+1" : 0,
         "-1" : 0,
         "confused" : 0,
         "eyes" : 0,
         "heart" : 0,
         "hooray" : 0,
         "laugh" : 0,
         "rocket" : 0,
         "total_count" : 0,
         "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1212088139/reactions"
      },
      "updated_at" : "2022-08-11T14:47:44Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1212088139",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/1387035?v=4",
         "events_url" : "https://api.github.com/users/verdy-p/events{/privacy}",
         "followers_url" : "https://api.github.com/users/verdy-p/followers",
         "following_url" : "https://api.github.com/users/verdy-p/following{/other_user}",
         "gists_url" : "https://api.github.com/users/verdy-p/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/verdy-p",
         "id" : 1387035,
         "login" : "verdy-p",
         "node_id" : "MDQ6VXNlcjEzODcwMzU=",
         "organizations_url" : "https://api.github.com/users/verdy-p/orgs",
         "received_events_url" : "https://api.github.com/users/verdy-p/received_events",
         "repos_url" : "https://api.github.com/users/verdy-p/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/verdy-p/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/verdy-p/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/verdy-p"
      }
   },
   {
      "author_association" : "MEMBER",
      "body" : "@verdy-p If that's the issue, it's a bug inside LevelDB, which we'll be unlikely to fix on our own. At this point I would avoid jumping to any conclusions and just try to reproduce the problem so we can try things.",
      "created_at" : "2022-08-11T14:47:55Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/25800#issuecomment-1212091150",
      "id" : 1212091150,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/25800",
      "node_id" : "IC_kwDOABII585IPwsO",
      "performed_via_github_app" : null,
      "reactions" : {
         "+1" : 0,
         "-1" : 0,
         "confused" : 0,
         "eyes" : 0,
         "heart" : 0,
         "hooray" : 0,
         "laugh" : 0,
         "rocket" : 0,
         "total_count" : 0,
         "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1212091150/reactions"
      },
      "updated_at" : "2022-08-11T14:47:55Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1212091150",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/548488?v=4",
         "events_url" : "https://api.github.com/users/sipa/events{/privacy}",
         "followers_url" : "https://api.github.com/users/sipa/followers",
         "following_url" : "https://api.github.com/users/sipa/following{/other_user}",
         "gists_url" : "https://api.github.com/users/sipa/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/sipa",
         "id" : 548488,
         "login" : "sipa",
         "node_id" : "MDQ6VXNlcjU0ODQ4OA==",
         "organizations_url" : "https://api.github.com/users/sipa/orgs",
         "received_events_url" : "https://api.github.com/users/sipa/received_events",
         "repos_url" : "https://api.github.com/users/sipa/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/sipa/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/sipa/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/sipa"
      }
   },
   {
      "author_association" : "NONE",
      "body" : "It's true that I've never seen any LevelDB application creating and deleting so many indexes at such incredible rate. Generally these indexes are quite stable, they just grow slowly in size.\r\nMay be the maximum index sizes for each table is too small (2MB) for a fast machine, and we easily reach the limitation of the OS for the filesystem background operations that are likely starting as soon as we close the file (and LevelDB doesnot seem to \"sync\" the filesystem when it closes a file, it allwos the OS to perform background cleanup, but the file handle remains allocated for the process as long as the OS has not terminated those operations.\r\n\r\nDoes LevelDB uses some optimized operations that allow file close to return instantly without waiting the effective completion? such optimization does not seem to be very \"safe\". The \"close()\" operation (or delete/move/rename operation) should be blocking.\r\n\r\nBut visibly LevelDB seems to use worker threads to complete its file I/O like ni this project (using the Go language)\r\n\r\nhttps://github.com/syndtr/goleveldb/blob/master/leveldb/storage/file_storage.go\r\n\r\nLevelDB creates an increadible amount of threads if I monitor Bitcoin Core and just look at them, and the total number of file handles that are open (they are frequently \"spiking\" very high, notably when performing \"gettxoutsetinfo\")\r\n\r\nAlso I don't understand why Bitcoind core is flushing EVERYTHING including its whole cache of block data (about 760GB) according to logs to return to just a single block (about 45MB). shouldn't we split the cache in two parts, so that we flush it just in half, and then maintain two metafiles (one for the older view of the chainstate, another for the most recent, making sure that the older view will remain intact and will not be deleted as long as the new state is not finished: if the new state fails, at least we can recover from the previous state. old indexes don't need to be deleted immediately if they can be still referenced from the old state: this allow safe recovery in all cases (even if the daemon crashes for any reason and is unable to flush its state completely).",
      "created_at" : "2022-08-11T14:53:47Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/25800#issuecomment-1212101325",
      "id" : 1212101325,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/25800",
      "node_id" : "IC_kwDOABII585IPzLN",
      "performed_via_github_app" : null,
      "reactions" : {
         "+1" : 0,
         "-1" : 0,
         "confused" : 0,
         "eyes" : 0,
         "heart" : 0,
         "hooray" : 0,
         "laugh" : 0,
         "rocket" : 0,
         "total_count" : 0,
         "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1212101325/reactions"
      },
      "updated_at" : "2022-08-11T15:05:49Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1212101325",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/1387035?v=4",
         "events_url" : "https://api.github.com/users/verdy-p/events{/privacy}",
         "followers_url" : "https://api.github.com/users/verdy-p/followers",
         "following_url" : "https://api.github.com/users/verdy-p/following{/other_user}",
         "gists_url" : "https://api.github.com/users/verdy-p/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/verdy-p",
         "id" : 1387035,
         "login" : "verdy-p",
         "node_id" : "MDQ6VXNlcjEzODcwMzU=",
         "organizations_url" : "https://api.github.com/users/verdy-p/orgs",
         "received_events_url" : "https://api.github.com/users/verdy-p/received_events",
         "repos_url" : "https://api.github.com/users/verdy-p/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/verdy-p/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/verdy-p/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/verdy-p"
      }
   },
   {
      "author_association" : "MEMBER",
      "body" : "Let's focus on reproducing. I am not convinced LevelDB (or even anything related to the chainstate at all) is at fault here, because the fact that `reconsiderblock` caused things to get unstruck implies there wasn't any actual on-disk corruption.\r\n\r\n> Also I don't understand why Bitcoind core is flushing EVERYTHING including its whole cache of block data (about 760GB) \r\n\r\nOnly the chainstate database is cached by Bitcoin Core, which is a few GB typically (and only up to the dbcache setting of that is kept in memory).\r\n\r\n> according to logs to return to just a single block (about 45MB).\r\n\r\nBlocks are never more than 4 MB, and aren't stored in LevelDB (or any kind of database). They're stored in raw blk*.dat files.",
      "created_at" : "2022-08-11T15:19:47Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/25800#issuecomment-1212136090",
      "id" : 1212136090,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/25800",
      "node_id" : "IC_kwDOABII585IP7qa",
      "performed_via_github_app" : null,
      "reactions" : {
         "+1" : 0,
         "-1" : 0,
         "confused" : 0,
         "eyes" : 0,
         "heart" : 0,
         "hooray" : 0,
         "laugh" : 0,
         "rocket" : 0,
         "total_count" : 0,
         "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1212136090/reactions"
      },
      "updated_at" : "2022-08-11T15:23:04Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1212136090",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/548488?v=4",
         "events_url" : "https://api.github.com/users/sipa/events{/privacy}",
         "followers_url" : "https://api.github.com/users/sipa/followers",
         "following_url" : "https://api.github.com/users/sipa/following{/other_user}",
         "gists_url" : "https://api.github.com/users/sipa/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/sipa",
         "id" : 548488,
         "login" : "sipa",
         "node_id" : "MDQ6VXNlcjU0ODQ4OA==",
         "organizations_url" : "https://api.github.com/users/sipa/orgs",
         "received_events_url" : "https://api.github.com/users/sipa/received_events",
         "repos_url" : "https://api.github.com/users/sipa/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/sipa/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/sipa/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/sipa"
      }
   },
   {
      "author_association" : "MEMBER",
      "body" : "I'd guess the most likely cause would be a cosmic ray or old/overheated CPU/RAM, as the issue wasn't persistent.",
      "created_at" : "2022-08-11T15:31:07Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/25800#issuecomment-1212149709",
      "id" : 1212149709,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/25800",
      "node_id" : "IC_kwDOABII585IP-_N",
      "performed_via_github_app" : null,
      "reactions" : {
         "+1" : 0,
         "-1" : 0,
         "confused" : 0,
         "eyes" : 0,
         "heart" : 0,
         "hooray" : 0,
         "laugh" : 0,
         "rocket" : 0,
         "total_count" : 0,
         "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1212149709/reactions"
      },
      "updated_at" : "2022-08-11T15:31:07Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1212149709",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/6399679?v=4",
         "events_url" : "https://api.github.com/users/MarcoFalke/events{/privacy}",
         "followers_url" : "https://api.github.com/users/MarcoFalke/followers",
         "following_url" : "https://api.github.com/users/MarcoFalke/following{/other_user}",
         "gists_url" : "https://api.github.com/users/MarcoFalke/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/MarcoFalke",
         "id" : 6399679,
         "login" : "MarcoFalke",
         "node_id" : "MDQ6VXNlcjYzOTk2Nzk=",
         "organizations_url" : "https://api.github.com/users/MarcoFalke/orgs",
         "received_events_url" : "https://api.github.com/users/MarcoFalke/received_events",
         "repos_url" : "https://api.github.com/users/MarcoFalke/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/MarcoFalke/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/MarcoFalke/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/MarcoFalke"
      }
   },
   {
      "author_association" : "NONE",
      "body" : "No Marco, cosmic rays are very unlikely, and overheating is definitely not the case. The bug is persistent even if it occurs \"unpredictably\" (for now because we don't know the exact cause) and in lot of different hardware and OS configurations, and even when running on very reliable systems (like Azure and Amazon VMs). And I have not noted any hardware issue reported by the OS or any problem in the filesystem which is always \"clean\", and based on very reliable RAID stores with multiple layers of hardware and software checks. It looks very much like a race issue in Bitcoin Core implementation itself (or its dependancies like LevelDB), which is more likely to occur on very fast machines and with very fast Internet connections.\r\nAll I did to limit the rate of these errors was to voluntarily slowdown Bitcoin Core. And I've never detected any block corruption when I compare the regular snapshots of data I make with backups or across the different hosts that I've tried. They just fail at different time, but they all fail sometime.",
      "created_at" : "2022-08-11T16:29:25Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/25800#issuecomment-1212215679",
      "id" : 1212215679,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/25800",
      "node_id" : "IC_kwDOABII585IQPF_",
      "performed_via_github_app" : null,
      "reactions" : {
         "+1" : 0,
         "-1" : 0,
         "confused" : 0,
         "eyes" : 0,
         "heart" : 0,
         "hooray" : 0,
         "laugh" : 0,
         "rocket" : 0,
         "total_count" : 0,
         "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1212215679/reactions"
      },
      "updated_at" : "2022-08-11T16:33:13Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1212215679",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/1387035?v=4",
         "events_url" : "https://api.github.com/users/verdy-p/events{/privacy}",
         "followers_url" : "https://api.github.com/users/verdy-p/followers",
         "following_url" : "https://api.github.com/users/verdy-p/following{/other_user}",
         "gists_url" : "https://api.github.com/users/verdy-p/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/verdy-p",
         "id" : 1387035,
         "login" : "verdy-p",
         "node_id" : "MDQ6VXNlcjEzODcwMzU=",
         "organizations_url" : "https://api.github.com/users/verdy-p/orgs",
         "received_events_url" : "https://api.github.com/users/verdy-p/received_events",
         "repos_url" : "https://api.github.com/users/verdy-p/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/verdy-p/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/verdy-p/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/verdy-p"
      }
   },
   {
      "author_association" : "MEMBER",
      "body" : "Do you have exact steps to reproduce on Azure or Amazon? Please make sure to include exact and complete steps, including all settings that are changed on the OS layer or elsewhere.",
      "created_at" : "2022-08-11T16:42:52Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/25800#issuecomment-1212228301",
      "id" : 1212228301,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/25800",
      "node_id" : "IC_kwDOABII585IQSLN",
      "performed_via_github_app" : null,
      "reactions" : {
         "+1" : 0,
         "-1" : 0,
         "confused" : 0,
         "eyes" : 0,
         "heart" : 0,
         "hooray" : 0,
         "laugh" : 0,
         "rocket" : 0,
         "total_count" : 0,
         "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1212228301/reactions"
      },
      "updated_at" : "2022-08-11T16:42:52Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1212228301",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/6399679?v=4",
         "events_url" : "https://api.github.com/users/MarcoFalke/events{/privacy}",
         "followers_url" : "https://api.github.com/users/MarcoFalke/followers",
         "following_url" : "https://api.github.com/users/MarcoFalke/following{/other_user}",
         "gists_url" : "https://api.github.com/users/MarcoFalke/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/MarcoFalke",
         "id" : 6399679,
         "login" : "MarcoFalke",
         "node_id" : "MDQ6VXNlcjYzOTk2Nzk=",
         "organizations_url" : "https://api.github.com/users/MarcoFalke/orgs",
         "received_events_url" : "https://api.github.com/users/MarcoFalke/received_events",
         "repos_url" : "https://api.github.com/users/MarcoFalke/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/MarcoFalke/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/MarcoFalke/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/MarcoFalke"
      }
   },
   {
      "author_association" : "NONE",
      "body" : "The steps are just configure a standard VM with default settings. I chose the most common OSes with little configuration. I chose the standard binary releases. jkuste like anyone would do at home on their PC.\r\nI tried many different configs (since many months), none have successed. We see failures happening after about 2 hours, or sometimes just after less than 10 minutes. I can erase all the daa and restart, this just fails at different moments, but it never completes.\r\nIn fact I have no idea about why it works for many other people. But they don't tell us why. Most probably many other have tried and already abandoned rapidly since long.",
      "created_at" : "2022-08-11T17:06:25Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/25800#issuecomment-1212258006",
      "id" : 1212258006,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/25800",
      "node_id" : "IC_kwDOABII585IQZbW",
      "performed_via_github_app" : null,
      "reactions" : {
         "+1" : 0,
         "-1" : 0,
         "confused" : 0,
         "eyes" : 0,
         "heart" : 0,
         "hooray" : 0,
         "laugh" : 0,
         "rocket" : 0,
         "total_count" : 0,
         "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1212258006/reactions"
      },
      "updated_at" : "2022-08-11T17:07:22Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1212258006",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/1387035?v=4",
         "events_url" : "https://api.github.com/users/verdy-p/events{/privacy}",
         "followers_url" : "https://api.github.com/users/verdy-p/followers",
         "following_url" : "https://api.github.com/users/verdy-p/following{/other_user}",
         "gists_url" : "https://api.github.com/users/verdy-p/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/verdy-p",
         "id" : 1387035,
         "login" : "verdy-p",
         "node_id" : "MDQ6VXNlcjEzODcwMzU=",
         "organizations_url" : "https://api.github.com/users/verdy-p/orgs",
         "received_events_url" : "https://api.github.com/users/verdy-p/received_events",
         "repos_url" : "https://api.github.com/users/verdy-p/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/verdy-p/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/verdy-p/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/verdy-p"
      }
   },
   {
      "author_association" : "MEMBER",
      "body" : "Are you absolutely sure you are using \"default\" settings? You said the same thing in the last issue, and I wasn't able to reproduce with default settings: https://github.com/bitcoin/bitcoin/issues/25726#issuecomment-1203088286",
      "created_at" : "2022-08-11T17:24:40Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/25800#issuecomment-1212273740",
      "id" : 1212273740,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/25800",
      "node_id" : "IC_kwDOABII585IQdRM",
      "performed_via_github_app" : null,
      "reactions" : {
         "+1" : 0,
         "-1" : 0,
         "confused" : 0,
         "eyes" : 0,
         "heart" : 0,
         "hooray" : 0,
         "laugh" : 0,
         "rocket" : 0,
         "total_count" : 0,
         "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1212273740/reactions"
      },
      "updated_at" : "2022-08-11T17:24:40Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1212273740",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/6399679?v=4",
         "events_url" : "https://api.github.com/users/MarcoFalke/events{/privacy}",
         "followers_url" : "https://api.github.com/users/MarcoFalke/followers",
         "following_url" : "https://api.github.com/users/MarcoFalke/following{/other_user}",
         "gists_url" : "https://api.github.com/users/MarcoFalke/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/MarcoFalke",
         "id" : 6399679,
         "login" : "MarcoFalke",
         "node_id" : "MDQ6VXNlcjYzOTk2Nzk=",
         "organizations_url" : "https://api.github.com/users/MarcoFalke/orgs",
         "received_events_url" : "https://api.github.com/users/MarcoFalke/received_events",
         "repos_url" : "https://api.github.com/users/MarcoFalke/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/MarcoFalke/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/MarcoFalke/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/MarcoFalke"
      }
   },
   {
      "author_association" : "NONE",
      "body" : "I just run \"bitcoind\" with no options its logs in debug.log and on the console, unless I give the option to not no log anything on th console or in \"debug.log\" (this makes it run faster), or I use\r\n\r\n> $ bitcoin-cli debug '[]' '[\"all\"]'\r\n\r\nto disable new log outputs (it just logs the startup or shutdown and \" UpdateTip: new best=*\" messages, still at a very high rate.)",
      "created_at" : "2022-08-11T20:19:47Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/25800#issuecomment-1212455409",
      "id" : 1212455409,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/25800",
      "node_id" : "IC_kwDOABII585IRJnx",
      "performed_via_github_app" : null,
      "reactions" : {
         "+1" : 0,
         "-1" : 0,
         "confused" : 0,
         "eyes" : 0,
         "heart" : 0,
         "hooray" : 0,
         "laugh" : 0,
         "rocket" : 0,
         "total_count" : 0,
         "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1212455409/reactions"
      },
      "updated_at" : "2022-08-11T20:24:46Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1212455409",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/1387035?v=4",
         "events_url" : "https://api.github.com/users/verdy-p/events{/privacy}",
         "followers_url" : "https://api.github.com/users/verdy-p/followers",
         "following_url" : "https://api.github.com/users/verdy-p/following{/other_user}",
         "gists_url" : "https://api.github.com/users/verdy-p/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/verdy-p",
         "id" : 1387035,
         "login" : "verdy-p",
         "node_id" : "MDQ6VXNlcjEzODcwMzU=",
         "organizations_url" : "https://api.github.com/users/verdy-p/orgs",
         "received_events_url" : "https://api.github.com/users/verdy-p/received_events",
         "repos_url" : "https://api.github.com/users/verdy-p/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/verdy-p/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/verdy-p/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/verdy-p"
      }
   },
   {
      "author_association" : "NONE",
      "body" : "> > But may be there are other competing softwares that could work such as https://www.bitcoinabc.org/ (if they've detected such attack and are able to isolate and fix it)?\r\n> \r\n> That software is for a different currency, with different consensus rules. It will not synchronize with the Bitcoin network/chain/currency.\r\n\r\nWhy do I see them connected to the Bitcoin chain (according to their user agent string)? What are they doing there? They are just \"listening\" and not emitting any transaction? But frequently blocks are downloaded *from* them.",
      "created_at" : "2022-08-12T05:13:31Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/25800#issuecomment-1212736619",
      "id" : 1212736619,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/25800",
      "node_id" : "IC_kwDOABII585ISORr",
      "performed_via_github_app" : null,
      "reactions" : {
         "+1" : 0,
         "-1" : 0,
         "confused" : 0,
         "eyes" : 0,
         "heart" : 0,
         "hooray" : 0,
         "laugh" : 0,
         "rocket" : 0,
         "total_count" : 0,
         "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1212736619/reactions"
      },
      "updated_at" : "2022-08-12T05:13:31Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1212736619",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/1387035?v=4",
         "events_url" : "https://api.github.com/users/verdy-p/events{/privacy}",
         "followers_url" : "https://api.github.com/users/verdy-p/followers",
         "following_url" : "https://api.github.com/users/verdy-p/following{/other_user}",
         "gists_url" : "https://api.github.com/users/verdy-p/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/verdy-p",
         "id" : 1387035,
         "login" : "verdy-p",
         "node_id" : "MDQ6VXNlcjEzODcwMzU=",
         "organizations_url" : "https://api.github.com/users/verdy-p/orgs",
         "received_events_url" : "https://api.github.com/users/verdy-p/received_events",
         "repos_url" : "https://api.github.com/users/verdy-p/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/verdy-p/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/verdy-p/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/verdy-p"
      }
   }
]
