[
   {
      "author_association" : "MEMBER",
      "body" : "CI failure seems completely unrelated (`feature_asmap` failure on a `Addrman` log line figuring `3` instead of `2`). Here is the log trace, \"just in case\".\r\n<details>\r\n<p>\r\n<summary>Random `feature_asmap` failure logs</summary>\r\n\r\n```\r\n2021-09-23T14:53:38.217000Z TestFramework (INFO): Initializing test directory /tmp/cirrus-ci-build/ci/scratch/test_runner/test_runner_â¿_ð_20210923_145026/feature_asmap_26\r\n2021-09-23T14:53:39.000000Z TestFramework (INFO): Test bitcoind with no -asmap arg passed\r\n2021-09-23T14:53:39.442000Z TestFramework (INFO): Test bitcoind -asmap=<absolute path>\r\n2021-09-23T14:53:40.286000Z TestFramework (INFO): Test bitcoind -asmap=<relative path>\r\n2021-09-23T14:53:40.859000Z TestFramework (INFO): Test bitcoind -asmap (using default map file)\r\n2021-09-23T14:53:41.404000Z TestFramework (INFO): Test bitcoind -asmap= (using default map file)\r\n2021-09-23T14:53:42.007000Z TestFramework (INFO): Test bitcoind -asmap restart with addrman containing new and tried entries\r\n2021-09-23T14:55:03.894000Z TestFramework (ERROR): Assertion failed\r\nTraceback (most recent call last):\r\n  File \"/tmp/cirrus-ci-build/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/test/functional/test_framework/test_framework.py\", line 131, in main\r\n    self.run_test()\r\n  File \"/tmp/cirrus-ci-build/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/test/functional/feature_asmap.py\", line 124, in run_test\r\n    self.test_asmap_interaction_with_addrman_containing_entries()\r\n  File \"/tmp/cirrus-ci-build/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/test/functional/feature_asmap.py\", line 96, in test_asmap_interaction_with_addrman_containing_entries\r\n    self.node.getnodeaddresses()  # getnodeaddresses re-runs the addrman checks\r\n  File \"/usr/lib/python3.6/contextlib.py\", line 88, in __exit__\r\n    next(self.gen)\r\n  File \"/tmp/cirrus-ci-build/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/test/functional/test_framework/test_node.py\", line 400, in assert_debug_log\r\n    self._raise_assertion_error('Expected messages \"{}\" does not partially match log:\\n\\n{}\\n\\n'.format(str(expected_msgs), print_log))\r\n  File \"/tmp/cirrus-ci-build/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/test/functional/test_framework/test_node.py\", line 166, in _raise_assertion_error\r\n    raise AssertionError(self._node_msg(msg))\r\nAssertionError: [node 0] Expected messages \"['Addrman checks started: new 2, tried 2, total 4', 'Addrman checks completed successfully']\" does not partially match log:\r\n - 2021-09-23T14:53:43.886617Z [http] [httpserver.cpp:237] [http_request_cb] Received a POST request for / from 127.0.0.1:52652\r\n - 2021-09-23T14:53:43.886733Z [httpworker.3] [rpc/request.cpp:174] [parse] ThreadRPCServer method=getnodeaddresses user=__cookie__\r\n - 2021-09-23T14:53:43.886809Z [httpworker.3] [addrman.cpp:770] [ForceCheckAddrman] Addrman checks started: new 3, tried 1, total 4\r\n - 2021-09-23T14:53:43.886870Z [httpworker.3] [addrman.cpp:48] [GetTriedBucket] IP 101.0.0.0 mapped to AS1 belongs to tried bucket 113\r\n - 2021-09-23T14:53:43.886980Z [httpworker.3] [addrman.cpp:850] [ForceCheckAddrman] Addrman checks completed successfully\r\n - 2021-09-23T14:53:43.886991Z [httpworker.3] [addrman.cpp:770] [ForceCheckAddrman] Addrman checks started: new 3, tried 1, total 4\r\n - 2021-09-23T14:53:43.887016Z [httpworker.3] [addrman.cpp:48] [GetTriedBucket] IP 101.0.0.0 mapped to AS1 belongs to tried bucket 113\r\n - 2021-09-23T14:53:43.887102Z [httpworker.3] [addrman.cpp:850] [ForceCheckAddrman] Addrman checks completed successfully\r\n - 2021-09-23T14:54:28.662861Z [scheduler] [net.h:865] [StartExtraBlockRelayPeers] net: enabling extra block-relay-only peers\r\n - 2021-09-23T14:54:43.321822Z [scheduler] [random.cpp:523] [SeedPeriodic] Feeding 33048 bytes of dynamic environment data into RNG\r\n```\r\n</p>\r\n</details>",
      "created_at" : "2021-09-23T17:03:16Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/pull/23074#issuecomment-925995340",
      "id" : 925995340,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/23074",
      "node_id" : "IC_kwDOABII5843MZFM",
      "performed_via_github_app" : null,
      "updated_at" : "2021-09-23T17:03:16Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/925995340",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/22457751?v=4",
         "events_url" : "https://api.github.com/users/darosior/events{/privacy}",
         "followers_url" : "https://api.github.com/users/darosior/followers",
         "following_url" : "https://api.github.com/users/darosior/following{/other_user}",
         "gists_url" : "https://api.github.com/users/darosior/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/darosior",
         "id" : 22457751,
         "login" : "darosior",
         "node_id" : "MDQ6VXNlcjIyNDU3NzUx",
         "organizations_url" : "https://api.github.com/users/darosior/orgs",
         "received_events_url" : "https://api.github.com/users/darosior/received_events",
         "repos_url" : "https://api.github.com/users/darosior/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/darosior/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/darosior/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/darosior"
      }
   }
]
