[
   {
      "author_association" : "CONTRIBUTOR",
      "body" : "I killed the hung process, started it again, let it get to within 4 blocks of the point it crashes, shut it down cleanly, then restarted it again. It crashed again, but got a few blocks further this time, getting to `height=485586` as opposed to 485584 last time. Also this time the error dialog showed the error message, and I was able to click it to exit bitcoin-qt cleanly.\r\n\r\n![screenshot_2017-09-16_13-08-09](https://user-images.githubusercontent.com/573356/30515629-bdf7397a-9ae0-11e7-9998-c2f7161f9b3c.png)\r\n",
      "created_at" : "2017-09-16T20:13:34Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/11355#issuecomment-329992182",
      "id" : 329992182,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/11355",
      "updated_at" : "2017-09-16T20:13:34Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/329992182",
      "user" : {
         "avatar_url" : "https://avatars3.githubusercontent.com/u/573356?v=4",
         "events_url" : "https://api.github.com/users/dooglus/events{/privacy}",
         "followers_url" : "https://api.github.com/users/dooglus/followers",
         "following_url" : "https://api.github.com/users/dooglus/following{/other_user}",
         "gists_url" : "https://api.github.com/users/dooglus/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/dooglus",
         "id" : 573356,
         "login" : "dooglus",
         "organizations_url" : "https://api.github.com/users/dooglus/orgs",
         "received_events_url" : "https://api.github.com/users/dooglus/received_events",
         "repos_url" : "https://api.github.com/users/dooglus/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/dooglus/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/dooglus/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/dooglus"
      }
   },
   {
      "author_association" : "CONTRIBUTOR",
      "body" : "I set a breakpoint:\r\n\r\n    (gdb) br leveldb::Status::Corruption\r\n    Breakpoint 3 at 0x555555acd1a2: leveldb::Status::Corruption. (9 locations)\r\n\r\nIt was hit:\r\n\r\n    Thread 20 \"bitcoin-msghand\" hit Breakpoint 4, leveldb::ReadBlock (file=<optimized out>, options=..., handle=..., result=0x7fffa6702378)\r\n        at leveldb/table/format.cc:95\r\n    95\t      s = Status::Corruption(\"block checksum mismatch\");\r\n    (gdb) where\r\n    #0  leveldb::ReadBlock (file=<optimized out>, options=..., handle=..., result=0x7fffa6702378) at leveldb/table/format.cc:95\r\n    #1  0x0000555555acd9f9 in leveldb::Table::BlockReader (arg=0x7fff8c176830, options=..., index_value=...) at leveldb/table/table.cc:189\r\n    #2  0x0000555555acde21 in leveldb::Table::InternalGet (this=0x7fff8c176830, options=..., k=..., arg=<optimized out>, saver=<optimized out>)\r\n        at leveldb/table/table.cc:241\r\n    #3  0x0000555555abf37c in leveldb::TableCache::Get (this=0x7fffb7560680, options=..., file_number=<optimized out>, file_size=<optimized out>, k=..., arg=0x140, \r\n        saver=0x7) at leveldb/db/table_cache.cc:115\r\n    #4  0x0000555555ac237a in leveldb::Version::Get (this=<optimized out>, options=..., k=..., value=<optimized out>, stats=<optimized out>)\r\n        at leveldb/db/version_set.cc:408\r\n    #5  0x0000555555ab6bf3 in leveldb::DBImpl::Get (this=0x7fffb7560940, options=..., key=..., value=0x7fffa67029e0) at leveldb/db/db_impl.cc:1141\r\n    #6  0x000055555588f609 in CDBWrapper::Read<(anonymous namespace)::CoinEntry, Coin> (this=<optimized out>, key=..., value=...) at ./dbwrapper.h:233\r\n    #7  CCoinsViewDB::GetCoin (this=0x7fffb755f2e0, outpoint=..., coin=...) at txdb.cpp:62\r\n    #8  0x0000555555a50107 in CCoinsViewBacked::GetCoin (this=<optimized out>, outpoint=..., coin=...) at coins.cpp:26\r\n    #9  0x000055555575c077 in CCoinsViewErrorCatcher::GetCoin (this=0x7fff8c000000, outpoint=..., coin=...) at init.cpp:141\r\n    #10 0x0000555555a50462 in CCoinsViewCache::FetchCoin (this=0x7fffb75641b0, outpoint=...) at coins.cpp:48\r\n    #11 0x0000555555a50549 in CCoinsViewCache::GetCoin (this=0x7fff8c000000, outpoint=..., coin=...) at coins.cpp:61\r\n    #12 0x0000555555a50462 in CCoinsViewCache::FetchCoin (this=0x7fffa6704440, outpoint=...) at coins.cpp:48\r\n    #13 0x0000555555a50b03 in CCoinsViewCache::HaveCoin (this=0x7fff8c000000, outpoint=...) at coins.cpp:129\r\n    #14 0x0000555555a51254 in CCoinsViewCache::HaveInputs (this=<optimized out>, tx=...) at coins.cpp:240\r\n    #15 0x00005555558d3210 in ConnectBlock (block=..., state=..., pindex=<optimized out>, view=..., chainparams=..., fJustCheck=<optimized out>) at validation.cpp:1763\r\n    #16 0x00005555558c676e in ConnectTip (state=..., chainparams=..., pindexNew=<optimized out>, connectTrace=..., disconnectpool=..., pblock=...)\r\n        at validation.cpp:2209\r\n    #17 ActivateBestChainStep (state=..., chainparams=..., pindexMostWork=<optimized out>, pblock=..., fInvalidFound=<optimized out>, connectTrace=...)\r\n        at validation.cpp:2354\r\n    #18 0x00005555558c5ad4 in ActivateBestChain (state=..., chainparams=..., pblock=...) at validation.cpp:2454\r\n    #19 0x00005555558cff58 in ProcessNewBlock (chainparams=..., pblock=warning: RTTI symbol not found for class 'std::_Sp_counted_ptr_inplace<CBlock, std::allocator<CBlock>, (__gnu_cxx::_Lock_policy)2>'\r\n    warning: RTTI symbol not found for class 'std::_Sp_counted_ptr_inplace<CBlock, std::allocator<CBlock>, (__gnu_cxx::_Lock_policy)2>'\r\n    std::shared_ptr (count 6, weak 0) 0x7fff8cd638e0, fForceProcessing=<optimized out>, \r\n        fNewBlock=0x7fffa6704aaf) at validation.cpp:3199\r\n    #20 0x00005555557beabf in ProcessMessage (pfrom=<optimized out>, strCommand=..., vRecv=..., nTimeReceived=<optimized out>, chainparams=..., \r\n        connman=<optimized out>, interruptMsgProc=...) at net_processing.cpp:2391\r\n    #21 0x00005555557adf12 in PeerLogicValidation::ProcessMessages (this=0x7fffc8410440, pfrom=0x7fff980008c0, interruptMsgProc=...) at net_processing.cpp:2718\r\n    #22 0x00005555557da037 in non-virtual thunk to PeerLogicValidation::ProcessMessages(CNode*, std::atomic<bool>&) () at net_processing.cpp:2643\r\n    #23 0x000055555578967b in CConnman::ThreadMessageHandler (this=<optimized out>) at net.cpp:1995\r\n    #24 0x00005555557a44ba in std::__invoke_impl<void, void (CConnman::* const&)(), CConnman*&> (__f=<optimized out>, __t=<optimized out>)\r\n        at /usr/bin/../lib/gcc/x86_64-linux-gnu/6.3.0/../../../../include/c++/6.3.0/functional:227\r\n    #25 std::__invoke<void (CConnman::* const&)(), CConnman*&> (__fn=<optimized out>, __args=<optimized out>)\r\n        at /usr/bin/../lib/gcc/x86_64-linux-gnu/6.3.0/../../../../include/c++/6.3.0/functional:250\r\n    #26 std::_Mem_fn_base<void (CConnman::*)(), true>::operator()<CConnman*&> (this=<optimized out>, __args=<optimized out>)\r\n        at /usr/bin/../lib/gcc/x86_64-linux-gnu/6.3.0/../../../../include/c++/6.3.0/functional:604\r\n    #27 std::_Bind<std::_Mem_fn<void (CConnman::*)()> (CConnman*)>::__call<void, , 0ul>(std::tuple<>&&, std::_Index_tuple<0ul>) (this=<optimized out>, \r\n        __args=<optimized out>) at /usr/bin/../lib/gcc/x86_64-linux-gnu/6.3.0/../../../../include/c++/6.3.0/functional:933\r\n    #28 std::_Bind<std::_Mem_fn<void (CConnman::*)()> (CConnman*)>::operator()<, void>() (this=<optimized out>)\r\n        at /usr/bin/../lib/gcc/x86_64-linux-gnu/6.3.0/../../../../include/c++/6.3.0/functional:991\r\n    #29 std::_Function_handler<void (), std::_Bind<std::_Mem_fn<void (CConnman::*)()> (CConnman*)> >::_M_invoke(std::_Any_data const&) (__functor=...)\r\n        at /usr/bin/../lib/gcc/x86_64-linux-gnu/6.3.0/../../../../include/c++/6.3.0/functional:1731\r\n    #30 0x0000555555758e3d in std::function<void ()>::operator()() const (this=0x7fffa670bd00)\r\n        at /usr/bin/../lib/gcc/x86_64-linux-gnu/6.3.0/../../../../include/c++/6.3.0/functional:2127\r\n    #31 TraceThread<std::function<void ()> >(char const*, std::function<void ()>) (name=<optimized out>, func=...) at ./util.h:309\r\n    #32 0x00005555557a467d in std::_Bind_simple<void (*(char const*, std::function<void ()>))(char const*, std::function<void ()>)>::_M_invoke<0ul, 1ul>(std::_Index_tuple<0ul, 1ul>) (this=<optimized out>) at /usr/bin/../lib/gcc/x86_64-linux-gnu/6.3.0/../../../../include/c++/6.3.0/functional:1390\r\n    #33 std::_Bind_simple<void (*(char const*, std::function<void ()>))(char const*, std::function<void ()>)>::operator()() (this=<optimized out>)\r\n        at /usr/bin/../lib/gcc/x86_64-linux-gnu/6.3.0/../../../../include/c++/6.3.0/functional:1380\r\n    #34 std::thread::_State_impl<std::_Bind_simple<void (*(char const*, std::function<void ()>))(char const*, std::function<void ()>)> >::_M_run() (\r\n        this=<optimized out>) at /usr/bin/../lib/gcc/x86_64-linux-gnu/6.3.0/../../../../include/c++/6.3.0/thread:197\r\n    #35 0x00007ffff452ce6f in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6\r\n    #36 0x00007ffff56f9494 in start_thread (arg=0x7fffa670c700) at pthread_create.c:333\r\n    #37 0x00007ffff3ca1aff in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:97\r\n    (gdb) \r\n\r\nSo it does look like my chainstate db is corrupted again doesn't it? I wonder if there's something wrong with the code that's causing this corruption. Should the db be able to get corrupted from random crashes?",
      "created_at" : "2017-09-16T20:22:37Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/11355#issuecomment-329992636",
      "id" : 329992636,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/11355",
      "updated_at" : "2017-09-16T20:22:37Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/329992636",
      "user" : {
         "avatar_url" : "https://avatars3.githubusercontent.com/u/573356?v=4",
         "events_url" : "https://api.github.com/users/dooglus/events{/privacy}",
         "followers_url" : "https://api.github.com/users/dooglus/followers",
         "following_url" : "https://api.github.com/users/dooglus/following{/other_user}",
         "gists_url" : "https://api.github.com/users/dooglus/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/dooglus",
         "id" : 573356,
         "login" : "dooglus",
         "organizations_url" : "https://api.github.com/users/dooglus/orgs",
         "received_events_url" : "https://api.github.com/users/dooglus/received_events",
         "repos_url" : "https://api.github.com/users/dooglus/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/dooglus/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/dooglus/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/dooglus"
      }
   },
   {
      "author_association" : "CONTRIBUTOR",
      "body" : "I have two separate Bitcoin data directories. One is a full node (and that's the one which is failing) and the other is pruned (`prune=600`).\r\n\r\nIs it safe to copy the `chainstate` folder from the pruned datadir into the full node's datadir to fix this corruption issue? Or do I need to run the >24h chainstate reindex thing again?\r\n\r\nEdit: it appears to have worked. I did this:\r\n\r\n* made a bootstrap.dat file that I used to sync the pruned node to the point where it returns the same for 'getblockcount' as the corrupted full node gives\r\n* stopped both nodes\r\n* deleted the corrupted chainstate folder\r\n* copied the pruned node's chainstate folder into the full node\r\n\r\nThen when I started the full node, it was able to continue syncing past the point it was previously failing.\r\n\r\nSo that seems like a good cheap way of recovering from chainstate db corruption, if you don't mind wasting the extra ~4GB of space for an extra pruned node. It can sync from the full node, so needn't add to your bandwidth requirements.",
      "created_at" : "2017-09-16T20:31:07Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/11355#issuecomment-329993047",
      "id" : 329993047,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/11355",
      "updated_at" : "2017-09-16T22:19:56Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/329993047",
      "user" : {
         "avatar_url" : "https://avatars3.githubusercontent.com/u/573356?v=4",
         "events_url" : "https://api.github.com/users/dooglus/events{/privacy}",
         "followers_url" : "https://api.github.com/users/dooglus/followers",
         "following_url" : "https://api.github.com/users/dooglus/following{/other_user}",
         "gists_url" : "https://api.github.com/users/dooglus/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/dooglus",
         "id" : 573356,
         "login" : "dooglus",
         "organizations_url" : "https://api.github.com/users/dooglus/orgs",
         "received_events_url" : "https://api.github.com/users/dooglus/received_events",
         "repos_url" : "https://api.github.com/users/dooglus/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/dooglus/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/dooglus/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/dooglus"
      }
   },
   {
      "author_association" : "NONE",
      "body" : "I experienced the same issue with my pruned node on a low end OSX computer on block #470915.\r\n\r\nI shut down Bitcoin QT and started it again >>> problem remained.\r\nI shut down my computer, restarted it, started Bitcoin QT again >>> problem has resolved itself.\r\n\r\nMy debug log:\r\n2017-09-18 04:46:34 UpdateTip: new best=000000000000000000051d8e3a33e4da2fdf008d35cf161382a5639e66b57c4a height=470914 version=0x20000000 log2_work=86.584992 tx=231183711 date='2017-06-12 06:50:28' progress=0.903516 cache=69.4MiB(516833txo)\r\n2017-09-18 04:46:34 UpdateTip: new best=00000000000000000004fcac1e558d2d6031d73b14db5cf67916f712081912e7 height=470915 version=0x20000002 log2_work=86.585028 tx=231184966 date='2017-06-12 06:50:36' progress=0.903521 cache=69.9MiB(521248txo)\r\n2017-09-18 04:46:35 LevelDB read failure: Corruption: block checksum mismatch\r\n2017-09-18 04:46:35 Corruption: block checksum mismatch\r\n2017-09-18 04:47:18 version handshake timeout from 5\r\n2017-09-18 04:47:19 version handshake timeout from 6",
      "created_at" : "2017-09-18T16:37:15Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/11355#issuecomment-330280417",
      "id" : 330280417,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/11355",
      "updated_at" : "2017-09-18T16:37:15Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/330280417",
      "user" : {
         "avatar_url" : "https://avatars3.githubusercontent.com/u/9769277?v=4",
         "events_url" : "https://api.github.com/users/jlegoupil/events{/privacy}",
         "followers_url" : "https://api.github.com/users/jlegoupil/followers",
         "following_url" : "https://api.github.com/users/jlegoupil/following{/other_user}",
         "gists_url" : "https://api.github.com/users/jlegoupil/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/jlegoupil",
         "id" : 9769277,
         "login" : "jlegoupil",
         "organizations_url" : "https://api.github.com/users/jlegoupil/orgs",
         "received_events_url" : "https://api.github.com/users/jlegoupil/received_events",
         "repos_url" : "https://api.github.com/users/jlegoupil/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/jlegoupil/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/jlegoupil/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/jlegoupil"
      }
   },
   {
      "author_association" : "CONTRIBUTOR",
      "body" : "@jlegoupil what version of Bitcoin Core were you using?\r\n\r\nI don't see why restarting your OS would help. That's strange.",
      "created_at" : "2017-09-18T16:51:31Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/11355#issuecomment-330284336",
      "id" : 330284336,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/11355",
      "updated_at" : "2017-09-18T16:51:31Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/330284336",
      "user" : {
         "avatar_url" : "https://avatars3.githubusercontent.com/u/573356?v=4",
         "events_url" : "https://api.github.com/users/dooglus/events{/privacy}",
         "followers_url" : "https://api.github.com/users/dooglus/followers",
         "following_url" : "https://api.github.com/users/dooglus/following{/other_user}",
         "gists_url" : "https://api.github.com/users/dooglus/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/dooglus",
         "id" : 573356,
         "login" : "dooglus",
         "organizations_url" : "https://api.github.com/users/dooglus/orgs",
         "received_events_url" : "https://api.github.com/users/dooglus/received_events",
         "repos_url" : "https://api.github.com/users/dooglus/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/dooglus/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/dooglus/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/dooglus"
      }
   },
   {
      "author_association" : "NONE",
      "body" : "I'm using Bitcoin Core 0.15.0.0",
      "created_at" : "2017-09-18T17:02:40Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/11355#issuecomment-330287557",
      "id" : 330287557,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/11355",
      "updated_at" : "2017-09-18T17:02:58Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/330287557",
      "user" : {
         "avatar_url" : "https://avatars3.githubusercontent.com/u/9769277?v=4",
         "events_url" : "https://api.github.com/users/jlegoupil/events{/privacy}",
         "followers_url" : "https://api.github.com/users/jlegoupil/followers",
         "following_url" : "https://api.github.com/users/jlegoupil/following{/other_user}",
         "gists_url" : "https://api.github.com/users/jlegoupil/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/jlegoupil",
         "id" : 9769277,
         "login" : "jlegoupil",
         "organizations_url" : "https://api.github.com/users/jlegoupil/orgs",
         "received_events_url" : "https://api.github.com/users/jlegoupil/received_events",
         "repos_url" : "https://api.github.com/users/jlegoupil/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/jlegoupil/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/jlegoupil/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/jlegoupil"
      }
   },
   {
      "author_association" : "CONTRIBUTOR",
      "body" : "It happened again to me, this time on shutdown:\r\n\r\n    2017-09-23 20:54:21 connect() to 59.127.26.8:8333 failed: Network is unreachable (101)\r\n    2017-09-23 20:54:21 connect() to 220.253.70.199:8333 failed: Network is unreachable (101)\r\n    2017-09-23 20:54:22 connect() to 77.181.226.122:8333 failed: Network is unreachable (101)\r\n    2017-09-23 20:54:22 connect() to 35.185.131.115:8333 failed: Network is unreachable (101)\r\n    2017-09-23 20:54:23 connect() to [2001:0:9d38:6ab8:3c62:f87e:95d8:bcd2]:8333 failed: Network is unreachable (101)\r\n    2017-09-23 20:54:23 connect() to 139.59.149.67:8333 failed: Network is unreachable (101)\r\n    2017-09-23 20:54:24 connect() to 188.195.24.170:8333 failed: Network is unreachable (101)\r\n    2017-09-23 20:54:24 connect() to 24.90.192.28:8333 failed: Network is unreachable (101)\r\n    2017-09-23 20:54:25 connect() to [2001:0:9d38:78cf:20d3:3c09:a9d2:703a]:8333 failed: Network is unreachable (101)\r\n    2017-09-23 20:54:25 addcon thread exit\r\n    2017-09-23 20:54:25 scheduler thread interrupt\r\n    2017-09-23 20:54:25 opencon thread exit\r\n    2017-09-23 20:54:25 Shutdown: In progress...\r\n    2017-09-23 20:54:25 net thread exit\r\n    2017-09-23 20:54:25 msghand thread exit\r\n    2017-09-23 20:54:25 Dumped mempool: 0.005588s to copy, 0.126193s to dump\r\n    2017-09-23 20:54:25 Corruption: block checksum mismatch\r\n    2017-09-23 20:54:25 *** System error while flushing: Database corrupted\r\n    2017-09-23 20:54:33 Corruption: block checksum mismatch\r\n    2017-09-23 20:54:33 *** System error while flushing: Database corrupted\r\n    2017-09-23 20:54:34 GUI: QXcbConnection: XCB error: 3 (BadWindow), sequence: 7465, resource id: 11515671, major code: 40 (TranslateCoords), minor code: 0\r\n    2017-09-23 20:54:34 Shutdown: done\r\n\r\nI was offline at the time, which explains all the \"Network is unreachable\" errors. Since the last time I fixed the chainstate db I never had Bitcoin crash, but I did have the laptop fail to resume from a suspend state once and had to do a cold reset. I guess that could have corrupted the db, but this really seems to be so much more common in 0.15 than it was before. This is the 3rd chainstate db corruption I've had with 0.15 compared to 6 years of corruption-free operation before 0.15.",
      "created_at" : "2017-09-23T20:57:57Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/11355#issuecomment-331669466",
      "id" : 331669466,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/11355",
      "updated_at" : "2017-09-23T20:57:57Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/331669466",
      "user" : {
         "avatar_url" : "https://avatars3.githubusercontent.com/u/573356?v=4",
         "events_url" : "https://api.github.com/users/dooglus/events{/privacy}",
         "followers_url" : "https://api.github.com/users/dooglus/followers",
         "following_url" : "https://api.github.com/users/dooglus/following{/other_user}",
         "gists_url" : "https://api.github.com/users/dooglus/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/dooglus",
         "id" : 573356,
         "login" : "dooglus",
         "organizations_url" : "https://api.github.com/users/dooglus/orgs",
         "received_events_url" : "https://api.github.com/users/dooglus/received_events",
         "repos_url" : "https://api.github.com/users/dooglus/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/dooglus/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/dooglus/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/dooglus"
      }
   },
   {
      "author_association" : "CONTRIBUTOR",
      "body" : "I'm still getting this chainstate database corruption fairly regularly.\r\n\r\nSince my last comment here it has happened three more times, on Oct 11th, 12th, and 22nd.\r\n\r\nThis seems like a serious issue to me, because once the chainstate database is corrupted it requires a full blockchain rescan to repair it. For a pruned node that means starting the IBD from scratch, and will likely lead to lots of full nodes going offline due to inertia.",
      "created_at" : "2017-10-22T17:59:17Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/11355#issuecomment-338496500",
      "id" : 338496500,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/11355",
      "updated_at" : "2017-10-22T17:59:17Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/338496500",
      "user" : {
         "avatar_url" : "https://avatars3.githubusercontent.com/u/573356?v=4",
         "events_url" : "https://api.github.com/users/dooglus/events{/privacy}",
         "followers_url" : "https://api.github.com/users/dooglus/followers",
         "following_url" : "https://api.github.com/users/dooglus/following{/other_user}",
         "gists_url" : "https://api.github.com/users/dooglus/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/dooglus",
         "id" : 573356,
         "login" : "dooglus",
         "organizations_url" : "https://api.github.com/users/dooglus/orgs",
         "received_events_url" : "https://api.github.com/users/dooglus/received_events",
         "repos_url" : "https://api.github.com/users/dooglus/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/dooglus/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/dooglus/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/dooglus"
      }
   },
   {
      "author_association" : "CONTRIBUTOR",
      "body" : "One thing occurs to me. If I leave my laptop unattended, the screen locks after 5 minutes. It used to be that when I unlocked the screen any browser tabs I had open would have been updating behind the scenes. But for the last couple of months I've noticed that having the screen locked seems to freeze things. I unlock the screen, and the price charts haven't updated since I left and such like.\r\n\r\nI don't know what would cause that, but I'm wondering if it could also be causing the chainstate corruption I'm seeing if I leave bitcoin-qt running while the screen is locked.\r\n\r\nJust a thought.",
      "created_at" : "2017-10-22T18:15:19Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/11355#issuecomment-338497609",
      "id" : 338497609,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/11355",
      "updated_at" : "2017-10-22T18:15:19Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/338497609",
      "user" : {
         "avatar_url" : "https://avatars3.githubusercontent.com/u/573356?v=4",
         "events_url" : "https://api.github.com/users/dooglus/events{/privacy}",
         "followers_url" : "https://api.github.com/users/dooglus/followers",
         "following_url" : "https://api.github.com/users/dooglus/following{/other_user}",
         "gists_url" : "https://api.github.com/users/dooglus/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/dooglus",
         "id" : 573356,
         "login" : "dooglus",
         "organizations_url" : "https://api.github.com/users/dooglus/orgs",
         "received_events_url" : "https://api.github.com/users/dooglus/received_events",
         "repos_url" : "https://api.github.com/users/dooglus/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/dooglus/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/dooglus/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/dooglus"
      }
   },
   {
      "author_association" : "CONTRIBUTOR",
      "body" : "My chainstate database was corrupted again last night when I tried to close bitcoin-qt. From the debug.log:\r\n\r\n    2017-10-25 23:38:25 opencon thread exit\r\n    2017-10-25 23:38:25 addcon thread exit\r\n    2017-10-25 23:38:25 net thread exit\r\n    2017-10-25 23:38:25 msghand thread exit\r\n    2017-10-25 23:38:25 scheduler thread interrupt\r\n    2017-10-25 23:38:25 Shutdown: In progress...\r\n    2017-10-25 23:38:26 Dumped mempool: 0.001688s to copy, 0.191935s to dump\r\n    2017-10-25 23:38:27 Corruption: block checksum mismatch\r\n    2017-10-25 23:38:27 *** System error while flushing: Database corrupted\r\n    2017-10-25 23:38:31 Corruption: block checksum mismatch\r\n    2017-10-25 23:38:31 *** System error while flushing: Database corrupted\r\n    2017-10-25 23:38:32 Shutdown: done\r\n\r\nEach time it has happened recently, I have synced up my pruned node to the same block that the corrupted node is at, renamed the corrupted node's chainstate directory, then copied the pruned node's chainstate directory into the corrupted node's .bitcoin directory. That has left me with a bunch of corrupted chainstate directories:\r\n\r\n    ~/.bitcoin$ du -m chain*\r\n    2812\tchainstate\r\n    2757\tchainstate.bad\r\n    2779\tchainstate.bad2\r\n    2800\tchainstate.bad3\r\n    2837\tchainstate.bad4\r\n    2842\tchainstate.bad5\r\n    ~/.bitcoin$ ls -ld chainstate*\r\n    drwx------ 2 chris chris 61440 Oct 26 08:34 chainstate\r\n    drwx------ 2 chris chris 69632 Sep 16 14:50 chainstate.bad\r\n    drwx------ 2 chris chris 61440 Oct 11 07:29 chainstate.bad2\r\n    drwx------ 2 chris chris 65536 Oct 12 22:10 chainstate.bad3\r\n    drwx------ 2 chris chris 61440 Oct 22 09:39 chainstate.bad4\r\n    drwx------ 2 chris chris 65536 Oct 26 00:19 chainstate.bad5\r\n\r\nI can make these available if that would be helpful (and if it is safe to do so).",
      "created_at" : "2017-10-26T15:41:48Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/11355#issuecomment-339708547",
      "id" : 339708547,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/11355",
      "updated_at" : "2017-10-26T15:41:48Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/339708547",
      "user" : {
         "avatar_url" : "https://avatars3.githubusercontent.com/u/573356?v=4",
         "events_url" : "https://api.github.com/users/dooglus/events{/privacy}",
         "followers_url" : "https://api.github.com/users/dooglus/followers",
         "following_url" : "https://api.github.com/users/dooglus/following{/other_user}",
         "gists_url" : "https://api.github.com/users/dooglus/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/dooglus",
         "id" : 573356,
         "login" : "dooglus",
         "organizations_url" : "https://api.github.com/users/dooglus/orgs",
         "received_events_url" : "https://api.github.com/users/dooglus/received_events",
         "repos_url" : "https://api.github.com/users/dooglus/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/dooglus/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/dooglus/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/dooglus"
      }
   },
   {
      "author_association" : "CONTRIBUTOR",
      "body" : "We should change the order of the log print & blocking message box calls so the corruption errors are printed in the log if the message box handler hangs:\r\n\r\n```diff\r\n--- a/src/init.cpp\r\n+++ b/src/init.cpp\r\n@@ -140,8 +140,8 @@ public:\r\n         try {\r\n             return CCoinsViewBacked::GetCoin(outpoint, coin);\r\n         } catch(const std::runtime_error& e) {\r\n-            uiInterface.ThreadSafeMessageBox(_(\"Error reading from database, shutting down.\"), \"\", CClientUIInterface::MSG_ERROR);\r\n             LogPrintf(\"Error reading from database: %s\\n\", e.what());\r\n+            uiInterface.ThreadSafeMessageBox(_(\"Error reading from database, shutting down.\"), \"\", CClientUIInterface::MSG_ERROR);\r\n             // Starting the shutdown sequence and returning false to the caller would be\r\n             // interpreted as 'entry not found' (as opposed to unable to read data), and\r\n             // could lead to invalid interpretation. Just exit immediately, as we can't\r\n```\r\n\r\nEDIT: Actually, it doesn't matter very much, since the full leveldb error is logged right before the exception is thrown: https://github.com/bitcoin/bitcoin/blob/50fae68d416b4b8ec4ca192923dfd5ae9ea42773/src/dbwrapper.cpp#L203",
      "created_at" : "2017-10-26T16:26:31Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/11355#issuecomment-339722095",
      "id" : 339722095,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/11355",
      "updated_at" : "2017-10-26T17:29:53Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/339722095",
      "user" : {
         "avatar_url" : "https://avatars2.githubusercontent.com/u/7133040?v=4",
         "events_url" : "https://api.github.com/users/ryanofsky/events{/privacy}",
         "followers_url" : "https://api.github.com/users/ryanofsky/followers",
         "following_url" : "https://api.github.com/users/ryanofsky/following{/other_user}",
         "gists_url" : "https://api.github.com/users/ryanofsky/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/ryanofsky",
         "id" : 7133040,
         "login" : "ryanofsky",
         "organizations_url" : "https://api.github.com/users/ryanofsky/orgs",
         "received_events_url" : "https://api.github.com/users/ryanofsky/received_events",
         "repos_url" : "https://api.github.com/users/ryanofsky/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/ryanofsky/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/ryanofsky/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/ryanofsky"
      }
   },
   {
      "author_association" : "CONTRIBUTOR",
      "body" : "I only saw the message box hang once. It happened the first time the database was corrupted, and never since.",
      "created_at" : "2017-10-26T16:29:26Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/11355#issuecomment-339722984",
      "id" : 339722984,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/11355",
      "updated_at" : "2017-10-26T16:29:26Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/339722984",
      "user" : {
         "avatar_url" : "https://avatars3.githubusercontent.com/u/573356?v=4",
         "events_url" : "https://api.github.com/users/dooglus/events{/privacy}",
         "followers_url" : "https://api.github.com/users/dooglus/followers",
         "following_url" : "https://api.github.com/users/dooglus/following{/other_user}",
         "gists_url" : "https://api.github.com/users/dooglus/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/dooglus",
         "id" : 573356,
         "login" : "dooglus",
         "organizations_url" : "https://api.github.com/users/dooglus/orgs",
         "received_events_url" : "https://api.github.com/users/dooglus/received_events",
         "repos_url" : "https://api.github.com/users/dooglus/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/dooglus/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/dooglus/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/dooglus"
      }
   },
   {
      "author_association" : "MEMBER",
      "body" : ">  seems to be so much more common in 0.15 than it was before\r\n\r\nSo this was also happening before?\r\n\r\nA checksum error is a really really cut and dry condition: The system reads a record off the disk and the CRC32 didn't match.  We have never, so far, had a bug in the software which turned out to cause these errors: the cause has always been disk corruption due to a failing disk, faulty ram, or an overheating cpu. The latter of which is especially implicated in laptops (and other small systems) since most brands really just cannot handle being run at full intensity.  If prior versions did it as well and 0.15 is more frequent about it, it could just be because 0.15 hits the machine more intensely.\r\n\r\nBut it would be good to eliminate what other causes we can.. What exact cpu model and compiler version are you using?  Have you run Memtest86 on this system?",
      "created_at" : "2017-10-26T16:37:57Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/11355#issuecomment-339725394",
      "id" : 339725394,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/11355",
      "updated_at" : "2017-10-26T21:00:51Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/339725394",
      "user" : {
         "avatar_url" : "https://avatars1.githubusercontent.com/u/858454?v=4",
         "events_url" : "https://api.github.com/users/gmaxwell/events{/privacy}",
         "followers_url" : "https://api.github.com/users/gmaxwell/followers",
         "following_url" : "https://api.github.com/users/gmaxwell/following{/other_user}",
         "gists_url" : "https://api.github.com/users/gmaxwell/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/gmaxwell",
         "id" : 858454,
         "login" : "gmaxwell",
         "organizations_url" : "https://api.github.com/users/gmaxwell/orgs",
         "received_events_url" : "https://api.github.com/users/gmaxwell/received_events",
         "repos_url" : "https://api.github.com/users/gmaxwell/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/gmaxwell/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/gmaxwell/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/gmaxwell"
      }
   },
   {
      "author_association" : "CONTRIBUTOR",
      "body" : "Might be worth trying to store your chainstate on a zfs or btrfs partition to see if any corruption errors can be detected at the filesystem level. COW snapshots could also help you recover more quickly if there is corruption above the filesystem level.",
      "created_at" : "2017-10-26T16:54:32Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/11355#issuecomment-339730194",
      "id" : 339730194,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/11355",
      "updated_at" : "2017-10-26T16:54:32Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/339730194",
      "user" : {
         "avatar_url" : "https://avatars2.githubusercontent.com/u/7133040?v=4",
         "events_url" : "https://api.github.com/users/ryanofsky/events{/privacy}",
         "followers_url" : "https://api.github.com/users/ryanofsky/followers",
         "following_url" : "https://api.github.com/users/ryanofsky/following{/other_user}",
         "gists_url" : "https://api.github.com/users/ryanofsky/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/ryanofsky",
         "id" : 7133040,
         "login" : "ryanofsky",
         "organizations_url" : "https://api.github.com/users/ryanofsky/orgs",
         "received_events_url" : "https://api.github.com/users/ryanofsky/received_events",
         "repos_url" : "https://api.github.com/users/ryanofsky/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/ryanofsky/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/ryanofsky/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/ryanofsky"
      }
   },
   {
      "author_association" : "CONTRIBUTOR",
      "body" : "> So this was also happening before?\r\n\r\nI have had to run a full reindex maybe twice before 0.15, but both times were after I had had to do a cold reboot of my laptop while Core was running. I wasn't surprised that doing a cold reboot would cause problems.\r\n\r\nSince running 0.15 the chainstate database has become corrupted 7 times in 6 weeks. Most if not all of these happened without any cold restart happening.\r\n\r\n> the cause has always been disk corruption due to a failing disk, faulty ram, or an overheating cpu. The latter of which is especially implicated in laptops (and other small systems) since most brands really just cannot handle being run at full intensity. If prior versions did it as well and 0.15 is more frequent about it, it could just be because 0.15 hits the machine more intensely.\r\n\r\nAll 7 times it has been the chainstate db, not the block index db that was corrupted. I am running a laptop, but it isn't running at full intensity. The CPU isn't often running flat out.\r\n\r\n> But it would be good to eliminate what other causes we can.. What exact cpu model and compiler version are you using?\r\n\r\nAccording to /proc/cpuinfo, it's a 4 core i7-5500U:\r\n\r\n    $ grep 'model name' /proc/cpuinfo | uniq -c\r\n          4 model name\t: Intel(R) Core(TM) i7-5500U CPU @ 2.40GHz\r\n\r\nThe compiler version might be interesting. I switched from using gcc to clang a few months back when I was trying to debug [a crash I get on startup](https://github.com/bitcoin/bitcoin/issues/9683) about 1% of the time. I still see crashes when starting bitcoin-qt very occasionally. I saw one today in fact but I've given up trying to debug it.\r\n\r\n    $ clang++ -v\r\n    clang version 3.8.1-24 (tags/RELEASE_381/final)\r\n    Target: x86_64-pc-linux-gnu\r\n    Thread model: posix\r\n    InstalledDir: /usr/bin\r\n    Found candidate GCC installation: /usr/bin/../lib/gcc/i586-linux-gnu/4.9\r\n    Found candidate GCC installation: /usr/bin/../lib/gcc/i586-linux-gnu/4.9.2\r\n    Found candidate GCC installation: /usr/bin/../lib/gcc/i686-linux-gnu/6.3.0\r\n    Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/4.8\r\n    Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/4.8.4\r\n    Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/4.9\r\n    Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/4.9.2\r\n    Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/6.3.0\r\n    Found candidate GCC installation: /usr/lib/gcc/i586-linux-gnu/4.9\r\n    Found candidate GCC installation: /usr/lib/gcc/i586-linux-gnu/4.9.2\r\n    Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/6.3.0\r\n    Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.8\r\n    Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.8.4\r\n    Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.9\r\n    Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.9.2\r\n    Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/6.3.0\r\n    Selected GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/6.3.0\r\n    Candidate multilib: .;@m64\r\n    Selected multilib: .;@m64\r\n\r\n> Have you run Memtest86 on this system?\r\n\r\nI have, maybe 6 months ago. I let it run for a few hours and it didn't find any problems. I could try letting it run to completion. I have replaced the RAM since then actually so I should run it again anyway. Will report back.",
      "created_at" : "2017-10-26T17:23:25Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/11355#issuecomment-339738256",
      "id" : 339738256,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/11355",
      "updated_at" : "2017-10-26T17:23:25Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/339738256",
      "user" : {
         "avatar_url" : "https://avatars3.githubusercontent.com/u/573356?v=4",
         "events_url" : "https://api.github.com/users/dooglus/events{/privacy}",
         "followers_url" : "https://api.github.com/users/dooglus/followers",
         "following_url" : "https://api.github.com/users/dooglus/following{/other_user}",
         "gists_url" : "https://api.github.com/users/dooglus/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/dooglus",
         "id" : 573356,
         "login" : "dooglus",
         "organizations_url" : "https://api.github.com/users/dooglus/orgs",
         "received_events_url" : "https://api.github.com/users/dooglus/received_events",
         "repos_url" : "https://api.github.com/users/dooglus/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/dooglus/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/dooglus/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/dooglus"
      }
   },
   {
      "author_association" : "CONTRIBUTOR",
      "body" : "> Might be worth trying to store your chainstate on a zfs or btrfs partition to see if any corruption errors can be detected at the filesystem level. COW snapshots could also help you recover more quickly if there is corruption above the filesystem level.\r\n\r\nI have no experience of zfs or btrfs. Is one better than the other for this purpose? Do I need to set any particular configuration to detect filesystem corruption? I'm willing to experiment.",
      "created_at" : "2017-10-26T17:24:46Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/11355#issuecomment-339738622",
      "id" : 339738622,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/11355",
      "updated_at" : "2017-10-26T17:24:46Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/339738622",
      "user" : {
         "avatar_url" : "https://avatars3.githubusercontent.com/u/573356?v=4",
         "events_url" : "https://api.github.com/users/dooglus/events{/privacy}",
         "followers_url" : "https://api.github.com/users/dooglus/followers",
         "following_url" : "https://api.github.com/users/dooglus/following{/other_user}",
         "gists_url" : "https://api.github.com/users/dooglus/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/dooglus",
         "id" : 573356,
         "login" : "dooglus",
         "organizations_url" : "https://api.github.com/users/dooglus/orgs",
         "received_events_url" : "https://api.github.com/users/dooglus/received_events",
         "repos_url" : "https://api.github.com/users/dooglus/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/dooglus/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/dooglus/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/dooglus"
      }
   },
   {
      "author_association" : "CONTRIBUTOR",
      "body" : "Either should work fine, though btrfs is slightly better-supported in Linux-land, even if its newer/a bit less stable in strange edge-cases.",
      "created_at" : "2017-10-26T17:35:15Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/11355#issuecomment-339741490",
      "id" : 339741490,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/11355",
      "updated_at" : "2017-10-26T17:35:15Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/339741490",
      "user" : {
         "avatar_url" : "https://avatars0.githubusercontent.com/u/649246?v=4",
         "events_url" : "https://api.github.com/users/TheBlueMatt/events{/privacy}",
         "followers_url" : "https://api.github.com/users/TheBlueMatt/followers",
         "following_url" : "https://api.github.com/users/TheBlueMatt/following{/other_user}",
         "gists_url" : "https://api.github.com/users/TheBlueMatt/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/TheBlueMatt",
         "id" : 649246,
         "login" : "TheBlueMatt",
         "organizations_url" : "https://api.github.com/users/TheBlueMatt/orgs",
         "received_events_url" : "https://api.github.com/users/TheBlueMatt/received_events",
         "repos_url" : "https://api.github.com/users/TheBlueMatt/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/TheBlueMatt/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/TheBlueMatt/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/TheBlueMatt"
      }
   },
   {
      "author_association" : "CONTRIBUTOR",
      "body" : "Is it safe to assume that if bitcoin starts up successfully with the `-forcecompactdb` flag then the chainstate database currently doesn't have any checksum errors?",
      "created_at" : "2017-10-26T17:39:09Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/11355#issuecomment-339742636",
      "id" : 339742636,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/11355",
      "updated_at" : "2017-10-26T17:39:09Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/339742636",
      "user" : {
         "avatar_url" : "https://avatars3.githubusercontent.com/u/573356?v=4",
         "events_url" : "https://api.github.com/users/dooglus/events{/privacy}",
         "followers_url" : "https://api.github.com/users/dooglus/followers",
         "following_url" : "https://api.github.com/users/dooglus/following{/other_user}",
         "gists_url" : "https://api.github.com/users/dooglus/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/dooglus",
         "id" : 573356,
         "login" : "dooglus",
         "organizations_url" : "https://api.github.com/users/dooglus/orgs",
         "received_events_url" : "https://api.github.com/users/dooglus/received_events",
         "repos_url" : "https://api.github.com/users/dooglus/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/dooglus/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/dooglus/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/dooglus"
      }
   },
   {
      "author_association" : "CONTRIBUTOR",
      "body" : "> I have no experience of zfs or btrfs. Is one better than the other for this purpose? Do I need to set any particular configuration to detect filesystem corruption? I'm willing to experiment\r\n\r\nPersonally I've only used btrfs, not zfs. But neither require configuration to detect corruption, you just need to create a partition, store data on it, and any errors should show up in your system log (and be returned to applications). In btrfs, if you want to create a COW snapshot of a file or directory, you can run `cp -a --reflink SRC DEST`.\r\n\r\n> Is it safe to assume that if bitcoin starts up successfully with the -forcecompactdb flag then the chainstate database currently doesn't have any checksum errors?\r\n\r\nI would guess not. From https://github.com/google/leveldb/blob/master/doc/impl.md, it doesn't seem like a compaction will necessarily rewrite the whole database (for example if it is already compacted). \r\n\r\nMaybe one way to manually verify there are no checksum errors in the database would be to add error reporting to leveldb dump code in src/leveldb/db/dumpfile.cc, which can be run with:\r\n\r\n```sh\r\nmake -C src/leveldb out-static/leveldbutil\r\nsrc/leveldb/out-static/leveldbutil dump ~/.bitcoin/chainstate/*\r\n```",
      "created_at" : "2017-10-26T18:14:29Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/11355#issuecomment-339752813",
      "id" : 339752813,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/11355",
      "updated_at" : "2017-10-26T18:14:29Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/339752813",
      "user" : {
         "avatar_url" : "https://avatars2.githubusercontent.com/u/7133040?v=4",
         "events_url" : "https://api.github.com/users/ryanofsky/events{/privacy}",
         "followers_url" : "https://api.github.com/users/ryanofsky/followers",
         "following_url" : "https://api.github.com/users/ryanofsky/following{/other_user}",
         "gists_url" : "https://api.github.com/users/ryanofsky/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/ryanofsky",
         "id" : 7133040,
         "login" : "ryanofsky",
         "organizations_url" : "https://api.github.com/users/ryanofsky/orgs",
         "received_events_url" : "https://api.github.com/users/ryanofsky/received_events",
         "repos_url" : "https://api.github.com/users/ryanofsky/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/ryanofsky/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/ryanofsky/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/ryanofsky"
      }
   },
   {
      "author_association" : "CONTRIBUTOR",
      "body" : "I don't have any unpartitioned disk space, so I made a file within an existing partition, and made a btrfs filesystem in there. Hopefully that's good enough:\r\n\r\n    chris@chris:~/.bitcoin$ dd if=/dev/zero of=chainstate.btrfs bs=1M count=4096\r\n    4096+0 records in\r\n    4096+0 records out\r\n    4294967296 bytes (4.3 GB, 4.0 GiB) copied, 40.403 s, 106 MB/s\r\n    chris@chris:~/.bitcoin$ mkfs.btrfs chainstate.btrfs\r\n    btrfs-progs v4.7.3\r\n    See http://btrfs.wiki.kernel.org for more information.\r\n\r\n    Label:              (null)\r\n    UUID:               \r\n    Node size:          16384\r\n    Sector size:        4096\r\n    Filesystem size:    4.00GiB\r\n    Block group profiles:\r\n      Data:             single            8.00MiB\r\n      Metadata:         DUP             204.75MiB\r\n      System:           DUP               8.00MiB\r\n    SSD detected:       no\r\n    Incompat features:  extref, skinny-metadata\r\n    Number of devices:  1\r\n    Devices:\r\n       ID        SIZE  PATH\r\n        1     4.00GiB  chainstate.btrfs\r\n\r\n    chris@chris:~/.bitcoin$ bc stop\r\n    Bitcoin server stopping\r\n    chris@chris:~/.bitcoin$ mv chainstate chainstate.good6\r\n    chris@chris:~/.bitcoin$ mkdir chainstate\r\n    chris@chris:~/.bitcoin$ sudo mount chainstate.btrfs chainstate\r\n    chris@chris:~/.bitcoin$ sudo chown chris:chris chainstate\r\n    chris@chris:~/.bitcoin$ df chainstate\r\n    Filesystem      Size  Used Avail Use% Mounted on\r\n    /dev/loop0      4.0G   17M  3.6G   1% /home/chris/.bitcoin/chainstate\r\n    chris@chris:~/.bitcoin$ (cd ~/.bitcoin/chainstate.good6/ && tar cf - .) | (cd ~/.bitcoin/chainstate/ && tar xf -)\r\n    chris@chris:~/.bitcoin$ df chainstate\r\n    Filesystem      Size  Used Avail Use% Mounted on\r\n    /dev/loop0      4.0G  2.5G  1.3G  67% /home/chris/.bitcoin/chainstate\r\n",
      "created_at" : "2017-10-26T18:20:27Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/11355#issuecomment-339754447",
      "id" : 339754447,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/11355",
      "updated_at" : "2017-10-26T18:20:27Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/339754447",
      "user" : {
         "avatar_url" : "https://avatars3.githubusercontent.com/u/573356?v=4",
         "events_url" : "https://api.github.com/users/dooglus/events{/privacy}",
         "followers_url" : "https://api.github.com/users/dooglus/followers",
         "following_url" : "https://api.github.com/users/dooglus/following{/other_user}",
         "gists_url" : "https://api.github.com/users/dooglus/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/dooglus",
         "id" : 573356,
         "login" : "dooglus",
         "organizations_url" : "https://api.github.com/users/dooglus/orgs",
         "received_events_url" : "https://api.github.com/users/dooglus/received_events",
         "repos_url" : "https://api.github.com/users/dooglus/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/dooglus/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/dooglus/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/dooglus"
      }
   },
   {
      "author_association" : "CONTRIBUTOR",
      "body" : ">> Have you run Memtest86 on this system?\r\n\r\n> I have, maybe 6 months ago. I let it run for a few hours and it didn't find any problems. I could try letting it run to completion. I have replaced the RAM since then actually so I should run it again anyway. Will report back.\r\n\r\nI ran it for 2 hours this morning. It got through about 1.5 test cycles without finding any error.\r\n\r\nI tried running it on all 4 cores at once (pressing F2 when memtest86 starts up, I think) and it locked up the computer after about 5 minutes. It remember it used to do that before I upgraded the RAM too. I don't know if that's cause for concern or not.",
      "created_at" : "2017-10-27T00:04:49Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/11355#issuecomment-339834802",
      "id" : 339834802,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/11355",
      "updated_at" : "2017-10-27T00:04:49Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/339834802",
      "user" : {
         "avatar_url" : "https://avatars3.githubusercontent.com/u/573356?v=4",
         "events_url" : "https://api.github.com/users/dooglus/events{/privacy}",
         "followers_url" : "https://api.github.com/users/dooglus/followers",
         "following_url" : "https://api.github.com/users/dooglus/following{/other_user}",
         "gists_url" : "https://api.github.com/users/dooglus/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/dooglus",
         "id" : 573356,
         "login" : "dooglus",
         "organizations_url" : "https://api.github.com/users/dooglus/orgs",
         "received_events_url" : "https://api.github.com/users/dooglus/received_events",
         "repos_url" : "https://api.github.com/users/dooglus/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/dooglus/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/dooglus/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/dooglus"
      }
   },
   {
      "author_association" : "CONTRIBUTOR",
      "body" : "@ryanofsky > Might be worth trying to store your chainstate on a zfs or btrfs partition to see if any corruption errors can be detected at the filesystem level.\r\n\r\nI just had the same crash again. This is the first crash since I moved `chainstate` onto a btrfs filesystem.\r\n\r\ndebug.log:\r\n\r\n    2017-10-29 13:19:16 Pre-allocating up to position 0x5000000 in blk01008.dat\r\n    2017-10-29 13:19:16 Pre-allocating up to position 0xa00000 in rev01008.dat\r\n    2017-10-29 13:19:16 UpdateTip: new best=00000000000000000092bb686c21f129852b3f24aff05113d02b708c9d6c11f6 height=492209 version=0x20000000 log2_work=87.373165 tx=266570069 date='2017-10-29 13:19:00' progress=1.000000 cache=92.8MiB(691920txo) warning='2 of last 100 blocks have unexpected version'\r\n    2017-10-29 13:23:24 UpdateTip: new best=000000000000000000500829275e29849bb2a64a38d2f112d81c8fba43e620b0 height=492210 version=0x20000000 log2_work=87.37321 tx=266572022 date='2017-10-29 13:22:51' progress=1.000000 cache=93.4MiB(697320txo) warning='2 of last 100 blocks have unexpected version'\r\n    2017-10-29 13:23:58 UpdateTip: new best=0000000000000000001d8f1d13239fb8544698ca2bb9bc1cdd2883fc2580556c height=492211 version=0x20000000 log2_work=87.373255 tx=266574358 date='2017-10-29 13:23:23' progress=1.000000 cache=93.9MiB(701053txo) warning='2 of last 100 blocks have unexpected version'\r\n    2017-10-29 17:31:09 socket sending timeout: 14654s\r\n    2017-10-29 17:31:09 socket sending timeout: 14654s\r\n    2017-10-29 17:31:09 socket sending timeout: 14654s\r\n    2017-10-29 17:31:09 socket sending timeout: 14654s\r\n    2017-10-29 17:31:09 socket sending timeout: 14654s\r\n    2017-10-29 17:31:09 socket sending timeout: 14654s\r\n    2017-10-29 17:31:09 socket sending timeout: 14654s\r\n    2017-10-29 17:31:09 socket sending timeout: 14656s\r\n    2017-10-29 17:31:09 connect() to 178.49.137.89:8333 failed: Network is unreachable (101)\r\n    2017-10-29 17:31:10 connect() to 156.11.1.152:8333 failed: Network is unreachable (101)\r\n    2017-10-29 17:31:11 connect() to 18.111.110.151:8333 failed: Network is unreachable (101)\r\n    2017-10-29 17:31:11 connect() to [2002:d941:d96c:8000:0:5efe:a00:7d6]:8333 failed: Network is unreachable (101)\r\n    2017-10-29 17:31:12 connect() to 52.14.94.187:8333 failed: Network is unreachable (101)\r\n    2017-10-29 17:31:12 connect() to 46.59.78.181:8333 failed: Network is unreachable (101)\r\n    2017-10-29 17:31:13 connect() to 92.177.51.206:8333 failed: Network is unreachable (101)\r\n    2017-10-29 17:31:13 connect() to 5.189.165.102:8333 failed: Network is unreachable (101)\r\n    2017-10-29 17:31:14 connect() to [2a04:2180:0:2::77]:8333 failed: Network is unreachable (101)\r\n    2017-10-29 17:31:14 connect() to 71.178.245.103:8333 failed: Network is unreachable (101)\r\n    2017-10-29 17:31:15 connect() to 59.125.8.143:8333 failed: Network is unreachable (101)\r\n    2017-10-29 17:31:15 connect() to 176.159.164.10:8333 failed: Network is unreachable (101)\r\n    2017-10-29 17:31:16 connect() to 130.194.84.251:8333 failed: Network is unreachable (101)\r\n    2017-10-29 17:31:16 connect() to 190.95.220.138:8333 failed: Network is unreachable (101)\r\n    2017-10-29 17:31:17 connect() to 138.201.33.232:8333 failed: Network is unreachable (101)\r\n    2017-10-29 17:31:18 connect() to [2a01:4f8:10a:1d8f::2]:8333 failed: Network is unreachable (101)\r\n    2017-10-29 17:31:18 connect() to 97.87.213.112:8333 failed: Network is unreachable (101)\r\n    2017-10-29 17:31:19 connect() to 52.59.146.184:8333 failed: Network is unreachable (101)\r\n    2017-10-29 17:31:19 connect() to 83.135.85.203:8333 failed: Network is unreachable (101)\r\n    2017-10-29 17:31:20 connect() to 69.162.111.228:8333 failed: Network is unreachable (101)\r\n    2017-10-29 17:31:23 connect() to 212.164.233.103:8333 failed after select(): Connection refused (111)\r\n    2017-10-29 17:31:30 connect() to [2001:0:9d38:6abd:245a:a009:fac1:d805]:8333 failed: Network is unreachable (101)\r\n    2017-10-29 17:31:42 receive version message: /Satoshi:0.14.2/: version 70015, blocks=492233, us=<me>:8284, peer=55\r\n    2017-10-29 17:31:50 receive version message: /Satoshi:0.15.99/: version 70015, blocks=492233, us=<me>:13696, peer=56\r\n    2017-10-29 17:31:50 receive version message: /Satoshi:0.13.2/: version 70015, blocks=492233, us=<me>:27749, peer=57\r\n    2017-10-29 17:31:50 receive version message: /Satoshi:0.14.2/: version 70015, blocks=492233, us=<me>:16359, peer=58\r\n    2017-10-29 17:31:50 connect() to [2001:0:9d38:6abd:1076:1102:aead:172]:8333 failed: Network is unreachable (101)\r\n    2017-10-29 17:31:51 receive version message: /Satoshi:0.14.2/: version 70015, blocks=492233, us=<me>:22722, peer=60\r\n    2017-10-29 17:31:55 socket recv error Connection reset by peer (104)\r\n    2017-10-29 17:32:11 connect() to [2602:306:39de:ea90:c555:2374:2256:6c3d]:8333 failed: Network is unreachable (101)\r\n    2017-10-29 17:32:36 UpdateTip: new best=00000000000000000065aedcb67e1ca2230c9c06a667f11f0a1528839f3c068b height=492212 version=0x20000000 log2_work=87.3733 tx=266576702 date='2017-10-29 13:42:56' progress=0.999840 cache=94.7MiB(707504txo) warning='2 of last 100 blocks have unexpected version'\r\n    2017-10-29 17:32:36 receive version message: /Satoshi:0.15.0.1/: version 70015, blocks=492233, us=<me>:26163, peer=61\r\n    2017-10-29 17:33:19 UpdateTip: new best=0000000000000000000bd68df3f9398932b1535aea34649358e24b5e2b41a9f6 height=492213 version=0x20000000 log2_work=87.373345 tx=266579252 date='2017-10-29 13:43:39' progress=0.999840 cache=95.1MiB(710427txo) warning='2 of last 100 blocks have unexpected version'\r\n    2017-10-29 17:33:19 version handshake timeout from 61\r\n    2017-10-29 17:33:19 version handshake timeout from 62\r\n    2017-10-29 17:33:23 connect() to 51.174.51.66:8333 failed after select(): Connection refused (111)\r\n    2017-10-29 17:33:47 UpdateTip: new best=0000000000000000002565c85bb351e222fd34eb68f0712261689ec7c5f05d33 height=492214 version=0x20000000 log2_work=87.37339 tx=266581963 date='2017-10-29 14:12:23' progress=0.999859 cache=95.6MiB(714560txo) warning='2 of last 100 blocks have unexpected version'\r\n    2017-10-29 17:33:47 version handshake timeout from 63\r\n    2017-10-29 17:34:12 UpdateTip: new best=0000000000000000001f0ffad4402279360668ba5b071ee3206971199bd732f7 height=492215 version=0x20000000 log2_work=87.373435 tx=266585112 date='2017-10-29 14:43:25' progress=0.999881 cache=96.2MiB(719487txo) warning='1 of last 100 blocks have unexpected version'\r\n    2017-10-29 17:34:12 receive version message: /Satoshi:0.15.0/: version 70015, blocks=492234, us=<me>:26749, peer=64\r\n    2017-10-29 17:34:25 version handshake timeout from 64\r\n    2017-10-29 17:34:37 UpdateTip: new best=0000000000000000006d7c1822119613361d0fdb4594ec68990a37d1c42472da height=492216 version=0x20000000 log2_work=87.37348 tx=266587484 date='2017-10-29 14:51:19' progress=0.999886 cache=96.6MiB(723194txo) warning='1 of last 100 blocks have unexpected version'\r\n    2017-10-29 17:34:37 receive version message: /Satoshi:0.13.1/: version 70014, blocks=492234, us=<me>:6057, peer=65\r\n    2017-10-29 17:35:00 Pre-allocating up to position 0xb00000 in rev01008.dat\r\n    2017-10-29 17:35:00 UpdateTip: new best=00000000000000000046d5cabb24f80c5f60e614cb9450b14f5f86548dbac7af height=492217 version=0x20000000 log2_work=87.373525 tx=266589807 date='2017-10-29 14:51:45' progress=0.999886 cache=97.2MiB(728063txo) warning='1 of last 100 blocks have unexpected version'\r\n    2017-10-29 17:35:00 version handshake timeout from 65\r\n    2017-10-29 17:35:00 receive version message: /Satoshi:0.14.2/: version 70015, blocks=492234, us=<me>:6139, peer=66\r\n    2017-10-29 17:35:01 connect() to 85.187.183.13:8333 failed after select(): Connection refused (111)\r\n    2017-10-29 17:35:07 connect() to 157.193.121.83:8333 failed after select(): Connection refused (111)\r\n    2017-10-29 17:35:08 connect() to [2003:f1:5bc3:500:7d68:661:1815:5090]:8333 failed: Network is unreachable (101)\r\n    2017-10-29 17:35:28 UpdateTip: new best=0000000000000000001a5530ee669c4438fa706d53f8e5135f8256488df66ce2 height=492218 version=0x20000000 log2_work=87.373569 tx=266591778 date='2017-10-29 14:55:21' progress=0.999888 cache=97.8MiB(732858txo) warning='1 of last 100 blocks have unexpected version'\r\n    2017-10-29 17:35:28 version handshake timeout from 66\r\n    2017-10-29 17:35:29 receive version message: /Satoshi:0.14.2/: version 70015, blocks=492234, us=<me>:20734, peer=68\r\n    2017-10-29 17:35:29 Pre-allocating up to position 0x6000000 in blk01008.dat\r\n    2017-10-29 17:35:36 UpdateTip: new best=000000000000000000882bdeda9d256d4c172bb4a8b369f1772af19fcb31451d height=492219 version=0x20000000 log2_work=87.373614 tx=266594510 date='2017-10-29 15:20:12' progress=0.999906 cache=98.2MiB(735883txo) warning='1 of last 100 blocks have unexpected version'\r\n    2017-10-29 17:35:40 connect() to 31.28.161.19:8333 failed after select(): Connection refused (111)\r\n    2017-10-29 17:35:43 UpdateTip: new best=0000000000000000004e85fe4b36a585da072f329619001fb50cdcee7d58437c height=492220 version=0x20000000 log2_work=87.373659 tx=266597133 date='2017-10-29 15:36:37' progress=0.999917 cache=98.7MiB(740448txo) warning='1 of last 100 blocks have unexpected version'\r\n    2017-10-29 17:35:49 UpdateTip: new best=000000000000000000a7a14031d4eaac94e2794e0395a7cdef3be6a96c4c8ac1 height=492221 version=0x20000000 log2_work=87.373704 tx=266598920 date='2017-10-29 15:50:43' progress=0.999927 cache=98.7MiB(740177txo) warning='1 of last 100 blocks have unexpected version'\r\n    2017-10-29 17:35:49 receive version message: /Satoshi:0.14.2/: version 70015, blocks=492234, us=<me>:12875, peer=69\r\n    2017-10-29 17:35:50 connect() to 192.42.116.16:8333 failed after select(): Connection refused (111)\r\n    2017-10-29 17:35:50 connect() to 217.16.185.175:8333 failed after select(): Connection refused (111)\r\n    2017-10-29 17:36:00 UpdateTip: new best=00000000000000000039cbb36466e124d82478a80a85d65ca36f0fd40064a993 height=492222 version=0x20000000 log2_work=87.373749 tx=266601379 date='2017-10-29 16:03:24' progress=0.999935 cache=99.2MiB(744167txo) warning='1 of last 100 blocks have unexpected version'\r\n    2017-10-29 17:36:11 UpdateTip: new best=00000000000000000032f3507d2598dda323087d1a3ea128f0b8b4912851b096 height=492223 version=0x20000000 log2_work=87.373794 tx=266603427 date='2017-10-29 16:04:26' progress=0.999936 cache=100.1MiB(751940txo)\r\n    2017-10-29 17:36:11 receive version message: /Satoshi:0.15.0.1/: version 70015, blocks=492234, us=<me>:27617, peer=70\r\n    2017-10-29 17:36:31 Pre-allocating up to position 0xc00000 in rev01008.dat\r\n    2017-10-29 17:36:31 UpdateTip: new best=0000000000000000003277b639e56dffe2b4e60d18aeedb1fe8b7e4256b2a526 height=492224 version=0x20000000 log2_work=87.373839 tx=266605826 date='2017-10-29 16:07:26' progress=0.999938 cache=100.6MiB(756143txo)\r\n    2017-10-29 17:36:43 connect() to [2001:0:9d38:6ab8:1810:10a5:a051:8a63]:8333 failed: Network is unreachable (101)\r\n    2017-10-29 17:36:45 UpdateTip: new best=00000000000000000083ebf6203ebab0082124b89e4be4eeaf1d05882758ce5e height=492225 version=0x20000000 log2_work=87.373884 tx=266607828 date='2017-10-29 16:10:00' progress=0.999939 cache=101.3MiB(761279txo)\r\n    2017-10-29 17:36:50 UpdateTip: new best=000000000000000000bcc54ba6076238c9530fcc28c238d37ff8de13809c96fc height=492226 version=0x20000000 log2_work=87.373929 tx=266610888 date='2017-10-29 16:36:27' progress=0.999958 cache=101.7MiB(765107txo)\r\n    2017-10-29 17:36:57 UpdateTip: new best=0000000000000000006f70ce5e670cb2eb81273a0084967ab3908dfa1f9d3b4b height=492227 version=0x20000000 log2_work=87.373974 tx=266613180 date='2017-10-29 16:44:11' progress=0.999963 cache=102.3MiB(769473txo)\r\n    2017-10-29 17:37:05 UpdateTip: new best=000000000000000000654c6a0ac1fd849176bfe255fc6798f1b31647b0058e15 height=492228 version=0x20000000 log2_work=87.374018 tx=266615764 date='2017-10-29 16:48:42' progress=0.999966 cache=103.1MiB(776461txo)\r\n    2017-10-29 17:37:11 UpdateTip: new best=000000000000000000212978b06e687f8b3a18d952bf049bbad4e08f31f6067f height=492229 version=0x20000000 log2_work=87.374063 tx=266618250 date='2017-10-29 16:51:42' progress=0.999968 cache=103.7MiB(781118txo)\r\n    2017-10-29 17:37:18 UpdateTip: new best=000000000000000000394c6ed382de4b1ca6f1925c5c3aa1454356aec8f9bf99 height=492230 version=0x20000000 log2_work=87.374108 tx=266620126 date='2017-10-29 16:56:29' progress=0.999972 cache=104.1MiB(784164txo)\r\n    2017-10-29 17:37:19 Pre-allocating up to position 0xd00000 in rev01008.dat\r\n    2017-10-29 17:37:19 UpdateTip: new best=000000000000000000610ae3e70726f9dd2026f414a1327cb20f66b8b8ead02c height=492231 version=0x20000000 log2_work=87.374153 tx=266622135 date='2017-10-29 17:04:46' progress=0.999977 cache=104.3MiB(785998txo)\r\n    2017-10-29 17:37:24 UpdateTip: new best=0000000000000000002d7e28f24480fbcecdad62d7f69e2822fcc162ca48e27f height=492232 version=0x20000000 log2_work=87.374198 tx=266624967 date='2017-10-29 17:06:27' progress=0.999978 cache=104.8MiB(789835txo)\r\n    2017-10-29 17:37:25 UpdateTip: new best=000000000000000000a4c6aa4eac92080ce9e8ea94c41c116218477e0fece617 height=492233 version=0x20000000 log2_work=87.374243 tx=266629170 date='2017-10-29 17:07:45' progress=0.999979 cache=104.9MiB(790754txo)\r\n    2017-10-29 17:37:27 UpdateTip: new best=0000000000000000004823ba5cd79517717ab8f9c190c03cb702e9e3432fd81d height=492234 version=0x20000000 log2_work=87.374288 tx=266632276 date='2017-10-29 17:31:59' progress=0.999996 cache=105.4MiB(795421txo)\r\n    2017-10-29 17:37:51 UpdateTip: new best=0000000000000000005e6dd53b92fecd07db6f5668996b95f4d6e41598700ce4 height=492235 version=0x20000000 log2_work=87.374333 tx=266634727 date='2017-10-29 17:36:47' progress=0.999999 cache=106.0MiB(799924txo)\r\n    2017-10-29 17:41:18 connect() to [2001:41d0:1:8135::1]:8333 failed: Network is unreachable (101)\r\n    2017-10-29 17:42:54 Corruption: block checksum mismatch\r\n    2017-10-29 17:42:54 *** System error while flushing: Database corrupted\r\n    2017-10-29 17:43:24 connect() to [2001:0:9d38:6ab8:3018:8f0:26e4:7c97]:8333 failed: Network is unreachable (101)\r\n\r\n    2017-10-29 17:45:26 GUI: QXcbConnection: XCB error: 3 (BadWindow), sequence: 17984, resource id: 11739945, major code: 40 (TranslateCoords), minor code: 0\r\n    2017-10-29 17:45:26 scheduler thread interrupt\r\n    2017-10-29 17:45:26 msghand thread exit\r\n    2017-10-29 17:45:26 opencon thread exit\r\n    2017-10-29 17:45:26 addcon thread exit\r\n    2017-10-29 17:45:26 Shutdown: In progress...\r\n    2017-10-29 17:45:26 net thread exit\r\n    2017-10-29 17:45:30 Dumped mempool: 0.008012s to copy, 0.690163s to dump\r\n    2017-10-29 17:45:30 Corruption: block checksum mismatch\r\n    2017-10-29 17:45:30 *** System error while flushing: Database corrupted\r\n    2017-10-29 17:46:21 Corruption: block checksum mismatch\r\n    2017-10-29 17:46:21 *** System error while flushing: Database corrupted\r\n    2017-10-29 17:46:27 GUI: QXcbConnection: XCB error: 3 (BadWindow), sequence: 18529, resource id: 11745836, major code: 40 (TranslateCoords), minor code: 0\r\n    2017-10-29 17:46:27 Shutdown: done\r\n\r\nfsck on the btrfs system:\r\n\r\n    10:48:29 chris@chris:~/.bitcoin$ mount | grep chainst\r\n    /home/chris/.bitcoin/chainstate.btrfs on /home/chris/.bitcoin/chainstate type btrfs (rw,relatime,space_cache,subvolid=5,subvol=/)\r\n    10:48:49 chris@chris:~/.bitcoin$ sudo umount ~/.bitcoin/chainstate\r\n    [sudo] password for chris: \r\n    10:52:53 chris@chris:~/.bitcoin$ btrfsck --readonly chainstate.btrfs\r\n    Checking filesystem on chainstate.btrfs\r\n    UUID: 24eb317a-d18d-4df4-8cac-a6e0b1e1105c\r\n    checking extents\r\n    checking free space cache\r\n    checking fs roots\r\n    checking csums\r\n    checking root refs\r\n    found 2982662144 bytes used err is 0\r\n    total csum bytes: 2906980\r\n    total tree bytes: 5324800\r\n    total fs tree bytes: 999424\r\n    total extent tree bytes: 196608\r\n    btree space waste bytes: 1492325\r\n    file data blocks allocated: 2977337344\r\n     referenced 2977247232\r\n    10:52:59 chris@chris:~/.bitcoin$ btrfsck --readonly --check-data-csum chainstate.btrfs\r\n    Checking filesystem on chainstate.btrfs\r\n    UUID: 24eb317a-d18d-4df4-8cac-a6e0b1e1105c\r\n    checking extents\r\n    checking free space cache\r\n    checking fs roots\r\n    checking csums\r\n    checking root refs\r\n    found 2982662144 bytes used err is 0\r\n    total csum bytes: 2906980\r\n    total tree bytes: 5324800\r\n    total fs tree bytes: 999424\r\n    total extent tree bytes: 196608\r\n    btree space waste bytes: 1492325\r\n    file data blocks allocated: 2977337344\r\n     referenced 2977247232\r\n    10:54:48 chris@chris:~/.bitcoin$ sudo mount ~/.bitcoin/chainstate.btrfs ~/.bitcoin/chainstate\r\n    [sudo] password for chris: \r\n    11:05:10 chris@chris:~/.bitcoin$ df chainstate\r\n    Filesystem      Size  Used Avail Use% Mounted on\r\n    /dev/loop0      4.0G  2.8G  831M  78% /home/chris/.bitcoin/chainstate\r\n    11:05:15 chris@chris:~/.bitcoin$ \r\n\r\nWhich file(s) should I look in for any filesystem errors that may have been logged?\r\n\r\nDoes this clean fsck rule out the possibility of the corruption being caused by hard drive or filesystem errors?\r\n\r\nEdit: I see that the laptop suspended which I was sleeping, probably when a kitten jumped on the laptop lid at 6:26am, and resumed around the time of the crash:\r\n\r\n    ==> auth.log <==\r\n    Oct 29 06:26:50 chris systemd-logind[649]: Lid closed.\r\n    Oct 29 06:26:50 chris systemd-logind[649]: Suspending...\r\n    Oct 29 10:31:09 chris systemd-logind[649]: Lid opened.\r\n\r\nI'm currently 7 hours behind UTC, so 10:31 in the `auth.log` is 17:31 in Bitcoin's `debug.log`.",
      "created_at" : "2017-10-29T18:17:00Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/11355#issuecomment-340282506",
      "id" : 340282506,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/11355",
      "updated_at" : "2017-10-29T19:02:31Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/340282506",
      "user" : {
         "avatar_url" : "https://avatars3.githubusercontent.com/u/573356?v=4",
         "events_url" : "https://api.github.com/users/dooglus/events{/privacy}",
         "followers_url" : "https://api.github.com/users/dooglus/followers",
         "following_url" : "https://api.github.com/users/dooglus/following{/other_user}",
         "gists_url" : "https://api.github.com/users/dooglus/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/dooglus",
         "id" : 573356,
         "login" : "dooglus",
         "organizations_url" : "https://api.github.com/users/dooglus/orgs",
         "received_events_url" : "https://api.github.com/users/dooglus/received_events",
         "repos_url" : "https://api.github.com/users/dooglus/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/dooglus/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/dooglus/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/dooglus"
      }
   },
   {
      "author_association" : "CONTRIBUTOR",
      "body" : "I restarted bitcoin-qt after the crash in my immediately previous comment and was able to sync the blockchain without error. I didn't see any more \"Corruption: block checksum mismatch\" messages, and everything seemed to go fine. That's without doing any kind of repair on the database which was earlier reported to be corrupted.\r\n\r\nSomething strange is going on.\r\n\r\nI tried running with `-forcecompactdb` - it took 26 minutes to compact the block index, and another 7 minutes to compact the chainstate, but again managed to compact both without any warnings or errors being reported:\r\n\r\n    2017-10-29 19:55:20 Starting database compaction of /home/chris/.bitcoin/blocks/index\r\n    2017-10-29 20:21:00 Finished database compaction of /home/chris/.bitcoin/blocks/index\r\n    2017-10-29 20:21:00 Using obfuscation key for /home/chris/.bitcoin/blocks/index: 0000000000000000\r\n    2017-10-29 20:21:04 LoadBlockIndexDB: last block file = 1008\r\n    2017-10-29 20:21:04 LoadBlockIndexDB: last block file info: CBlockFileInfo(blocks=103, size=104965446, heights=492143...492245, time=2017-10-29...2017-10-29)\r\n    2017-10-29 20:21:04 Checking all blk files are present...\r\n    2017-10-29 20:21:04 LoadBlockIndexDB: transaction index enabled\r\n    2017-10-29 20:21:04 Opening LevelDB in /home/chris/.bitcoin/chainstate\r\n    2017-10-29 20:21:05 Opened LevelDB successfully\r\n    2017-10-29 20:21:05 Starting database compaction of /home/chris/.bitcoin/chainstate\r\n    2017-10-29 20:28:35 Finished database compaction of /home/chris/.bitcoin/chainstate\r\n    2017-10-29 20:28:35 Using obfuscation key for /home/chris/.bitcoin/chainstate: 5d6a8c01975f3412\r\n\r\nI don't understand why I'm seeing this particular error over and over again but almost nobody else is seeing it.",
      "created_at" : "2017-10-30T01:33:57Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/11355#issuecomment-340321491",
      "id" : 340321491,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/11355",
      "updated_at" : "2017-10-30T01:33:57Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/340321491",
      "user" : {
         "avatar_url" : "https://avatars3.githubusercontent.com/u/573356?v=4",
         "events_url" : "https://api.github.com/users/dooglus/events{/privacy}",
         "followers_url" : "https://api.github.com/users/dooglus/followers",
         "following_url" : "https://api.github.com/users/dooglus/following{/other_user}",
         "gists_url" : "https://api.github.com/users/dooglus/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/dooglus",
         "id" : 573356,
         "login" : "dooglus",
         "organizations_url" : "https://api.github.com/users/dooglus/orgs",
         "received_events_url" : "https://api.github.com/users/dooglus/received_events",
         "repos_url" : "https://api.github.com/users/dooglus/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/dooglus/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/dooglus/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/dooglus"
      }
   },
   {
      "author_association" : "NONE",
      "body" : "I just got this `block checksum mismatch` error during the late stages of an initial sync on a raspi 3 running raspian stretch configured for pruning. As far as I can tell it happened out of the blue while it was left to sync - I'd only been checking on the sync progress a couple of times a day. I have a nearly identical setup that's working fine, but I used 0.14 for the initial sync on there (since upgraded to 0.15). Here's the relevant portion from debug.log.\r\n\r\n```\r\n2017-10-29 23:42:39 UpdateTip: new best=000000000000000002df85b73562d01bff8e13389ae99532093a6e0b019eb348 height=422372 version=0x20000000 log2_work=85.04258 tx=144960767 date='2016-07-26 18:11:29' progress=0.542795 cache=43.9MiB(255554txo)\r\n2017-10-29 23:42:39 socket send error Connection reset by peer (104)\r\n2017-10-29 23:42:40 receive version message: /Satoshi:0.12.1/: version 70012, blocks=492271, us=69.143.4.96:47562, peer=1217\r\n2017-10-29 23:42:40 Leaving block file 582: CBlockFileInfo(blocks=160, size=133623360, heights=422316...422733, time=2016-07-26...2016-07-29)\r\n2017-10-29 23:42:42 Pre-allocating up to position 0x1000000 in blk00583.dat\r\n2017-10-29 23:42:42 receive version message: /Satoshi:0.15.0.1/: version 70015, blocks=492271, us=[2601:141:201:79a0:2f44:dfe0:5692:275c]:38382, peer=1218\r\n2017-10-29 23:42:44 Pre-allocating up to position 0x2000000 in blk00583.dat\r\n2017-10-29 23:42:47 Prune: UnlinkPrunedFiles deleted blk/rev (00553)\r\n2017-10-29 23:42:48 Corruption: block checksum mismatch\r\n2017-10-29 23:42:48 *** System error while flushing: Database corrupted\r\n2017-10-29 23:42:48 Error: Error: A fatal internal error occurred, see debug.log for details\r\n2017-10-29 23:42:48 tor: Thread interrupt\r\n2017-10-29 23:42:48 torcontrol thread exit\r\n2017-10-29 23:42:48 addcon thread exit\r\n2017-10-29 23:42:48 opencon thread exit\r\n2017-10-29 23:42:48 net thread exit\r\n2017-10-29 23:42:48 msghand thread exit\r\n2017-10-29 23:42:48 scheduler thread interrupt\r\n2017-10-29 23:42:48 Shutdown: In progress...\r\n2017-10-29 23:42:50 UPNP_DeletePortMapping() returned: 0\r\n2017-10-29 23:42:50 upnp thread interrupt\r\n2017-10-29 23:42:52 Dumped mempool: 0.003313s to copy, 0.041511s to dump\r\n2017-10-29 23:42:52 Corruption: block checksum mismatch\r\n2017-10-29 23:42:52 *** System error while flushing: Database corrupted\r\n2017-10-29 23:42:52 Error: Error: A fatal internal error occurred, see debug.log for details\r\n2017-10-29 23:42:52 Corruption: block checksum mismatch\r\n2017-10-29 23:42:52 *** System error while flushing: Database corrupted\r\n2017-10-29 23:42:52 Error: Error: A fatal internal error occurred, see debug.log for details\r\n2017-10-29 23:42:53 Shutdown: done\r\n```",
      "created_at" : "2017-10-30T04:23:59Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/11355#issuecomment-340340542",
      "id" : 340340542,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/11355",
      "updated_at" : "2017-10-30T04:23:59Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/340340542",
      "user" : {
         "avatar_url" : "https://avatars1.githubusercontent.com/u/3440835?v=4",
         "events_url" : "https://api.github.com/users/sangaman/events{/privacy}",
         "followers_url" : "https://api.github.com/users/sangaman/followers",
         "following_url" : "https://api.github.com/users/sangaman/following{/other_user}",
         "gists_url" : "https://api.github.com/users/sangaman/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/sangaman",
         "id" : 3440835,
         "login" : "sangaman",
         "organizations_url" : "https://api.github.com/users/sangaman/orgs",
         "received_events_url" : "https://api.github.com/users/sangaman/received_events",
         "repos_url" : "https://api.github.com/users/sangaman/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/sangaman/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/sangaman/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/sangaman"
      }
   },
   {
      "author_association" : "CONTRIBUTOR",
      "body" : "Thanks for the report @sangaman. It's reassuring to hear of others experiencing the same issue.\r\n\r\nWas the system which crashed running version 0.15 for the whole sync?\r\n\r\nI run a pruned 0.15 node and have never had it crash. I don't leave it running though, I run it every few days until it has synced and then shut it down again.",
      "created_at" : "2017-10-30T04:33:33Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/11355#issuecomment-340341527",
      "id" : 340341527,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/11355",
      "updated_at" : "2017-10-30T04:33:33Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/340341527",
      "user" : {
         "avatar_url" : "https://avatars3.githubusercontent.com/u/573356?v=4",
         "events_url" : "https://api.github.com/users/dooglus/events{/privacy}",
         "followers_url" : "https://api.github.com/users/dooglus/followers",
         "following_url" : "https://api.github.com/users/dooglus/following{/other_user}",
         "gists_url" : "https://api.github.com/users/dooglus/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/dooglus",
         "id" : 573356,
         "login" : "dooglus",
         "organizations_url" : "https://api.github.com/users/dooglus/orgs",
         "received_events_url" : "https://api.github.com/users/dooglus/received_events",
         "repos_url" : "https://api.github.com/users/dooglus/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/dooglus/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/dooglus/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/dooglus"
      }
   },
   {
      "author_association" : "NONE",
      "body" : "The system that crashed has been running 0.15 the entire time. The other system completed the initial sync on 0.14, has been running 0.15 for the past few weeks ~24/7, and has never crashed. Both systems were created from the same image and I followed the same steps for setting them up, so the only real difference there is 0.14 vs 0.15.",
      "created_at" : "2017-10-30T04:39:30Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/11355#issuecomment-340342139",
      "id" : 340342139,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/11355",
      "updated_at" : "2017-10-30T04:39:30Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/340342139",
      "user" : {
         "avatar_url" : "https://avatars1.githubusercontent.com/u/3440835?v=4",
         "events_url" : "https://api.github.com/users/sangaman/events{/privacy}",
         "followers_url" : "https://api.github.com/users/sangaman/followers",
         "following_url" : "https://api.github.com/users/sangaman/following{/other_user}",
         "gists_url" : "https://api.github.com/users/sangaman/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/sangaman",
         "id" : 3440835,
         "login" : "sangaman",
         "organizations_url" : "https://api.github.com/users/sangaman/orgs",
         "received_events_url" : "https://api.github.com/users/sangaman/received_events",
         "repos_url" : "https://api.github.com/users/sangaman/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/sangaman/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/sangaman/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/sangaman"
      }
   },
   {
      "author_association" : "CONTRIBUTOR",
      "body" : "Does your Pi ever suspend itself?\r\n\r\nDo you see a 'gap' in the debug.log timestamps shortly before the crash? See for example in [this comment](https://github.com/bitcoin/bitcoin/issues/11355#issuecomment-340282506) where there's a 4 hour gap in the timestamps between the 5th and 6th lines of the debug.log I posted.",
      "created_at" : "2017-10-30T04:42:58Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/11355#issuecomment-340342509",
      "id" : 340342509,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/11355",
      "updated_at" : "2017-10-30T04:42:58Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/340342509",
      "user" : {
         "avatar_url" : "https://avatars3.githubusercontent.com/u/573356?v=4",
         "events_url" : "https://api.github.com/users/dooglus/events{/privacy}",
         "followers_url" : "https://api.github.com/users/dooglus/followers",
         "following_url" : "https://api.github.com/users/dooglus/following{/other_user}",
         "gists_url" : "https://api.github.com/users/dooglus/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/dooglus",
         "id" : 573356,
         "login" : "dooglus",
         "organizations_url" : "https://api.github.com/users/dooglus/orgs",
         "received_events_url" : "https://api.github.com/users/dooglus/received_events",
         "repos_url" : "https://api.github.com/users/dooglus/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/dooglus/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/dooglus/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/dooglus"
      }
   },
   {
      "author_association" : "NONE",
      "body" : "Hm I don't believe it suspends itself, it has been syncing continuously pretty much since I set it up. I scrolled through the past ~48 hours of debug.log and didn't see any gaps in the timestamps. My other pi is also running continuously as far as I can tell.",
      "created_at" : "2017-10-30T04:49:02Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/11355#issuecomment-340343114",
      "id" : 340343114,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/11355",
      "updated_at" : "2017-10-30T04:49:02Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/340343114",
      "user" : {
         "avatar_url" : "https://avatars1.githubusercontent.com/u/3440835?v=4",
         "events_url" : "https://api.github.com/users/sangaman/events{/privacy}",
         "followers_url" : "https://api.github.com/users/sangaman/followers",
         "following_url" : "https://api.github.com/users/sangaman/following{/other_user}",
         "gists_url" : "https://api.github.com/users/sangaman/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/sangaman",
         "id" : 3440835,
         "login" : "sangaman",
         "organizations_url" : "https://api.github.com/users/sangaman/orgs",
         "received_events_url" : "https://api.github.com/users/sangaman/received_events",
         "repos_url" : "https://api.github.com/users/sangaman/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/sangaman/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/sangaman/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/sangaman"
      }
   },
   {
      "author_association" : "NONE",
      "body" : "Just an update - I have copied over the `.bitcoin` folder from my working raspi to the one that crashed yesterday (to avoid having to start the initial sync all over again). Everything running fine for the time being, but I'll update this thread if I encounter the issue again. I also have preserved the old `.bitcoin` folder in the broken state in case it may be useful for debugging the issue.",
      "created_at" : "2017-10-30T21:34:55Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/11355#issuecomment-340591860",
      "id" : 340591860,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/11355",
      "updated_at" : "2017-10-30T21:34:55Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/340591860",
      "user" : {
         "avatar_url" : "https://avatars1.githubusercontent.com/u/3440835?v=4",
         "events_url" : "https://api.github.com/users/sangaman/events{/privacy}",
         "followers_url" : "https://api.github.com/users/sangaman/followers",
         "following_url" : "https://api.github.com/users/sangaman/following{/other_user}",
         "gists_url" : "https://api.github.com/users/sangaman/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/sangaman",
         "id" : 3440835,
         "login" : "sangaman",
         "organizations_url" : "https://api.github.com/users/sangaman/orgs",
         "received_events_url" : "https://api.github.com/users/sangaman/received_events",
         "repos_url" : "https://api.github.com/users/sangaman/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/sangaman/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/sangaman/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/sangaman"
      }
   },
   {
      "author_association" : "CONTRIBUTOR",
      "body" : "@dooglus your memtest86 issues scare me. Have you tried to run linpack recently? I'd be curious to see how your CPU does under such conditions and see if it generates any errors.\r\n\r\n@sangaman Does your RPi have a heatsink? Does it overheat during sync?",
      "created_at" : "2017-10-30T23:09:25Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/11355#issuecomment-340611913",
      "id" : 340611913,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/11355",
      "updated_at" : "2017-10-30T23:09:56Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/340611913",
      "user" : {
         "avatar_url" : "https://avatars0.githubusercontent.com/u/649246?v=4",
         "events_url" : "https://api.github.com/users/TheBlueMatt/events{/privacy}",
         "followers_url" : "https://api.github.com/users/TheBlueMatt/followers",
         "following_url" : "https://api.github.com/users/TheBlueMatt/following{/other_user}",
         "gists_url" : "https://api.github.com/users/TheBlueMatt/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/TheBlueMatt",
         "id" : 649246,
         "login" : "TheBlueMatt",
         "organizations_url" : "https://api.github.com/users/TheBlueMatt/orgs",
         "received_events_url" : "https://api.github.com/users/TheBlueMatt/received_events",
         "repos_url" : "https://api.github.com/users/TheBlueMatt/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/TheBlueMatt/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/TheBlueMatt/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/TheBlueMatt"
      }
   },
   {
      "author_association" : "CONTRIBUTOR",
      "body" : "@TheBlueMatt I've never even heard of linpack.\r\n\r\nYou're talking about [this](https://en.wikipedia.org/wiki/LINPACK_benchmarks)?\r\n\r\n> The LINPACK Benchmarks are a measure of a system's floating point computing power. Introduced by Jack Dongarra, they measure how fast a computer solves a dense n by n system of linear equations Ax = b, which is a common task in engineering.",
      "created_at" : "2017-10-31T05:07:17Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/11355#issuecomment-340661440",
      "id" : 340661440,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/11355",
      "updated_at" : "2017-10-31T05:07:17Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/340661440",
      "user" : {
         "avatar_url" : "https://avatars3.githubusercontent.com/u/573356?v=4",
         "events_url" : "https://api.github.com/users/dooglus/events{/privacy}",
         "followers_url" : "https://api.github.com/users/dooglus/followers",
         "following_url" : "https://api.github.com/users/dooglus/following{/other_user}",
         "gists_url" : "https://api.github.com/users/dooglus/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/dooglus",
         "id" : 573356,
         "login" : "dooglus",
         "organizations_url" : "https://api.github.com/users/dooglus/orgs",
         "received_events_url" : "https://api.github.com/users/dooglus/received_events",
         "repos_url" : "https://api.github.com/users/dooglus/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/dooglus/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/dooglus/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/dooglus"
      }
   },
   {
      "author_association" : "CONTRIBUTOR",
      "body" : "Yes, linpack is one of the more aggressive benchmarking tools. I'm curious to see if your CPU instantly overheats if you run it.\n\nOn October 31, 2017 1:07:30 AM EDT, Chris Moore <notifications@github.com> wrote:\n>@TheBlueMatt I've never even heard of linpack.\n>\n>You're talking about\n>[this](https://en.wikipedia.org/wiki/LINPACK_benchmarks)?\n>\n>> The LINPACK Benchmarks are a measure of a system's floating point\n>computing power. Introduced by Jack Dongarra, they measure how fast a\n>computer solves a dense n by n system of linear equations Ax = b, which\n>is a common task in engineering.\n>\n>-- \n>You are receiving this because you were mentioned.\n>Reply to this email directly or view it on GitHub:\n>https://github.com/bitcoin/bitcoin/issues/11355#issuecomment-340661440\n",
      "created_at" : "2017-10-31T12:05:05Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/11355#issuecomment-340742369",
      "id" : 340742369,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/11355",
      "updated_at" : "2017-10-31T12:05:05Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/340742369",
      "user" : {
         "avatar_url" : "https://avatars0.githubusercontent.com/u/649246?v=4",
         "events_url" : "https://api.github.com/users/TheBlueMatt/events{/privacy}",
         "followers_url" : "https://api.github.com/users/TheBlueMatt/followers",
         "following_url" : "https://api.github.com/users/TheBlueMatt/following{/other_user}",
         "gists_url" : "https://api.github.com/users/TheBlueMatt/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/TheBlueMatt",
         "id" : 649246,
         "login" : "TheBlueMatt",
         "organizations_url" : "https://api.github.com/users/TheBlueMatt/orgs",
         "received_events_url" : "https://api.github.com/users/TheBlueMatt/received_events",
         "repos_url" : "https://api.github.com/users/TheBlueMatt/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/TheBlueMatt/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/TheBlueMatt/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/TheBlueMatt"
      }
   },
   {
      "author_association" : "NONE",
      "body" : "@TheBlueMatt I do have heatsinks on them, although I didn't ever check the temperatures on them during initial sync. They aren't overclocked or modded in any way.",
      "created_at" : "2017-10-31T13:42:10Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/11355#issuecomment-340765635",
      "id" : 340765635,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/11355",
      "updated_at" : "2017-10-31T13:42:10Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/340765635",
      "user" : {
         "avatar_url" : "https://avatars1.githubusercontent.com/u/3440835?v=4",
         "events_url" : "https://api.github.com/users/sangaman/events{/privacy}",
         "followers_url" : "https://api.github.com/users/sangaman/followers",
         "following_url" : "https://api.github.com/users/sangaman/following{/other_user}",
         "gists_url" : "https://api.github.com/users/sangaman/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/sangaman",
         "id" : 3440835,
         "login" : "sangaman",
         "organizations_url" : "https://api.github.com/users/sangaman/orgs",
         "received_events_url" : "https://api.github.com/users/sangaman/received_events",
         "repos_url" : "https://api.github.com/users/sangaman/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/sangaman/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/sangaman/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/sangaman"
      }
   },
   {
      "author_association" : "CONTRIBUTOR",
      "body" : "Here's a possibly interesting data point:\r\n\r\nMy Bitcoin Cash node corrupted its chainstate yesterday.\r\n\r\nAs I understand it, Bitcoin Cash is based on a pre 0.15 release of Bitcoin Core (they call it 0.14.6).\r\n\r\nI built it from commit a46e63c2bb3d189beb846a8d34a0d33fd563fa7b.\r\n\r\nThis leads me to believe that the corruption I keep seeing in Core's chainstate db isn't new in 0.15 as I previously suspected.",
      "created_at" : "2017-11-13T20:01:09Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/11355#issuecomment-344039980",
      "id" : 344039980,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/11355",
      "updated_at" : "2017-11-13T20:01:09Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/344039980",
      "user" : {
         "avatar_url" : "https://avatars3.githubusercontent.com/u/573356?v=4",
         "events_url" : "https://api.github.com/users/dooglus/events{/privacy}",
         "followers_url" : "https://api.github.com/users/dooglus/followers",
         "following_url" : "https://api.github.com/users/dooglus/following{/other_user}",
         "gists_url" : "https://api.github.com/users/dooglus/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/dooglus",
         "id" : 573356,
         "login" : "dooglus",
         "organizations_url" : "https://api.github.com/users/dooglus/orgs",
         "received_events_url" : "https://api.github.com/users/dooglus/received_events",
         "repos_url" : "https://api.github.com/users/dooglus/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/dooglus/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/dooglus/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/dooglus"
      }
   },
   {
      "author_association" : "NONE",
      "body" : "I had a checksum corruption error these days. The difference to this case was, that it happened after the syncing process was finished. See: https://github.com/bitcoin/bitcoin/issues/11627\r\nThe experts opinion was that it must have been a disk falior. That might be, but I have no other evidence that the disk used is wearing out. I do observe bugs in bitcoin core after having imported a private key from another wallet and after changing the wallet.dat file (causing a rescan). The data corruption problem begun after several rescans and ther is a chance that there is really a bug in bitcoin core which leads to data corruption. But so far no real proof. ",
      "created_at" : "2017-11-15T07:11:24Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/11355#issuecomment-344505509",
      "id" : 344505509,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/11355",
      "updated_at" : "2017-11-15T07:11:24Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/344505509",
      "user" : {
         "avatar_url" : "https://avatars2.githubusercontent.com/u/15250834?v=4",
         "events_url" : "https://api.github.com/users/kollokollo/events{/privacy}",
         "followers_url" : "https://api.github.com/users/kollokollo/followers",
         "following_url" : "https://api.github.com/users/kollokollo/following{/other_user}",
         "gists_url" : "https://api.github.com/users/kollokollo/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/kollokollo",
         "id" : 15250834,
         "login" : "kollokollo",
         "organizations_url" : "https://api.github.com/users/kollokollo/orgs",
         "received_events_url" : "https://api.github.com/users/kollokollo/received_events",
         "repos_url" : "https://api.github.com/users/kollokollo/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/kollokollo/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/kollokollo/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/kollokollo"
      }
   },
   {
      "author_association" : "CONTRIBUTOR",
      "body" : "@kollokollo I dont think the \"expert opinion\" is that it is disk failure, much, much more likely CPU is corrupting data in-flight (due to thermal issues/overclock/other instability) or the memory is corrupting data (also likely for similar reasons).",
      "created_at" : "2017-11-15T22:31:00Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/11355#issuecomment-344750911",
      "id" : 344750911,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/11355",
      "updated_at" : "2017-11-15T22:31:00Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/344750911",
      "user" : {
         "avatar_url" : "https://avatars0.githubusercontent.com/u/649246?v=4",
         "events_url" : "https://api.github.com/users/TheBlueMatt/events{/privacy}",
         "followers_url" : "https://api.github.com/users/TheBlueMatt/followers",
         "following_url" : "https://api.github.com/users/TheBlueMatt/following{/other_user}",
         "gists_url" : "https://api.github.com/users/TheBlueMatt/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/TheBlueMatt",
         "id" : 649246,
         "login" : "TheBlueMatt",
         "organizations_url" : "https://api.github.com/users/TheBlueMatt/orgs",
         "received_events_url" : "https://api.github.com/users/TheBlueMatt/received_events",
         "repos_url" : "https://api.github.com/users/TheBlueMatt/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/TheBlueMatt/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/TheBlueMatt/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/TheBlueMatt"
      }
   },
   {
      "author_association" : "NONE",
      "body" : "I am suprized to hear that a normal Laptop would miscalculate \"on the fly\". But I am not the expert here. \r\nI just want to help debugging the application.",
      "created_at" : "2017-11-16T07:42:04Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/11355#issuecomment-344841039",
      "id" : 344841039,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/11355",
      "updated_at" : "2017-11-16T07:42:04Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/344841039",
      "user" : {
         "avatar_url" : "https://avatars2.githubusercontent.com/u/15250834?v=4",
         "events_url" : "https://api.github.com/users/kollokollo/events{/privacy}",
         "followers_url" : "https://api.github.com/users/kollokollo/followers",
         "following_url" : "https://api.github.com/users/kollokollo/following{/other_user}",
         "gists_url" : "https://api.github.com/users/kollokollo/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/kollokollo",
         "id" : 15250834,
         "login" : "kollokollo",
         "organizations_url" : "https://api.github.com/users/kollokollo/orgs",
         "received_events_url" : "https://api.github.com/users/kollokollo/received_events",
         "repos_url" : "https://api.github.com/users/kollokollo/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/kollokollo/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/kollokollo/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/kollokollo"
      }
   },
   {
      "author_association" : "OWNER",
      "body" : "> I am suprized to hear that a normal Laptop would miscalculate \"on the fly\"\r\n\r\nEspecially those! Laptops are much more likely to have bad thermal management than desktops or servers (less room than desktops, not designed for heavy loads like servers, generally no ECC on memory). Also the fans tend to get cluttered with dust much quicker.",
      "created_at" : "2017-11-16T12:49:41Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/11355#issuecomment-344913168",
      "id" : 344913168,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/11355",
      "updated_at" : "2017-11-16T12:53:03Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/344913168",
      "user" : {
         "avatar_url" : "https://avatars0.githubusercontent.com/u/126646?v=4",
         "events_url" : "https://api.github.com/users/laanwj/events{/privacy}",
         "followers_url" : "https://api.github.com/users/laanwj/followers",
         "following_url" : "https://api.github.com/users/laanwj/following{/other_user}",
         "gists_url" : "https://api.github.com/users/laanwj/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/laanwj",
         "id" : 126646,
         "login" : "laanwj",
         "organizations_url" : "https://api.github.com/users/laanwj/orgs",
         "received_events_url" : "https://api.github.com/users/laanwj/received_events",
         "repos_url" : "https://api.github.com/users/laanwj/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/laanwj/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/laanwj/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/laanwj"
      }
   },
   {
      "author_association" : "OWNER",
      "body" : "BTW if anyone suffering leveldb corruption issues wants to help me inventarize the kind of corruptions that happen, please try #11674 to improve leveldb's error logging and send me the specific file that it labels as corrupted.",
      "created_at" : "2017-11-16T12:52:24Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/11355#issuecomment-344913822",
      "id" : 344913822,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/11355",
      "updated_at" : "2017-11-16T12:52:24Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/344913822",
      "user" : {
         "avatar_url" : "https://avatars0.githubusercontent.com/u/126646?v=4",
         "events_url" : "https://api.github.com/users/laanwj/events{/privacy}",
         "followers_url" : "https://api.github.com/users/laanwj/followers",
         "following_url" : "https://api.github.com/users/laanwj/following{/other_user}",
         "gists_url" : "https://api.github.com/users/laanwj/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/laanwj",
         "id" : 126646,
         "login" : "laanwj",
         "organizations_url" : "https://api.github.com/users/laanwj/orgs",
         "received_events_url" : "https://api.github.com/users/laanwj/received_events",
         "repos_url" : "https://api.github.com/users/laanwj/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/laanwj/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/laanwj/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/laanwj"
      }
   },
   {
      "author_association" : "CONTRIBUTOR",
      "body" : ">> I am suprized to hear that a normal Laptop would miscalculate \"on the fly\"\r\n>\r\n> Especially those! Laptops are much more likely to have bad thermal management\r\n\r\nMaybe I am thinking about this wrong, but the thing I don't understand is if the problem is cpu/memory hardware failures, how come we seem to be seeing more leveldb checksum errors than bitcoin validation errors (mismatched hashes, bad signatures)? Presumably leveldb checksums aren't particularly expensive to compute and the hardware is spending much more time checking bitcoin signatures and hashes and computing leveldb checksums, so shouldn't we expect more bitcoin errors and fewer leveldb errors?\r\n\r\nIs the answer that bitcoin signatures and hashes tend to be checked once and trusted forever, while leveldb checksums are read and checked more continuously? I would think overheating laptops and raspberry pis should never be able to get through an initial sync if they can't even compute leveldb checksums reliably.",
      "created_at" : "2017-11-16T13:10:44Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/11355#issuecomment-344918064",
      "id" : 344918064,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/11355",
      "updated_at" : "2017-11-16T13:10:44Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/344918064",
      "user" : {
         "avatar_url" : "https://avatars2.githubusercontent.com/u/7133040?v=4",
         "events_url" : "https://api.github.com/users/ryanofsky/events{/privacy}",
         "followers_url" : "https://api.github.com/users/ryanofsky/followers",
         "following_url" : "https://api.github.com/users/ryanofsky/following{/other_user}",
         "gists_url" : "https://api.github.com/users/ryanofsky/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/ryanofsky",
         "id" : 7133040,
         "login" : "ryanofsky",
         "organizations_url" : "https://api.github.com/users/ryanofsky/orgs",
         "received_events_url" : "https://api.github.com/users/ryanofsky/received_events",
         "repos_url" : "https://api.github.com/users/ryanofsky/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/ryanofsky/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/ryanofsky/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/ryanofsky"
      }
   },
   {
      "author_association" : "OWNER",
      "body" : "> Maybe I am thinking about this wrong, but the thing I don't understand is if the problem is cpu/memory hardware failures, how come we seem to be seeing more leveldb checksum errors than bitcoin validation errors (mismatched hashes, bad signatures)?\r\n\r\nWe do see validation errors and nodes getting stuck after failing to verify a valid block once in a while - but they don't terminate the process with an immediate error, so might be less likely to get reported!\r\n\r\n> Is the answer that bitcoin signatures and hashes tend to be checked once and trusted forever, while leveldb checksums are read and checked more continuously\r\n\r\nThat's a good point too. The database is continuously being read and written, so the chance of an error in the i/o there might be higher (I have certainly seen cases of corruption not caused by CPU overheating, but by faulty USB sticks and SD cards).\r\n\r\nBut all in all we just don't know for sure. The *kind* of glitches (e.g. bit toggling, zeroed blocks, duplicated sequences, file truncation) might reveal more about the underlying cause. Which is why I'm trying to collect corrupted leveldb files.",
      "created_at" : "2017-11-16T16:01:43Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/11355#issuecomment-344969027",
      "id" : 344969027,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/11355",
      "updated_at" : "2017-11-16T16:04:13Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/344969027",
      "user" : {
         "avatar_url" : "https://avatars0.githubusercontent.com/u/126646?v=4",
         "events_url" : "https://api.github.com/users/laanwj/events{/privacy}",
         "followers_url" : "https://api.github.com/users/laanwj/followers",
         "following_url" : "https://api.github.com/users/laanwj/following{/other_user}",
         "gists_url" : "https://api.github.com/users/laanwj/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/laanwj",
         "id" : 126646,
         "login" : "laanwj",
         "organizations_url" : "https://api.github.com/users/laanwj/orgs",
         "received_events_url" : "https://api.github.com/users/laanwj/received_events",
         "repos_url" : "https://api.github.com/users/laanwj/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/laanwj/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/laanwj/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/laanwj"
      }
   },
   {
      "author_association" : "CONTRIBUTOR",
      "body" : "I'm running your patch and will attach corrupted db files when I next get a corruption.\r\n\r\nI have a bunch of old corrupt chainstate/ directories here. Is there a safe way of finding out which file in each is corrupted without corrupting my block index? I don't want to have to rescan everything again.",
      "created_at" : "2017-11-16T18:21:13Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/11355#issuecomment-345012359",
      "id" : 345012359,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/11355",
      "updated_at" : "2017-11-16T18:21:13Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/345012359",
      "user" : {
         "avatar_url" : "https://avatars3.githubusercontent.com/u/573356?v=4",
         "events_url" : "https://api.github.com/users/dooglus/events{/privacy}",
         "followers_url" : "https://api.github.com/users/dooglus/followers",
         "following_url" : "https://api.github.com/users/dooglus/following{/other_user}",
         "gists_url" : "https://api.github.com/users/dooglus/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/dooglus",
         "id" : 573356,
         "login" : "dooglus",
         "organizations_url" : "https://api.github.com/users/dooglus/orgs",
         "received_events_url" : "https://api.github.com/users/dooglus/received_events",
         "repos_url" : "https://api.github.com/users/dooglus/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/dooglus/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/dooglus/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/dooglus"
      }
   },
   {
      "author_association" : "OWNER",
      "body" : "> I have a bunch of old corrupt chainstate/ directories here. Is there a safe way of finding out which file in each is corrupted without corrupting my block index? I don't want to have to rescan everything again.\r\n\r\nNot easily. The only way I see to do this safely would be to use https://github.com/laanwj/blockdb-troubleshoot, which I've updated with the patch\r\n```bash\r\ngit clone https://github.com/laanwj/blockdb-troubleshoot.git\r\ncd blockdb-troubleshoot\r\n./compile_leveldb.sh\r\n...\r\n./simplecheck.py /path/to/corrupted/datadir/\r\n...\r\nleveldb.LevelDBError: Corruption: block checksum mismatch: /.../blocks/index/000042.ldb\r\n```\r\nThis will do a linear scan as well as some probing over the databases (chainstate and block index), and probably trigger it, though I've seen issues that are only triggered by specific random access to records!\r\n",
      "created_at" : "2017-11-16T20:26:27Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/11355#issuecomment-345052036",
      "id" : 345052036,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/11355",
      "updated_at" : "2017-11-16T20:26:27Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/345052036",
      "user" : {
         "avatar_url" : "https://avatars0.githubusercontent.com/u/126646?v=4",
         "events_url" : "https://api.github.com/users/laanwj/events{/privacy}",
         "followers_url" : "https://api.github.com/users/laanwj/followers",
         "following_url" : "https://api.github.com/users/laanwj/following{/other_user}",
         "gists_url" : "https://api.github.com/users/laanwj/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/laanwj",
         "id" : 126646,
         "login" : "laanwj",
         "organizations_url" : "https://api.github.com/users/laanwj/orgs",
         "received_events_url" : "https://api.github.com/users/laanwj/received_events",
         "repos_url" : "https://api.github.com/users/laanwj/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/laanwj/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/laanwj/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/laanwj"
      }
   },
   {
      "author_association" : "CONTRIBUTOR",
      "body" : "@laanwj Thanks, but that didn't show any errors. I commented out the check of `/blocks/index`, and switched in each of the old corrupt chainstate databases in turn:\r\n\r\n    $ ./simplecheck.py ~/.bitcoin # .bad\r\n    * Checking chain state\r\n     * opening /home/chris/.bitcoin/chainstate\r\n     * 51256562 records checked\r\n     * probe 10000 times (trigger bloom filters)\r\n    $ ./simplecheck.py ~/.bitcoin # .bad2\r\n    * Checking chain state\r\n     * opening /home/chris/.bitcoin/chainstate\r\n     * 51932124 records checked\r\n     * probe 10000 times (trigger bloom filters)\r\n    $ ./simplecheck.py ~/.bitcoin # .bad3\r\n    * Checking chain state\r\n     * opening /home/chris/.bitcoin/chainstate\r\n     * 52049450 records checked\r\n     * probe 10000 times (trigger bloom filters)\r\n    $ ./simplecheck.py ~/.bitcoin # .bad4\r\n    * Checking chain state\r\n     * opening /home/chris/.bitcoin/chainstate\r\n     * 52591784 records checked\r\n     * probe 10000 times (trigger bloom filters)\r\n    $ ./simplecheck.py ~/.bitcoin # .bad5\r\n    * Checking chain state\r\n     * opening /home/chris/.bitcoin/chainstate\r\n     * 52497622 records checked\r\n     * probe 10000 times (trigger bloom filters)\r\n    $ ",
      "created_at" : "2017-11-17T02:39:19Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/11355#issuecomment-345128588",
      "id" : 345128588,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/11355",
      "updated_at" : "2017-11-17T02:39:19Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/345128588",
      "user" : {
         "avatar_url" : "https://avatars3.githubusercontent.com/u/573356?v=4",
         "events_url" : "https://api.github.com/users/dooglus/events{/privacy}",
         "followers_url" : "https://api.github.com/users/dooglus/followers",
         "following_url" : "https://api.github.com/users/dooglus/following{/other_user}",
         "gists_url" : "https://api.github.com/users/dooglus/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/dooglus",
         "id" : 573356,
         "login" : "dooglus",
         "organizations_url" : "https://api.github.com/users/dooglus/orgs",
         "received_events_url" : "https://api.github.com/users/dooglus/received_events",
         "repos_url" : "https://api.github.com/users/dooglus/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/dooglus/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/dooglus/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/dooglus"
      }
   },
   {
      "author_association" : "OWNER",
      "body" : "I pushed an update to make it more sensitive (need to re-invoke `./compile_leveldb.sh`), apparently python-leveldb was ignoring errors during iteration.",
      "created_at" : "2017-11-17T12:21:55Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/11355#issuecomment-345230058",
      "id" : 345230058,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/11355",
      "updated_at" : "2017-11-17T12:21:55Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/345230058",
      "user" : {
         "avatar_url" : "https://avatars0.githubusercontent.com/u/126646?v=4",
         "events_url" : "https://api.github.com/users/laanwj/events{/privacy}",
         "followers_url" : "https://api.github.com/users/laanwj/followers",
         "following_url" : "https://api.github.com/users/laanwj/following{/other_user}",
         "gists_url" : "https://api.github.com/users/laanwj/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/laanwj",
         "id" : 126646,
         "login" : "laanwj",
         "organizations_url" : "https://api.github.com/users/laanwj/orgs",
         "received_events_url" : "https://api.github.com/users/laanwj/received_events",
         "repos_url" : "https://api.github.com/users/laanwj/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/laanwj/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/laanwj/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/laanwj"
      }
   }
]
