[
   {
      "author_association" : "CONTRIBUTOR",
      "body" : "I killed the hung process, started it again, let it get to within 4 blocks of the point it crashes, shut it down cleanly, then restarted it again. It crashed again, but got a few blocks further this time, getting to `height=485586` as opposed to 485584 last time. Also this time the error dialog showed the error message, and I was able to click it to exit bitcoin-qt cleanly.\r\n\r\n![screenshot_2017-09-16_13-08-09](https://user-images.githubusercontent.com/573356/30515629-bdf7397a-9ae0-11e7-9998-c2f7161f9b3c.png)\r\n",
      "created_at" : "2017-09-16T20:13:34Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/11355#issuecomment-329992182",
      "id" : 329992182,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/11355",
      "updated_at" : "2017-09-16T20:13:34Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/329992182",
      "user" : {
         "avatar_url" : "https://avatars3.githubusercontent.com/u/573356?v=4",
         "events_url" : "https://api.github.com/users/dooglus/events{/privacy}",
         "followers_url" : "https://api.github.com/users/dooglus/followers",
         "following_url" : "https://api.github.com/users/dooglus/following{/other_user}",
         "gists_url" : "https://api.github.com/users/dooglus/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/dooglus",
         "id" : 573356,
         "login" : "dooglus",
         "organizations_url" : "https://api.github.com/users/dooglus/orgs",
         "received_events_url" : "https://api.github.com/users/dooglus/received_events",
         "repos_url" : "https://api.github.com/users/dooglus/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/dooglus/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/dooglus/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/dooglus"
      }
   },
   {
      "author_association" : "CONTRIBUTOR",
      "body" : "I set a breakpoint:\r\n\r\n    (gdb) br leveldb::Status::Corruption\r\n    Breakpoint 3 at 0x555555acd1a2: leveldb::Status::Corruption. (9 locations)\r\n\r\nIt was hit:\r\n\r\n    Thread 20 \"bitcoin-msghand\" hit Breakpoint 4, leveldb::ReadBlock (file=<optimized out>, options=..., handle=..., result=0x7fffa6702378)\r\n        at leveldb/table/format.cc:95\r\n    95\t      s = Status::Corruption(\"block checksum mismatch\");\r\n    (gdb) where\r\n    #0  leveldb::ReadBlock (file=<optimized out>, options=..., handle=..., result=0x7fffa6702378) at leveldb/table/format.cc:95\r\n    #1  0x0000555555acd9f9 in leveldb::Table::BlockReader (arg=0x7fff8c176830, options=..., index_value=...) at leveldb/table/table.cc:189\r\n    #2  0x0000555555acde21 in leveldb::Table::InternalGet (this=0x7fff8c176830, options=..., k=..., arg=<optimized out>, saver=<optimized out>)\r\n        at leveldb/table/table.cc:241\r\n    #3  0x0000555555abf37c in leveldb::TableCache::Get (this=0x7fffb7560680, options=..., file_number=<optimized out>, file_size=<optimized out>, k=..., arg=0x140, \r\n        saver=0x7) at leveldb/db/table_cache.cc:115\r\n    #4  0x0000555555ac237a in leveldb::Version::Get (this=<optimized out>, options=..., k=..., value=<optimized out>, stats=<optimized out>)\r\n        at leveldb/db/version_set.cc:408\r\n    #5  0x0000555555ab6bf3 in leveldb::DBImpl::Get (this=0x7fffb7560940, options=..., key=..., value=0x7fffa67029e0) at leveldb/db/db_impl.cc:1141\r\n    #6  0x000055555588f609 in CDBWrapper::Read<(anonymous namespace)::CoinEntry, Coin> (this=<optimized out>, key=..., value=...) at ./dbwrapper.h:233\r\n    #7  CCoinsViewDB::GetCoin (this=0x7fffb755f2e0, outpoint=..., coin=...) at txdb.cpp:62\r\n    #8  0x0000555555a50107 in CCoinsViewBacked::GetCoin (this=<optimized out>, outpoint=..., coin=...) at coins.cpp:26\r\n    #9  0x000055555575c077 in CCoinsViewErrorCatcher::GetCoin (this=0x7fff8c000000, outpoint=..., coin=...) at init.cpp:141\r\n    #10 0x0000555555a50462 in CCoinsViewCache::FetchCoin (this=0x7fffb75641b0, outpoint=...) at coins.cpp:48\r\n    #11 0x0000555555a50549 in CCoinsViewCache::GetCoin (this=0x7fff8c000000, outpoint=..., coin=...) at coins.cpp:61\r\n    #12 0x0000555555a50462 in CCoinsViewCache::FetchCoin (this=0x7fffa6704440, outpoint=...) at coins.cpp:48\r\n    #13 0x0000555555a50b03 in CCoinsViewCache::HaveCoin (this=0x7fff8c000000, outpoint=...) at coins.cpp:129\r\n    #14 0x0000555555a51254 in CCoinsViewCache::HaveInputs (this=<optimized out>, tx=...) at coins.cpp:240\r\n    #15 0x00005555558d3210 in ConnectBlock (block=..., state=..., pindex=<optimized out>, view=..., chainparams=..., fJustCheck=<optimized out>) at validation.cpp:1763\r\n    #16 0x00005555558c676e in ConnectTip (state=..., chainparams=..., pindexNew=<optimized out>, connectTrace=..., disconnectpool=..., pblock=...)\r\n        at validation.cpp:2209\r\n    #17 ActivateBestChainStep (state=..., chainparams=..., pindexMostWork=<optimized out>, pblock=..., fInvalidFound=<optimized out>, connectTrace=...)\r\n        at validation.cpp:2354\r\n    #18 0x00005555558c5ad4 in ActivateBestChain (state=..., chainparams=..., pblock=...) at validation.cpp:2454\r\n    #19 0x00005555558cff58 in ProcessNewBlock (chainparams=..., pblock=warning: RTTI symbol not found for class 'std::_Sp_counted_ptr_inplace<CBlock, std::allocator<CBlock>, (__gnu_cxx::_Lock_policy)2>'\r\n    warning: RTTI symbol not found for class 'std::_Sp_counted_ptr_inplace<CBlock, std::allocator<CBlock>, (__gnu_cxx::_Lock_policy)2>'\r\n    std::shared_ptr (count 6, weak 0) 0x7fff8cd638e0, fForceProcessing=<optimized out>, \r\n        fNewBlock=0x7fffa6704aaf) at validation.cpp:3199\r\n    #20 0x00005555557beabf in ProcessMessage (pfrom=<optimized out>, strCommand=..., vRecv=..., nTimeReceived=<optimized out>, chainparams=..., \r\n        connman=<optimized out>, interruptMsgProc=...) at net_processing.cpp:2391\r\n    #21 0x00005555557adf12 in PeerLogicValidation::ProcessMessages (this=0x7fffc8410440, pfrom=0x7fff980008c0, interruptMsgProc=...) at net_processing.cpp:2718\r\n    #22 0x00005555557da037 in non-virtual thunk to PeerLogicValidation::ProcessMessages(CNode*, std::atomic<bool>&) () at net_processing.cpp:2643\r\n    #23 0x000055555578967b in CConnman::ThreadMessageHandler (this=<optimized out>) at net.cpp:1995\r\n    #24 0x00005555557a44ba in std::__invoke_impl<void, void (CConnman::* const&)(), CConnman*&> (__f=<optimized out>, __t=<optimized out>)\r\n        at /usr/bin/../lib/gcc/x86_64-linux-gnu/6.3.0/../../../../include/c++/6.3.0/functional:227\r\n    #25 std::__invoke<void (CConnman::* const&)(), CConnman*&> (__fn=<optimized out>, __args=<optimized out>)\r\n        at /usr/bin/../lib/gcc/x86_64-linux-gnu/6.3.0/../../../../include/c++/6.3.0/functional:250\r\n    #26 std::_Mem_fn_base<void (CConnman::*)(), true>::operator()<CConnman*&> (this=<optimized out>, __args=<optimized out>)\r\n        at /usr/bin/../lib/gcc/x86_64-linux-gnu/6.3.0/../../../../include/c++/6.3.0/functional:604\r\n    #27 std::_Bind<std::_Mem_fn<void (CConnman::*)()> (CConnman*)>::__call<void, , 0ul>(std::tuple<>&&, std::_Index_tuple<0ul>) (this=<optimized out>, \r\n        __args=<optimized out>) at /usr/bin/../lib/gcc/x86_64-linux-gnu/6.3.0/../../../../include/c++/6.3.0/functional:933\r\n    #28 std::_Bind<std::_Mem_fn<void (CConnman::*)()> (CConnman*)>::operator()<, void>() (this=<optimized out>)\r\n        at /usr/bin/../lib/gcc/x86_64-linux-gnu/6.3.0/../../../../include/c++/6.3.0/functional:991\r\n    #29 std::_Function_handler<void (), std::_Bind<std::_Mem_fn<void (CConnman::*)()> (CConnman*)> >::_M_invoke(std::_Any_data const&) (__functor=...)\r\n        at /usr/bin/../lib/gcc/x86_64-linux-gnu/6.3.0/../../../../include/c++/6.3.0/functional:1731\r\n    #30 0x0000555555758e3d in std::function<void ()>::operator()() const (this=0x7fffa670bd00)\r\n        at /usr/bin/../lib/gcc/x86_64-linux-gnu/6.3.0/../../../../include/c++/6.3.0/functional:2127\r\n    #31 TraceThread<std::function<void ()> >(char const*, std::function<void ()>) (name=<optimized out>, func=...) at ./util.h:309\r\n    #32 0x00005555557a467d in std::_Bind_simple<void (*(char const*, std::function<void ()>))(char const*, std::function<void ()>)>::_M_invoke<0ul, 1ul>(std::_Index_tuple<0ul, 1ul>) (this=<optimized out>) at /usr/bin/../lib/gcc/x86_64-linux-gnu/6.3.0/../../../../include/c++/6.3.0/functional:1390\r\n    #33 std::_Bind_simple<void (*(char const*, std::function<void ()>))(char const*, std::function<void ()>)>::operator()() (this=<optimized out>)\r\n        at /usr/bin/../lib/gcc/x86_64-linux-gnu/6.3.0/../../../../include/c++/6.3.0/functional:1380\r\n    #34 std::thread::_State_impl<std::_Bind_simple<void (*(char const*, std::function<void ()>))(char const*, std::function<void ()>)> >::_M_run() (\r\n        this=<optimized out>) at /usr/bin/../lib/gcc/x86_64-linux-gnu/6.3.0/../../../../include/c++/6.3.0/thread:197\r\n    #35 0x00007ffff452ce6f in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6\r\n    #36 0x00007ffff56f9494 in start_thread (arg=0x7fffa670c700) at pthread_create.c:333\r\n    #37 0x00007ffff3ca1aff in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:97\r\n    (gdb) \r\n\r\nSo it does look like my chainstate db is corrupted again doesn't it? I wonder if there's something wrong with the code that's causing this corruption. Should the db be able to get corrupted from random crashes?",
      "created_at" : "2017-09-16T20:22:37Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/11355#issuecomment-329992636",
      "id" : 329992636,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/11355",
      "updated_at" : "2017-09-16T20:22:37Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/329992636",
      "user" : {
         "avatar_url" : "https://avatars3.githubusercontent.com/u/573356?v=4",
         "events_url" : "https://api.github.com/users/dooglus/events{/privacy}",
         "followers_url" : "https://api.github.com/users/dooglus/followers",
         "following_url" : "https://api.github.com/users/dooglus/following{/other_user}",
         "gists_url" : "https://api.github.com/users/dooglus/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/dooglus",
         "id" : 573356,
         "login" : "dooglus",
         "organizations_url" : "https://api.github.com/users/dooglus/orgs",
         "received_events_url" : "https://api.github.com/users/dooglus/received_events",
         "repos_url" : "https://api.github.com/users/dooglus/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/dooglus/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/dooglus/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/dooglus"
      }
   },
   {
      "author_association" : "CONTRIBUTOR",
      "body" : "I have two separate Bitcoin data directories. One is a full node (and that's the one which is failing) and the other is pruned (`prune=600`).\r\n\r\nIs it safe to copy the `chainstate` folder from the pruned datadir into the full node's datadir to fix this corruption issue? Or do I need to run the >24h chainstate reindex thing again?\r\n\r\nEdit: it appears to have worked. I did this:\r\n\r\n* made a bootstrap.dat file that I used to sync the pruned node to the point where it returns the same for 'getblockcount' as the corrupted full node gives\r\n* stopped both nodes\r\n* deleted the corrupted chainstate folder\r\n* copied the pruned node's chainstate folder into the full node\r\n\r\nThen when I started the full node, it was able to continue syncing past the point it was previously failing.\r\n\r\nSo that seems like a good cheap way of recovering from chainstate db corruption, if you don't mind wasting the extra ~4GB of space for an extra pruned node. It can sync from the full node, so needn't add to your bandwidth requirements.",
      "created_at" : "2017-09-16T20:31:07Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/11355#issuecomment-329993047",
      "id" : 329993047,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/11355",
      "updated_at" : "2017-09-16T22:19:56Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/329993047",
      "user" : {
         "avatar_url" : "https://avatars3.githubusercontent.com/u/573356?v=4",
         "events_url" : "https://api.github.com/users/dooglus/events{/privacy}",
         "followers_url" : "https://api.github.com/users/dooglus/followers",
         "following_url" : "https://api.github.com/users/dooglus/following{/other_user}",
         "gists_url" : "https://api.github.com/users/dooglus/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/dooglus",
         "id" : 573356,
         "login" : "dooglus",
         "organizations_url" : "https://api.github.com/users/dooglus/orgs",
         "received_events_url" : "https://api.github.com/users/dooglus/received_events",
         "repos_url" : "https://api.github.com/users/dooglus/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/dooglus/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/dooglus/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/dooglus"
      }
   },
   {
      "author_association" : "NONE",
      "body" : "I experienced the same issue with my pruned node on a low end OSX computer on block #470915.\r\n\r\nI shut down Bitcoin QT and started it again >>> problem remained.\r\nI shut down my computer, restarted it, started Bitcoin QT again >>> problem has resolved itself.\r\n\r\nMy debug log:\r\n2017-09-18 04:46:34 UpdateTip: new best=000000000000000000051d8e3a33e4da2fdf008d35cf161382a5639e66b57c4a height=470914 version=0x20000000 log2_work=86.584992 tx=231183711 date='2017-06-12 06:50:28' progress=0.903516 cache=69.4MiB(516833txo)\r\n2017-09-18 04:46:34 UpdateTip: new best=00000000000000000004fcac1e558d2d6031d73b14db5cf67916f712081912e7 height=470915 version=0x20000002 log2_work=86.585028 tx=231184966 date='2017-06-12 06:50:36' progress=0.903521 cache=69.9MiB(521248txo)\r\n2017-09-18 04:46:35 LevelDB read failure: Corruption: block checksum mismatch\r\n2017-09-18 04:46:35 Corruption: block checksum mismatch\r\n2017-09-18 04:47:18 version handshake timeout from 5\r\n2017-09-18 04:47:19 version handshake timeout from 6",
      "created_at" : "2017-09-18T16:37:15Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/11355#issuecomment-330280417",
      "id" : 330280417,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/11355",
      "updated_at" : "2017-09-18T16:37:15Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/330280417",
      "user" : {
         "avatar_url" : "https://avatars3.githubusercontent.com/u/9769277?v=4",
         "events_url" : "https://api.github.com/users/jlegoupil/events{/privacy}",
         "followers_url" : "https://api.github.com/users/jlegoupil/followers",
         "following_url" : "https://api.github.com/users/jlegoupil/following{/other_user}",
         "gists_url" : "https://api.github.com/users/jlegoupil/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/jlegoupil",
         "id" : 9769277,
         "login" : "jlegoupil",
         "organizations_url" : "https://api.github.com/users/jlegoupil/orgs",
         "received_events_url" : "https://api.github.com/users/jlegoupil/received_events",
         "repos_url" : "https://api.github.com/users/jlegoupil/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/jlegoupil/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/jlegoupil/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/jlegoupil"
      }
   },
   {
      "author_association" : "CONTRIBUTOR",
      "body" : "@jlegoupil what version of Bitcoin Core were you using?\r\n\r\nI don't see why restarting your OS would help. That's strange.",
      "created_at" : "2017-09-18T16:51:31Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/11355#issuecomment-330284336",
      "id" : 330284336,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/11355",
      "updated_at" : "2017-09-18T16:51:31Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/330284336",
      "user" : {
         "avatar_url" : "https://avatars3.githubusercontent.com/u/573356?v=4",
         "events_url" : "https://api.github.com/users/dooglus/events{/privacy}",
         "followers_url" : "https://api.github.com/users/dooglus/followers",
         "following_url" : "https://api.github.com/users/dooglus/following{/other_user}",
         "gists_url" : "https://api.github.com/users/dooglus/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/dooglus",
         "id" : 573356,
         "login" : "dooglus",
         "organizations_url" : "https://api.github.com/users/dooglus/orgs",
         "received_events_url" : "https://api.github.com/users/dooglus/received_events",
         "repos_url" : "https://api.github.com/users/dooglus/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/dooglus/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/dooglus/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/dooglus"
      }
   },
   {
      "author_association" : "NONE",
      "body" : "I'm using Bitcoin Core 0.15.0.0",
      "created_at" : "2017-09-18T17:02:40Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/11355#issuecomment-330287557",
      "id" : 330287557,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/11355",
      "updated_at" : "2017-09-18T17:02:58Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/330287557",
      "user" : {
         "avatar_url" : "https://avatars3.githubusercontent.com/u/9769277?v=4",
         "events_url" : "https://api.github.com/users/jlegoupil/events{/privacy}",
         "followers_url" : "https://api.github.com/users/jlegoupil/followers",
         "following_url" : "https://api.github.com/users/jlegoupil/following{/other_user}",
         "gists_url" : "https://api.github.com/users/jlegoupil/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/jlegoupil",
         "id" : 9769277,
         "login" : "jlegoupil",
         "organizations_url" : "https://api.github.com/users/jlegoupil/orgs",
         "received_events_url" : "https://api.github.com/users/jlegoupil/received_events",
         "repos_url" : "https://api.github.com/users/jlegoupil/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/jlegoupil/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/jlegoupil/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/jlegoupil"
      }
   },
   {
      "author_association" : "CONTRIBUTOR",
      "body" : "It happened again to me, this time on shutdown:\r\n\r\n    2017-09-23 20:54:21 connect() to 59.127.26.8:8333 failed: Network is unreachable (101)\r\n    2017-09-23 20:54:21 connect() to 220.253.70.199:8333 failed: Network is unreachable (101)\r\n    2017-09-23 20:54:22 connect() to 77.181.226.122:8333 failed: Network is unreachable (101)\r\n    2017-09-23 20:54:22 connect() to 35.185.131.115:8333 failed: Network is unreachable (101)\r\n    2017-09-23 20:54:23 connect() to [2001:0:9d38:6ab8:3c62:f87e:95d8:bcd2]:8333 failed: Network is unreachable (101)\r\n    2017-09-23 20:54:23 connect() to 139.59.149.67:8333 failed: Network is unreachable (101)\r\n    2017-09-23 20:54:24 connect() to 188.195.24.170:8333 failed: Network is unreachable (101)\r\n    2017-09-23 20:54:24 connect() to 24.90.192.28:8333 failed: Network is unreachable (101)\r\n    2017-09-23 20:54:25 connect() to [2001:0:9d38:78cf:20d3:3c09:a9d2:703a]:8333 failed: Network is unreachable (101)\r\n    2017-09-23 20:54:25 addcon thread exit\r\n    2017-09-23 20:54:25 scheduler thread interrupt\r\n    2017-09-23 20:54:25 opencon thread exit\r\n    2017-09-23 20:54:25 Shutdown: In progress...\r\n    2017-09-23 20:54:25 net thread exit\r\n    2017-09-23 20:54:25 msghand thread exit\r\n    2017-09-23 20:54:25 Dumped mempool: 0.005588s to copy, 0.126193s to dump\r\n    2017-09-23 20:54:25 Corruption: block checksum mismatch\r\n    2017-09-23 20:54:25 *** System error while flushing: Database corrupted\r\n    2017-09-23 20:54:33 Corruption: block checksum mismatch\r\n    2017-09-23 20:54:33 *** System error while flushing: Database corrupted\r\n    2017-09-23 20:54:34 GUI: QXcbConnection: XCB error: 3 (BadWindow), sequence: 7465, resource id: 11515671, major code: 40 (TranslateCoords), minor code: 0\r\n    2017-09-23 20:54:34 Shutdown: done\r\n\r\nI was offline at the time, which explains all the \"Network is unreachable\" errors. Since the last time I fixed the chainstate db I never had Bitcoin crash, but I did have the laptop fail to resume from a suspend state once and had to do a cold reset. I guess that could have corrupted the db, but this really seems to be so much more common in 0.15 than it was before. This is the 3rd chainstate db corruption I've had with 0.15 compared to 6 years of corruption-free operation before 0.15.",
      "created_at" : "2017-09-23T20:57:57Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/11355#issuecomment-331669466",
      "id" : 331669466,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/11355",
      "updated_at" : "2017-09-23T20:57:57Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/331669466",
      "user" : {
         "avatar_url" : "https://avatars3.githubusercontent.com/u/573356?v=4",
         "events_url" : "https://api.github.com/users/dooglus/events{/privacy}",
         "followers_url" : "https://api.github.com/users/dooglus/followers",
         "following_url" : "https://api.github.com/users/dooglus/following{/other_user}",
         "gists_url" : "https://api.github.com/users/dooglus/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/dooglus",
         "id" : 573356,
         "login" : "dooglus",
         "organizations_url" : "https://api.github.com/users/dooglus/orgs",
         "received_events_url" : "https://api.github.com/users/dooglus/received_events",
         "repos_url" : "https://api.github.com/users/dooglus/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/dooglus/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/dooglus/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/dooglus"
      }
   },
   {
      "author_association" : "CONTRIBUTOR",
      "body" : "I'm still getting this chainstate database corruption fairly regularly.\r\n\r\nSince my last comment here it has happened three more times, on Oct 11th, 12th, and 22nd.\r\n\r\nThis seems like a serious issue to me, because once the chainstate database is corrupted it requires a full blockchain rescan to repair it. For a pruned node that means starting the IBD from scratch, and will likely lead to lots of full nodes going offline due to inertia.",
      "created_at" : "2017-10-22T17:59:17Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/11355#issuecomment-338496500",
      "id" : 338496500,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/11355",
      "updated_at" : "2017-10-22T17:59:17Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/338496500",
      "user" : {
         "avatar_url" : "https://avatars3.githubusercontent.com/u/573356?v=4",
         "events_url" : "https://api.github.com/users/dooglus/events{/privacy}",
         "followers_url" : "https://api.github.com/users/dooglus/followers",
         "following_url" : "https://api.github.com/users/dooglus/following{/other_user}",
         "gists_url" : "https://api.github.com/users/dooglus/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/dooglus",
         "id" : 573356,
         "login" : "dooglus",
         "organizations_url" : "https://api.github.com/users/dooglus/orgs",
         "received_events_url" : "https://api.github.com/users/dooglus/received_events",
         "repos_url" : "https://api.github.com/users/dooglus/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/dooglus/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/dooglus/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/dooglus"
      }
   },
   {
      "author_association" : "CONTRIBUTOR",
      "body" : "One thing occurs to me. If I leave my laptop unattended, the screen locks after 5 minutes. It used to be that when I unlocked the screen any browser tabs I had open would have been updating behind the scenes. But for the last couple of months I've noticed that having the screen locked seems to freeze things. I unlock the screen, and the price charts haven't updated since I left and such like.\r\n\r\nI don't know what would cause that, but I'm wondering if it could also be causing the chainstate corruption I'm seeing if I leave bitcoin-qt running while the screen is locked.\r\n\r\nJust a thought.",
      "created_at" : "2017-10-22T18:15:19Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/11355#issuecomment-338497609",
      "id" : 338497609,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/11355",
      "updated_at" : "2017-10-22T18:15:19Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/338497609",
      "user" : {
         "avatar_url" : "https://avatars3.githubusercontent.com/u/573356?v=4",
         "events_url" : "https://api.github.com/users/dooglus/events{/privacy}",
         "followers_url" : "https://api.github.com/users/dooglus/followers",
         "following_url" : "https://api.github.com/users/dooglus/following{/other_user}",
         "gists_url" : "https://api.github.com/users/dooglus/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/dooglus",
         "id" : 573356,
         "login" : "dooglus",
         "organizations_url" : "https://api.github.com/users/dooglus/orgs",
         "received_events_url" : "https://api.github.com/users/dooglus/received_events",
         "repos_url" : "https://api.github.com/users/dooglus/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/dooglus/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/dooglus/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/dooglus"
      }
   },
   {
      "author_association" : "CONTRIBUTOR",
      "body" : "My chainstate database was corrupted again last night when I tried to close bitcoin-qt. From the debug.log:\r\n\r\n    2017-10-25 23:38:25 opencon thread exit\r\n    2017-10-25 23:38:25 addcon thread exit\r\n    2017-10-25 23:38:25 net thread exit\r\n    2017-10-25 23:38:25 msghand thread exit\r\n    2017-10-25 23:38:25 scheduler thread interrupt\r\n    2017-10-25 23:38:25 Shutdown: In progress...\r\n    2017-10-25 23:38:26 Dumped mempool: 0.001688s to copy, 0.191935s to dump\r\n    2017-10-25 23:38:27 Corruption: block checksum mismatch\r\n    2017-10-25 23:38:27 *** System error while flushing: Database corrupted\r\n    2017-10-25 23:38:31 Corruption: block checksum mismatch\r\n    2017-10-25 23:38:31 *** System error while flushing: Database corrupted\r\n    2017-10-25 23:38:32 Shutdown: done\r\n\r\nEach time it has happened recently, I have synced up my pruned node to the same block that the corrupted node is at, renamed the corrupted node's chainstate directory, then copied the pruned node's chainstate directory into the corrupted node's .bitcoin directory. That has left me with a bunch of corrupted chainstate directories:\r\n\r\n    ~/.bitcoin$ du -m chain*\r\n    2812\tchainstate\r\n    2757\tchainstate.bad\r\n    2779\tchainstate.bad2\r\n    2800\tchainstate.bad3\r\n    2837\tchainstate.bad4\r\n    2842\tchainstate.bad5\r\n    ~/.bitcoin$ ls -ld chainstate*\r\n    drwx------ 2 chris chris 61440 Oct 26 08:34 chainstate\r\n    drwx------ 2 chris chris 69632 Sep 16 14:50 chainstate.bad\r\n    drwx------ 2 chris chris 61440 Oct 11 07:29 chainstate.bad2\r\n    drwx------ 2 chris chris 65536 Oct 12 22:10 chainstate.bad3\r\n    drwx------ 2 chris chris 61440 Oct 22 09:39 chainstate.bad4\r\n    drwx------ 2 chris chris 65536 Oct 26 00:19 chainstate.bad5\r\n\r\nI can make these available if that would be helpful (and if it is safe to do so).",
      "created_at" : "2017-10-26T15:41:48Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/11355#issuecomment-339708547",
      "id" : 339708547,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/11355",
      "updated_at" : "2017-10-26T15:41:48Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/339708547",
      "user" : {
         "avatar_url" : "https://avatars3.githubusercontent.com/u/573356?v=4",
         "events_url" : "https://api.github.com/users/dooglus/events{/privacy}",
         "followers_url" : "https://api.github.com/users/dooglus/followers",
         "following_url" : "https://api.github.com/users/dooglus/following{/other_user}",
         "gists_url" : "https://api.github.com/users/dooglus/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/dooglus",
         "id" : 573356,
         "login" : "dooglus",
         "organizations_url" : "https://api.github.com/users/dooglus/orgs",
         "received_events_url" : "https://api.github.com/users/dooglus/received_events",
         "repos_url" : "https://api.github.com/users/dooglus/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/dooglus/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/dooglus/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/dooglus"
      }
   },
   {
      "author_association" : "CONTRIBUTOR",
      "body" : "We should change the order of the log print & blocking message box calls so the corruption errors are printed in the log if the message box handler hangs:\r\n\r\n```diff\r\n--- a/src/init.cpp\r\n+++ b/src/init.cpp\r\n@@ -140,8 +140,8 @@ public:\r\n         try {\r\n             return CCoinsViewBacked::GetCoin(outpoint, coin);\r\n         } catch(const std::runtime_error& e) {\r\n-            uiInterface.ThreadSafeMessageBox(_(\"Error reading from database, shutting down.\"), \"\", CClientUIInterface::MSG_ERROR);\r\n             LogPrintf(\"Error reading from database: %s\\n\", e.what());\r\n+            uiInterface.ThreadSafeMessageBox(_(\"Error reading from database, shutting down.\"), \"\", CClientUIInterface::MSG_ERROR);\r\n             // Starting the shutdown sequence and returning false to the caller would be\r\n             // interpreted as 'entry not found' (as opposed to unable to read data), and\r\n             // could lead to invalid interpretation. Just exit immediately, as we can't\r\n```\r\n\r\nEDIT: Actually, it doesn't matter very much, since the full leveldb error is logged right before the exception is thrown: https://github.com/bitcoin/bitcoin/blob/50fae68d416b4b8ec4ca192923dfd5ae9ea42773/src/dbwrapper.cpp#L203",
      "created_at" : "2017-10-26T16:26:31Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/11355#issuecomment-339722095",
      "id" : 339722095,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/11355",
      "updated_at" : "2017-10-26T17:29:53Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/339722095",
      "user" : {
         "avatar_url" : "https://avatars2.githubusercontent.com/u/7133040?v=4",
         "events_url" : "https://api.github.com/users/ryanofsky/events{/privacy}",
         "followers_url" : "https://api.github.com/users/ryanofsky/followers",
         "following_url" : "https://api.github.com/users/ryanofsky/following{/other_user}",
         "gists_url" : "https://api.github.com/users/ryanofsky/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/ryanofsky",
         "id" : 7133040,
         "login" : "ryanofsky",
         "organizations_url" : "https://api.github.com/users/ryanofsky/orgs",
         "received_events_url" : "https://api.github.com/users/ryanofsky/received_events",
         "repos_url" : "https://api.github.com/users/ryanofsky/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/ryanofsky/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/ryanofsky/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/ryanofsky"
      }
   },
   {
      "author_association" : "CONTRIBUTOR",
      "body" : "I only saw the message box hang once. It happened the first time the database was corrupted, and never since.",
      "created_at" : "2017-10-26T16:29:26Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/11355#issuecomment-339722984",
      "id" : 339722984,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/11355",
      "updated_at" : "2017-10-26T16:29:26Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/339722984",
      "user" : {
         "avatar_url" : "https://avatars3.githubusercontent.com/u/573356?v=4",
         "events_url" : "https://api.github.com/users/dooglus/events{/privacy}",
         "followers_url" : "https://api.github.com/users/dooglus/followers",
         "following_url" : "https://api.github.com/users/dooglus/following{/other_user}",
         "gists_url" : "https://api.github.com/users/dooglus/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/dooglus",
         "id" : 573356,
         "login" : "dooglus",
         "organizations_url" : "https://api.github.com/users/dooglus/orgs",
         "received_events_url" : "https://api.github.com/users/dooglus/received_events",
         "repos_url" : "https://api.github.com/users/dooglus/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/dooglus/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/dooglus/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/dooglus"
      }
   },
   {
      "author_association" : "MEMBER",
      "body" : ">  seems to be so much more common in 0.15 than it was before\r\n\r\nSo this was also happening before?\r\n\r\nA checksum error is a really really cut and dry condition: The system read a record off the disk and the CRC32 didn't match.  We have never, so far, had a bug in the software which turned out to cause these errors: the cause has always been disk corruption due to a failing disk, faulty ram, or an overheating cpu. The latter of which is especially implicated in laptops (and other small systems) since most brands really just cannot handle being run at full intensity.  If prior versions did it as well and 0.15 is more frequent about it, it could just be because 0.15 hits the machine more intensely.\r\n\r\nBut it would be good to eliminate what other causes we can.. What exact cpu model and compiler version are you using?  Have you run Memtest86 on this system?",
      "created_at" : "2017-10-26T16:37:57Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/11355#issuecomment-339725394",
      "id" : 339725394,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/11355",
      "updated_at" : "2017-10-26T16:37:57Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/339725394",
      "user" : {
         "avatar_url" : "https://avatars1.githubusercontent.com/u/858454?v=4",
         "events_url" : "https://api.github.com/users/gmaxwell/events{/privacy}",
         "followers_url" : "https://api.github.com/users/gmaxwell/followers",
         "following_url" : "https://api.github.com/users/gmaxwell/following{/other_user}",
         "gists_url" : "https://api.github.com/users/gmaxwell/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/gmaxwell",
         "id" : 858454,
         "login" : "gmaxwell",
         "organizations_url" : "https://api.github.com/users/gmaxwell/orgs",
         "received_events_url" : "https://api.github.com/users/gmaxwell/received_events",
         "repos_url" : "https://api.github.com/users/gmaxwell/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/gmaxwell/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/gmaxwell/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/gmaxwell"
      }
   },
   {
      "author_association" : "CONTRIBUTOR",
      "body" : "Might be worth trying to store your chainstate on a zfs or btrfs partition to see if any corruption errors can be detected at the filesystem level. COW snapshots could also help you recover more quickly if there is corruption above the filesystem level.",
      "created_at" : "2017-10-26T16:54:32Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/11355#issuecomment-339730194",
      "id" : 339730194,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/11355",
      "updated_at" : "2017-10-26T16:54:32Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/339730194",
      "user" : {
         "avatar_url" : "https://avatars2.githubusercontent.com/u/7133040?v=4",
         "events_url" : "https://api.github.com/users/ryanofsky/events{/privacy}",
         "followers_url" : "https://api.github.com/users/ryanofsky/followers",
         "following_url" : "https://api.github.com/users/ryanofsky/following{/other_user}",
         "gists_url" : "https://api.github.com/users/ryanofsky/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/ryanofsky",
         "id" : 7133040,
         "login" : "ryanofsky",
         "organizations_url" : "https://api.github.com/users/ryanofsky/orgs",
         "received_events_url" : "https://api.github.com/users/ryanofsky/received_events",
         "repos_url" : "https://api.github.com/users/ryanofsky/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/ryanofsky/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/ryanofsky/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/ryanofsky"
      }
   },
   {
      "author_association" : "CONTRIBUTOR",
      "body" : "> So this was also happening before?\r\n\r\nI have had to run a full reindex maybe twice before 0.15, but both times were after I had had to do a cold reboot of my laptop while Core was running. I wasn't surprised that doing a cold reboot would cause problems.\r\n\r\nSince running 0.15 the chainstate database has become corrupted 7 times in 6 weeks. Most if not all of these happened without any cold restart happening.\r\n\r\n> the cause has always been disk corruption due to a failing disk, faulty ram, or an overheating cpu. The latter of which is especially implicated in laptops (and other small systems) since most brands really just cannot handle being run at full intensity. If prior versions did it as well and 0.15 is more frequent about it, it could just be because 0.15 hits the machine more intensely.\r\n\r\nAll 7 times it has been the chainstate db, not the block index db that was corrupted. I am running a laptop, but it isn't running at full intensity. The CPU isn't often running flat out.\r\n\r\n> But it would be good to eliminate what other causes we can.. What exact cpu model and compiler version are you using?\r\n\r\nAccording to /proc/cpuinfo, it's a 4 core i7-5500U:\r\n\r\n    $ grep 'model name' /proc/cpuinfo | uniq -c\r\n          4 model name\t: Intel(R) Core(TM) i7-5500U CPU @ 2.40GHz\r\n\r\nThe compiler version might be interesting. I switched from using gcc to clang a few months back when I was trying to debug [a crash I get on startup](https://github.com/bitcoin/bitcoin/issues/9683) about 1% of the time. I still see crashes when starting bitcoin-qt very occasionally. I saw one today in fact but I've given up trying to debug it.\r\n\r\n    $ clang++ -v\r\n    clang version 3.8.1-24 (tags/RELEASE_381/final)\r\n    Target: x86_64-pc-linux-gnu\r\n    Thread model: posix\r\n    InstalledDir: /usr/bin\r\n    Found candidate GCC installation: /usr/bin/../lib/gcc/i586-linux-gnu/4.9\r\n    Found candidate GCC installation: /usr/bin/../lib/gcc/i586-linux-gnu/4.9.2\r\n    Found candidate GCC installation: /usr/bin/../lib/gcc/i686-linux-gnu/6.3.0\r\n    Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/4.8\r\n    Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/4.8.4\r\n    Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/4.9\r\n    Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/4.9.2\r\n    Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/6.3.0\r\n    Found candidate GCC installation: /usr/lib/gcc/i586-linux-gnu/4.9\r\n    Found candidate GCC installation: /usr/lib/gcc/i586-linux-gnu/4.9.2\r\n    Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/6.3.0\r\n    Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.8\r\n    Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.8.4\r\n    Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.9\r\n    Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.9.2\r\n    Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/6.3.0\r\n    Selected GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/6.3.0\r\n    Candidate multilib: .;@m64\r\n    Selected multilib: .;@m64\r\n\r\n> Have you run Memtest86 on this system?\r\n\r\nI have, maybe 6 months ago. I let it run for a few hours and it didn't find any problems. I could try letting it run to completion. I have replaced the RAM since then actually so I should run it again anyway. Will report back.",
      "created_at" : "2017-10-26T17:23:25Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/11355#issuecomment-339738256",
      "id" : 339738256,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/11355",
      "updated_at" : "2017-10-26T17:23:25Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/339738256",
      "user" : {
         "avatar_url" : "https://avatars3.githubusercontent.com/u/573356?v=4",
         "events_url" : "https://api.github.com/users/dooglus/events{/privacy}",
         "followers_url" : "https://api.github.com/users/dooglus/followers",
         "following_url" : "https://api.github.com/users/dooglus/following{/other_user}",
         "gists_url" : "https://api.github.com/users/dooglus/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/dooglus",
         "id" : 573356,
         "login" : "dooglus",
         "organizations_url" : "https://api.github.com/users/dooglus/orgs",
         "received_events_url" : "https://api.github.com/users/dooglus/received_events",
         "repos_url" : "https://api.github.com/users/dooglus/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/dooglus/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/dooglus/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/dooglus"
      }
   },
   {
      "author_association" : "CONTRIBUTOR",
      "body" : "> Might be worth trying to store your chainstate on a zfs or btrfs partition to see if any corruption errors can be detected at the filesystem level. COW snapshots could also help you recover more quickly if there is corruption above the filesystem level.\r\n\r\nI have no experience of zfs or btrfs. Is one better than the other for this purpose? Do I need to set any particular configuration to detect filesystem corruption? I'm willing to experiment.",
      "created_at" : "2017-10-26T17:24:46Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/11355#issuecomment-339738622",
      "id" : 339738622,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/11355",
      "updated_at" : "2017-10-26T17:24:46Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/339738622",
      "user" : {
         "avatar_url" : "https://avatars3.githubusercontent.com/u/573356?v=4",
         "events_url" : "https://api.github.com/users/dooglus/events{/privacy}",
         "followers_url" : "https://api.github.com/users/dooglus/followers",
         "following_url" : "https://api.github.com/users/dooglus/following{/other_user}",
         "gists_url" : "https://api.github.com/users/dooglus/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/dooglus",
         "id" : 573356,
         "login" : "dooglus",
         "organizations_url" : "https://api.github.com/users/dooglus/orgs",
         "received_events_url" : "https://api.github.com/users/dooglus/received_events",
         "repos_url" : "https://api.github.com/users/dooglus/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/dooglus/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/dooglus/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/dooglus"
      }
   },
   {
      "author_association" : "CONTRIBUTOR",
      "body" : "Either should work fine, though btrfs is slightly better-supported in Linux-land, even if its newer/a bit less stable in strange edge-cases.",
      "created_at" : "2017-10-26T17:35:15Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/11355#issuecomment-339741490",
      "id" : 339741490,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/11355",
      "updated_at" : "2017-10-26T17:35:15Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/339741490",
      "user" : {
         "avatar_url" : "https://avatars0.githubusercontent.com/u/649246?v=4",
         "events_url" : "https://api.github.com/users/TheBlueMatt/events{/privacy}",
         "followers_url" : "https://api.github.com/users/TheBlueMatt/followers",
         "following_url" : "https://api.github.com/users/TheBlueMatt/following{/other_user}",
         "gists_url" : "https://api.github.com/users/TheBlueMatt/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/TheBlueMatt",
         "id" : 649246,
         "login" : "TheBlueMatt",
         "organizations_url" : "https://api.github.com/users/TheBlueMatt/orgs",
         "received_events_url" : "https://api.github.com/users/TheBlueMatt/received_events",
         "repos_url" : "https://api.github.com/users/TheBlueMatt/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/TheBlueMatt/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/TheBlueMatt/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/TheBlueMatt"
      }
   },
   {
      "author_association" : "CONTRIBUTOR",
      "body" : "Is it safe to assume that if bitcoin starts up successfully with the `-forcecompactdb` flag then the chainstate database currently doesn't have any checksum errors?",
      "created_at" : "2017-10-26T17:39:09Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/11355#issuecomment-339742636",
      "id" : 339742636,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/11355",
      "updated_at" : "2017-10-26T17:39:09Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/339742636",
      "user" : {
         "avatar_url" : "https://avatars3.githubusercontent.com/u/573356?v=4",
         "events_url" : "https://api.github.com/users/dooglus/events{/privacy}",
         "followers_url" : "https://api.github.com/users/dooglus/followers",
         "following_url" : "https://api.github.com/users/dooglus/following{/other_user}",
         "gists_url" : "https://api.github.com/users/dooglus/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/dooglus",
         "id" : 573356,
         "login" : "dooglus",
         "organizations_url" : "https://api.github.com/users/dooglus/orgs",
         "received_events_url" : "https://api.github.com/users/dooglus/received_events",
         "repos_url" : "https://api.github.com/users/dooglus/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/dooglus/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/dooglus/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/dooglus"
      }
   },
   {
      "author_association" : "CONTRIBUTOR",
      "body" : "> I have no experience of zfs or btrfs. Is one better than the other for this purpose? Do I need to set any particular configuration to detect filesystem corruption? I'm willing to experiment\r\n\r\nPersonally I've only used btrfs, not zfs. But neither require configuration to detect corruption, you just need to create a partition, store data on it, and any errors should show up in your system log (and be returned to applications). In btrfs, if you want to create a COW snapshot of a file or directory, you can run `cp -a --reflink SRC DEST`.\r\n\r\n> Is it safe to assume that if bitcoin starts up successfully with the -forcecompactdb flag then the chainstate database currently doesn't have any checksum errors?\r\n\r\nI would guess not. From https://github.com/google/leveldb/blob/master/doc/impl.md, it doesn't seem like a compaction will necessarily rewrite the whole database (for example if it is already compacted). \r\n\r\nMaybe one way to manually verify there are no checksum errors in the database would be to add error reporting to leveldb dump code in src/leveldb/db/dumpfile.cc, which can be run with:\r\n\r\n```sh\r\nmake -C src/leveldb out-static/leveldbutil\r\nsrc/leveldb/out-static/leveldbutil dump ~/.bitcoin/chainstate/*\r\n```",
      "created_at" : "2017-10-26T18:14:29Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/11355#issuecomment-339752813",
      "id" : 339752813,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/11355",
      "updated_at" : "2017-10-26T18:14:29Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/339752813",
      "user" : {
         "avatar_url" : "https://avatars2.githubusercontent.com/u/7133040?v=4",
         "events_url" : "https://api.github.com/users/ryanofsky/events{/privacy}",
         "followers_url" : "https://api.github.com/users/ryanofsky/followers",
         "following_url" : "https://api.github.com/users/ryanofsky/following{/other_user}",
         "gists_url" : "https://api.github.com/users/ryanofsky/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/ryanofsky",
         "id" : 7133040,
         "login" : "ryanofsky",
         "organizations_url" : "https://api.github.com/users/ryanofsky/orgs",
         "received_events_url" : "https://api.github.com/users/ryanofsky/received_events",
         "repos_url" : "https://api.github.com/users/ryanofsky/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/ryanofsky/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/ryanofsky/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/ryanofsky"
      }
   }
]
