[
   {
      "author_association" : "NONE",
      "body" : "Can somebody elaborate on how to produce the error. It seems the coverage report is still generated fine even given individual functional tests failed",
      "created_at" : "2019-04-08T03:20:22Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/15648#issuecomment-480669693",
      "id" : 480669693,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/15648",
      "node_id" : "MDEyOklzc3VlQ29tbWVudDQ4MDY2OTY5Mw==",
      "updated_at" : "2019-04-08T03:20:22Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/480669693",
      "user" : {
         "avatar_url" : "https://avatars0.githubusercontent.com/u/3409608?v=4",
         "events_url" : "https://api.github.com/users/crackercracked/events{/privacy}",
         "followers_url" : "https://api.github.com/users/crackercracked/followers",
         "following_url" : "https://api.github.com/users/crackercracked/following{/other_user}",
         "gists_url" : "https://api.github.com/users/crackercracked/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/crackercracked",
         "id" : 3409608,
         "login" : "crackercracked",
         "node_id" : "MDQ6VXNlcjM0MDk2MDg=",
         "organizations_url" : "https://api.github.com/users/crackercracked/orgs",
         "received_events_url" : "https://api.github.com/users/crackercracked/received_events",
         "repos_url" : "https://api.github.com/users/crackercracked/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/crackercracked/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/crackercracked/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/crackercracked"
      }
   },
   {
      "author_association" : "MEMBER",
      "body" : "> It seems the coverage report is still generated fine even given individual functional tests failed\r\n\r\nThe file is generated, but is obviously missing the coverage of the remainder of the test that failed. So it should have never been generated in the first place.",
      "created_at" : "2019-04-08T15:08:45Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/15648#issuecomment-480872499",
      "id" : 480872499,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/15648",
      "node_id" : "MDEyOklzc3VlQ29tbWVudDQ4MDg3MjQ5OQ==",
      "updated_at" : "2019-04-08T15:08:45Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/480872499",
      "user" : {
         "avatar_url" : "https://avatars0.githubusercontent.com/u/6399679?v=4",
         "events_url" : "https://api.github.com/users/MarcoFalke/events{/privacy}",
         "followers_url" : "https://api.github.com/users/MarcoFalke/followers",
         "following_url" : "https://api.github.com/users/MarcoFalke/following{/other_user}",
         "gists_url" : "https://api.github.com/users/MarcoFalke/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/MarcoFalke",
         "id" : 6399679,
         "login" : "MarcoFalke",
         "node_id" : "MDQ6VXNlcjYzOTk2Nzk=",
         "organizations_url" : "https://api.github.com/users/MarcoFalke/orgs",
         "received_events_url" : "https://api.github.com/users/MarcoFalke/received_events",
         "repos_url" : "https://api.github.com/users/MarcoFalke/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/MarcoFalke/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/MarcoFalke/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/MarcoFalke"
      }
   }
]
