[
   {
      "body" : "Travis failure unrelated (wallet.py -salvagewallet failure which I'm not able to reproduce locally anymore :-(().\r\n\r\nACK https://github.com/bitcoin/bitcoin/pull/7962/commits/c7aac2d557fe3d3aa5bcdd3301a9b87eb110d8ed",
      "created_at" : "2016-04-28T05:15:34Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/pull/7962#issuecomment-215312309",
      "id" : 215312309,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/7962",
      "updated_at" : "2016-04-28T05:15:34Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/215312309",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/6848764?v=3",
         "events_url" : "https://api.github.com/users/paveljanik/events{/privacy}",
         "followers_url" : "https://api.github.com/users/paveljanik/followers",
         "following_url" : "https://api.github.com/users/paveljanik/following{/other_user}",
         "gists_url" : "https://api.github.com/users/paveljanik/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/paveljanik",
         "id" : 6848764,
         "login" : "paveljanik",
         "organizations_url" : "https://api.github.com/users/paveljanik/orgs",
         "received_events_url" : "https://api.github.com/users/paveljanik/received_events",
         "repos_url" : "https://api.github.com/users/paveljanik/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/paveljanik/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/paveljanik/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/paveljanik"
      }
   }
]
