[
   {
      "author_association" : "MEMBER",
      "body" : "Thanks for looking at this, will review.",
      "created_at" : "2020-09-04T20:40:59Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/pull/19876#issuecomment-687372089",
      "id" : 687372089,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/19876",
      "node_id" : "MDEyOklzc3VlQ29tbWVudDY4NzM3MjA4OQ==",
      "performed_via_github_app" : null,
      "updated_at" : "2020-09-04T20:40:59Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/687372089",
      "user" : {
         "avatar_url" : "https://avatars1.githubusercontent.com/u/2415484?v=4",
         "events_url" : "https://api.github.com/users/jonatack/events{/privacy}",
         "followers_url" : "https://api.github.com/users/jonatack/followers",
         "following_url" : "https://api.github.com/users/jonatack/following{/other_user}",
         "gists_url" : "https://api.github.com/users/jonatack/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/jonatack",
         "id" : 2415484,
         "login" : "jonatack",
         "node_id" : "MDQ6VXNlcjI0MTU0ODQ=",
         "organizations_url" : "https://api.github.com/users/jonatack/orgs",
         "received_events_url" : "https://api.github.com/users/jonatack/received_events",
         "repos_url" : "https://api.github.com/users/jonatack/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/jonatack/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/jonatack/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/jonatack"
      }
   },
   {
      "author_association" : "MEMBER",
      "body" : "We currently track what wallets are currently loading (see `CWallet::LoadWallet`) to avoid a different race condition. I think we could reuse that for the startup wallet loading. Then in the RPC, `GetWalletForJSONRPCRequest` should check that the wallet isn't in the list of loading wallets. If it is, it should raise an exception. I don't think that returning NullUniValue is the correct way to handle this error.",
      "created_at" : "2020-09-04T21:58:44Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/pull/19876#issuecomment-687413170",
      "id" : 687413170,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/19876",
      "node_id" : "MDEyOklzc3VlQ29tbWVudDY4NzQxMzE3MA==",
      "performed_via_github_app" : null,
      "updated_at" : "2020-09-04T21:58:44Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/687413170",
      "user" : {
         "avatar_url" : "https://avatars3.githubusercontent.com/u/3782274?v=4",
         "events_url" : "https://api.github.com/users/achow101/events{/privacy}",
         "followers_url" : "https://api.github.com/users/achow101/followers",
         "following_url" : "https://api.github.com/users/achow101/following{/other_user}",
         "gists_url" : "https://api.github.com/users/achow101/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/achow101",
         "id" : 3782274,
         "login" : "achow101",
         "node_id" : "MDQ6VXNlcjM3ODIyNzQ=",
         "organizations_url" : "https://api.github.com/users/achow101/orgs",
         "received_events_url" : "https://api.github.com/users/achow101/received_events",
         "repos_url" : "https://api.github.com/users/achow101/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/achow101/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/achow101/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/achow101"
      }
   },
   {
      "author_association" : "CONTRIBUTOR",
      "body" : "> Just needs a call to `syncwithvalidationinterfacequeue` before `getbalance`?\r\n\r\nYes, this fixes the test. Initially, I was hoping I could fix the test and the underlying race issue in one PR but since the race fix is a bit more complicated I think it makes sense to split it from the test fix, so the CI failures stop as fast as possible. I opened it in #19887 and made you co-author.",
      "created_at" : "2020-09-05T18:09:13Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/pull/19876#issuecomment-687643549",
      "id" : 687643549,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/19876",
      "node_id" : "MDEyOklzc3VlQ29tbWVudDY4NzY0MzU0OQ==",
      "performed_via_github_app" : null,
      "updated_at" : "2020-09-05T18:09:13Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/687643549",
      "user" : {
         "avatar_url" : "https://avatars2.githubusercontent.com/u/1322187?v=4",
         "events_url" : "https://api.github.com/users/fjahr/events{/privacy}",
         "followers_url" : "https://api.github.com/users/fjahr/followers",
         "following_url" : "https://api.github.com/users/fjahr/following{/other_user}",
         "gists_url" : "https://api.github.com/users/fjahr/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/fjahr",
         "id" : 1322187,
         "login" : "fjahr",
         "node_id" : "MDQ6VXNlcjEzMjIxODc=",
         "organizations_url" : "https://api.github.com/users/fjahr/orgs",
         "received_events_url" : "https://api.github.com/users/fjahr/received_events",
         "repos_url" : "https://api.github.com/users/fjahr/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/fjahr/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/fjahr/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/fjahr"
      }
   },
   {
      "author_association" : "MEMBER",
      "body" : "Is this really a bug? The wallet is just \"catching up\" (?)",
      "created_at" : "2020-09-05T19:53:59Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/pull/19876#issuecomment-687655400",
      "id" : 687655400,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/19876",
      "node_id" : "MDEyOklzc3VlQ29tbWVudDY4NzY1NTQwMA==",
      "performed_via_github_app" : null,
      "updated_at" : "2020-09-05T19:53:59Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/687655400",
      "user" : {
         "avatar_url" : "https://avatars1.githubusercontent.com/u/3534524?v=4",
         "events_url" : "https://api.github.com/users/promag/events{/privacy}",
         "followers_url" : "https://api.github.com/users/promag/followers",
         "following_url" : "https://api.github.com/users/promag/following{/other_user}",
         "gists_url" : "https://api.github.com/users/promag/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/promag",
         "id" : 3534524,
         "login" : "promag",
         "node_id" : "MDQ6VXNlcjM1MzQ1MjQ=",
         "organizations_url" : "https://api.github.com/users/promag/orgs",
         "received_events_url" : "https://api.github.com/users/promag/received_events",
         "repos_url" : "https://api.github.com/users/promag/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/promag/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/promag/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/promag"
      }
   },
   {
      "author_association" : "CONTRIBUTOR",
      "body" : "> Is this really a bug? The wallet is just \"catching up\" (?)\r\n\r\nYes, it's catching up but while it's doing that it responds with a false balance to a `getbalance` request, which could mean the wallet has been hacked or it's broken. Instead, there should be an actual error that indicates that it's catching up or just anything that does not look like a real balance.",
      "created_at" : "2020-09-05T20:01:46Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/pull/19876#issuecomment-687656316",
      "id" : 687656316,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/19876",
      "node_id" : "MDEyOklzc3VlQ29tbWVudDY4NzY1NjMxNg==",
      "performed_via_github_app" : null,
      "updated_at" : "2020-09-05T20:01:46Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/687656316",
      "user" : {
         "avatar_url" : "https://avatars2.githubusercontent.com/u/1322187?v=4",
         "events_url" : "https://api.github.com/users/fjahr/events{/privacy}",
         "followers_url" : "https://api.github.com/users/fjahr/followers",
         "following_url" : "https://api.github.com/users/fjahr/following{/other_user}",
         "gists_url" : "https://api.github.com/users/fjahr/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/fjahr",
         "id" : 1322187,
         "login" : "fjahr",
         "node_id" : "MDQ6VXNlcjEzMjIxODc=",
         "organizations_url" : "https://api.github.com/users/fjahr/orgs",
         "received_events_url" : "https://api.github.com/users/fjahr/received_events",
         "repos_url" : "https://api.github.com/users/fjahr/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/fjahr/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/fjahr/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/fjahr"
      }
   },
   {
      "author_association" : "MEMBER",
      "body" : "The balance is fine I think, the wallet isn't aware of the mempool yet right? So, the wallet itself is loaded, but not synced.",
      "created_at" : "2020-09-05T20:30:44Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/pull/19876#issuecomment-687659313",
      "id" : 687659313,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/19876",
      "node_id" : "MDEyOklzc3VlQ29tbWVudDY4NzY1OTMxMw==",
      "performed_via_github_app" : null,
      "updated_at" : "2020-09-05T20:31:01Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/687659313",
      "user" : {
         "avatar_url" : "https://avatars1.githubusercontent.com/u/3534524?v=4",
         "events_url" : "https://api.github.com/users/promag/events{/privacy}",
         "followers_url" : "https://api.github.com/users/promag/followers",
         "following_url" : "https://api.github.com/users/promag/following{/other_user}",
         "gists_url" : "https://api.github.com/users/promag/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/promag",
         "id" : 3534524,
         "login" : "promag",
         "node_id" : "MDQ6VXNlcjM1MzQ1MjQ=",
         "organizations_url" : "https://api.github.com/users/promag/orgs",
         "received_events_url" : "https://api.github.com/users/promag/received_events",
         "repos_url" : "https://api.github.com/users/promag/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/promag/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/promag/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/promag"
      }
   },
   {
      "author_association" : "CONTRIBUTOR",
      "body" : "> The balance is fine I think, the wallet isn't aware of the mempool yet right? So, the wallet itself is loaded, but not synced.\r\n\r\nAs a user, I would expect that the wallet would report my own change output in the balance even if the mempool is still syncing. But I will have to review that code and maybe I am off on that. The many reports in the CI failure issue in the span of 2 days suggest that this is hit pretty frequently on startup and I think we should minimize the potential of reporting unexpected balances to users. But if others agree that this is not a big deal, I will close it.",
      "created_at" : "2020-09-05T21:21:26Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/pull/19876#issuecomment-687664726",
      "id" : 687664726,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/19876",
      "node_id" : "MDEyOklzc3VlQ29tbWVudDY4NzY2NDcyNg==",
      "performed_via_github_app" : null,
      "updated_at" : "2020-09-05T21:21:26Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/687664726",
      "user" : {
         "avatar_url" : "https://avatars2.githubusercontent.com/u/1322187?v=4",
         "events_url" : "https://api.github.com/users/fjahr/events{/privacy}",
         "followers_url" : "https://api.github.com/users/fjahr/followers",
         "following_url" : "https://api.github.com/users/fjahr/following{/other_user}",
         "gists_url" : "https://api.github.com/users/fjahr/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/fjahr",
         "id" : 1322187,
         "login" : "fjahr",
         "node_id" : "MDQ6VXNlcjEzMjIxODc=",
         "organizations_url" : "https://api.github.com/users/fjahr/orgs",
         "received_events_url" : "https://api.github.com/users/fjahr/received_events",
         "repos_url" : "https://api.github.com/users/fjahr/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/fjahr/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/fjahr/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/fjahr"
      }
   }
]
