[
   {
      "author_association" : "MEMBER",
      "body" : "Does this only occur on signet?",
      "created_at" : "2021-07-18T22:41:25Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/22489#issuecomment-882126090",
      "id" : 882126090,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/22489",
      "node_id" : "IC_kwDOABII5840lC0K",
      "performed_via_github_app" : null,
      "updated_at" : "2021-07-18T22:41:25Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/882126090",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/3782274?v=4",
         "events_url" : "https://api.github.com/users/achow101/events{/privacy}",
         "followers_url" : "https://api.github.com/users/achow101/followers",
         "following_url" : "https://api.github.com/users/achow101/following{/other_user}",
         "gists_url" : "https://api.github.com/users/achow101/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/achow101",
         "id" : 3782274,
         "login" : "achow101",
         "node_id" : "MDQ6VXNlcjM3ODIyNzQ=",
         "organizations_url" : "https://api.github.com/users/achow101/orgs",
         "received_events_url" : "https://api.github.com/users/achow101/received_events",
         "repos_url" : "https://api.github.com/users/achow101/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/achow101/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/achow101/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/achow101"
      }
   },
   {
      "author_association" : "NONE",
      "body" : "I just got this same error on testnet.\r\nSo it is not related to the network. ",
      "created_at" : "2021-07-18T23:09:00Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/22489#issuecomment-882129180",
      "id" : 882129180,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/22489",
      "node_id" : "IC_kwDOABII5840lDkc",
      "performed_via_github_app" : null,
      "updated_at" : "2021-07-18T23:09:00Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/882129180",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/84432093?v=4",
         "events_url" : "https://api.github.com/users/lsilva01/events{/privacy}",
         "followers_url" : "https://api.github.com/users/lsilva01/followers",
         "following_url" : "https://api.github.com/users/lsilva01/following{/other_user}",
         "gists_url" : "https://api.github.com/users/lsilva01/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/lsilva01",
         "id" : 84432093,
         "login" : "lsilva01",
         "node_id" : "MDQ6VXNlcjg0NDMyMDkz",
         "organizations_url" : "https://api.github.com/users/lsilva01/orgs",
         "received_events_url" : "https://api.github.com/users/lsilva01/received_events",
         "repos_url" : "https://api.github.com/users/lsilva01/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/lsilva01/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/lsilva01/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/lsilva01"
      }
   },
   {
      "author_association" : "CONTRIBUTOR",
      "body" : "> I just got this same error on testnet.\r\nSo it is not related to the network.\r\n\r\nI get this error when I use `-datadir` while running `bitcoind` and forget to add it in `bitcoin-cli` command.\r\n\r\nMaybe you can try adding `-datadir` if you have used it while running `bitcoind` or check other things which maybe the reason why `bitcoin-cli` is unable to connect with `bitcoind` if it is running.",
      "created_at" : "2021-07-18T23:37:19Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/22489#issuecomment-882133530",
      "id" : 882133530,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/22489",
      "node_id" : "IC_kwDOABII5840lEoa",
      "performed_via_github_app" : null,
      "updated_at" : "2021-07-18T23:37:19Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/882133530",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/13405205?v=4",
         "events_url" : "https://api.github.com/users/prayank23/events{/privacy}",
         "followers_url" : "https://api.github.com/users/prayank23/followers",
         "following_url" : "https://api.github.com/users/prayank23/following{/other_user}",
         "gists_url" : "https://api.github.com/users/prayank23/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/prayank23",
         "id" : 13405205,
         "login" : "prayank23",
         "node_id" : "MDQ6VXNlcjEzNDA1MjA1",
         "organizations_url" : "https://api.github.com/users/prayank23/orgs",
         "received_events_url" : "https://api.github.com/users/prayank23/received_events",
         "repos_url" : "https://api.github.com/users/prayank23/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/prayank23/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/prayank23/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/prayank23"
      }
   },
   {
      "author_association" : "NONE",
      "body" : "The reason `bitcoin-cli` cannot connect to `bitcoind` is because this exception causes the node to shut down.\r\n\r\nI'm running the node with `bitcoind -testnet`, so it's getting the default `datadir`, which is `~/.bitcoin/testnet3`.\r\nOr `~/.bitcoin/signet` for signet.\r\n\r\nAfter the error occurred on testnet, I am unable to dump the wallets again on this network. I delete the bitcoin node directory and cloned it again from Github., I also unloaded and loaded the wallet, but the error persists.",
      "created_at" : "2021-07-18T23:48:38Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/22489#issuecomment-882135335",
      "id" : 882135335,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/22489",
      "node_id" : "IC_kwDOABII5840lFEn",
      "performed_via_github_app" : null,
      "updated_at" : "2021-07-18T23:51:50Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/882135335",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/84432093?v=4",
         "events_url" : "https://api.github.com/users/lsilva01/events{/privacy}",
         "followers_url" : "https://api.github.com/users/lsilva01/followers",
         "following_url" : "https://api.github.com/users/lsilva01/following{/other_user}",
         "gists_url" : "https://api.github.com/users/lsilva01/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/lsilva01",
         "id" : 84432093,
         "login" : "lsilva01",
         "node_id" : "MDQ6VXNlcjg0NDMyMDkz",
         "organizations_url" : "https://api.github.com/users/lsilva01/orgs",
         "received_events_url" : "https://api.github.com/users/lsilva01/received_events",
         "repos_url" : "https://api.github.com/users/lsilva01/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/lsilva01/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/lsilva01/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/lsilva01"
      }
   }
]
